// Autogenerated by GOALS Data Pipeline from 07_oort.md
import { Question } from '../../types';

export const test07_Oort: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué hito de distancia histórica alcanza la sonda Voyager 1 hacia finales de 2026?",
    "options": [
      "Situarse a 1 Día-Luz de la Tierra (~25.900 millones de km), requiriendo 24 horas para que una señal de radio llegue a la nave",
      "Entrar en órbita alrededor de Próxima Centauri",
      "Aterrizar sobre el cometa Halley",
      "Regresar a la Tierra impulsada por gravedad"
    ],
    "answer": 0,
    "explanation": "A 1 Día-Luz de distancia, la radiación electromagnética (viajando a 300.000 km/s) tarda 24 horas completas en recorrer la distancia entre la Tierra y la nave."
  },
  {
    "type": "choice",
    "question": "¿Qué es la Nube de Oort según la astrofísica planetaria?",
    "options": [
      "Una gigantesca cáscara esférica de billones de cometas helados que envuelve al Sistema Solar hasta 100.000 UA",
      "Una nube de polvo que oscurece el disco solar en invierno",
      "Un anillo plano de asteroides metálicos entre Marte y Júpiter",
      "La atmósfera gaseosa del planeta Plutón"
    ],
    "answer": 0,
    "explanation": "Propuesta por el astrónomo Jan Oort, es una nube esférica que marca el límite gravitatorio del Sistema Solar y el reservorio de los cometas de largo período."
  },
  {
    "type": "choice",
    "question": "¿Qué mensaje transportan las sondas Voyager grabado en su emblemático Disco de Oro?",
    "options": [
      "Sonidos de la Tierra, música de diversas culturas, saludos en 55 idiomas, diagramas anatómicos y coordenadas estelares",
      "Un plano secreto de depósitos de combustible nuclear",
      "Una lista clasificada de astronautas militares",
      "Un disco duro digital con código binario ejecutable"
    ],
    "answer": 0,
    "explanation": "Diseñado por un comité presidido por Carl Sagan, el Disco de Oro es una cápsula cultural y biológica fonográfica diseñada para durar más de 1.000 millones de años.",
    "photo": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué frontera delimita el final de la Heliosfera solar y el inicio del espacio interestelar?",
    "options": [
      "La Heliopausa (a unas ~120 UA), donde el viento solar se frena contra el medio interestelar",
      "La órbita de la Luna a 384.400 km",
      "El Cinturón de Asteroides a 2,8 UA",
      "El centro de la Vía Láctea"
    ],
    "answer": 0,
    "explanation": "La Heliopausa es la frontera física donde la presión hacia afuera del viento solar se equilibra con la presión del gas interestelar galáctico."
  },
  {
    "type": "order",
    "question": "Ordena las regiones del Sistema Solar exterior desde el Sol hacia las estrellas vecinas:",
    "items": [
      "Cinturón de Kuiper (30 a 55 UA - Planetas enanos como Plutón)",
      "Choque de Terminación (~80 a 90 UA - Frenado del viento solar)",
      "Heliopausa (~120 UA - Frontera interestelar oficial)",
      "Nube de Oort interior (~2.000 a 20.000 UA)",
      "Límite exterior de la Nube de Oort (~100.000 UA - Frontera gravitatoria solar)"
    ],
    "correctOrder": [
      "Cinturón de Kuiper (30 a 55 UA - Planetas enanos como Plutón)",
      "Choque de Terminación (~80 a 90 UA - Frenado del viento solar)",
      "Heliopausa (~120 UA - Frontera interestelar oficial)",
      "Nube de Oort interior (~2.000 a 20.000 UA)",
      "Límite exterior de la Nube de Oort (~100.000 UA - Frontera gravitatoria solar)"
    ],
    "explanation": "La arquitectura externa progresa desde el cinturón transneptuniano hasta la heliopausa y la inmensa esfera de cometas de Oort."
  }
];
