// Autogenerated by GOALS Data Pipeline from 08_estrellas_vecinas_alfa_centauri_y_proxima_centauri.md
import { Question } from '../../types';

export const test08_Estrellas_vecinas_alfa_centauri_y_proxima_centauri: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuál es la estrella individual más cercana a nuestro Sistema Solar?",
    "options": [
      "Próxima Centauri (a 4,24 años luz)",
      "Sirio (a 8,6 años luz)",
      "Betelgeuse (a 640 años luz)",
      "Estrella Polar (a 430 años luz)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué es exactamente un 'año luz'?",
    "options": [
      "La distancia que recorre la luz en el vacío en un año (~9,46 billones de km)",
      "El tiempo que tarda la Tierra en dar una vuelta completa al Sol",
      "La cantidad de luz que emite una estrella en 12 meses",
      "La distancia que hay entre el Sol y Plutón"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena estos sistemas estelares desde el MÁS CERCANO a la Tierra hasta el MÁS LEJANO:",
    "items": [
      "Próxima Centauri (4,24 al)",
      "Estrella de Barnard (5,96 al)",
      "Sirio (8,6 al)",
      "Épsilon Eridani (10,5 al)"
    ],
    "correctOrder": [
      "Próxima Centauri (4,24 al)",
      "Estrella de Barnard (5,96 al)",
      "Sirio (8,6 al)",
      "Épsilon Eridani (10,5 al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué característica especial tiene el exoplaneta Próxima b?",
    "options": [
      "Es un planeta rocoso situado en la zona habitable de Próxima Centauri",
      "Es un gigante de gas con anillos como Saturno",
      "Está cubierto enteramente por un océano de lava a 2.000 °C",
      "No gira alrededor de ninguna estrella"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
