// Autogenerated by GOALS Data Pipeline from 04_orbit.md
import { Question } from '../../types';

export const test04_Orbit: Question[] = [
  {
    "type": "choice",
    "question": "¿En qué momento del año la Tierra se desplaza a su máxima velocidad orbital (~30,3 km/s)?",
    "options": [
      "En el Perihelio (principios de enero), cuando está en el punto más próximo al Sol (147,1 millones de km)",
      "En el Afelio (principios de julio), cuando está en el punto más alejado del Sol",
      "En los equinoccios de primavera y otoño",
      "La velocidad orbital de la Tierra es matemáticamente constante todos los días"
    ],
    "answer": 0,
    "explanation": "Por la Segunda Ley de Kepler, los planetas aumentan su velocidad cuanto más cerca están del foco gravitacional para barrer áreas iguales en tiempos iguales."
  },
  {
    "type": "choice",
    "question": "¿Qué forma geométrica tiene la órbita de la Tierra alrededor del Sol según la Primera Ley de Kepler?",
    "options": [
      "Una elipse de baja excentricidad con el Sol situado en uno de los dos focos",
      "Un círculo perfecto con el Sol en el centro geométrico absoluto",
      "Una espiral cónica que se acerca progresivamente al Sol",
      "Una trayectoria parabólica abierta"
    ],
    "answer": 0,
    "explanation": "Kepler demostró que las órbitas planetarias son elipses y que el Sol no ocupa el centro, sino uno de los focos orbitales."
  },
  {
    "type": "choice",
    "question": "Si la distancia media Tierra-Sol es 1 UA (~149,6 millones de km), ¿cuánto tarda un rayo de luz solar en llegar a la Tierra?",
    "options": [
      "8 minutos y 19 segundos (aproximadamente 499 segundos a 300.000 km/s)",
      "Ocurre de forma instantánea en 0 segundos",
      "24 horas exactas coincidiendo con el día solar",
      "365 días completos"
    ],
    "answer": 0,
    "explanation": "Dividiendo 149.600.000 km entre los 299.792 km/s de la velocidad de la luz se obtienen 499 segundos (~8 min 19 s).",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "choice",
    "question": "Según la Tercera Ley de Kepler ($P^2 = a^3$), ¿qué planeta del Sistema Solar se mueve a MENOR velocidad orbital?",
    "options": [
      "Neptuno (orbita a solo ~5,4 km/s por estar a 30 UA del Sol)",
      "Mercurio (el más veloz a ~47,4 km/s)",
      "La Tierra (a ~29,8 km/s)",
      "Marte (a ~24,1 km/s)"
    ],
    "answer": 0,
    "explanation": "A mayor distancia orbital ($a$), menor es la atracción gravitacional del Sol y menor es la velocidad orbital ($v$) requerida para mantenerse en equilibrio."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los hitos del viaje orbital de la Tierra empezando a principios de año:",
    "items": [
      "Perihelio de la Tierra (~3-4 de enero: mínima distancia y máxima velocidad orbital)",
      "Equinoccio de Primavera boreal (~20 de marzo: duración idéntica de día y noche)",
      "Solsticio de Verano boreal (~21 de junio: máxima altura del Sol en el cielo)",
      "Afelio de la Tierra (~4-5 de julio: máxima distancia y mínima velocidad orbital)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año en el norte)"
    ],
    "correctOrder": [
      "Perihelio de la Tierra (~3-4 de enero: mínima distancia y máxima velocidad orbital)",
      "Equinoccio de Primavera boreal (~20 de marzo: duración idéntica de día y noche)",
      "Solsticio de Verano boreal (~21 de junio: máxima altura del Sol en el cielo)",
      "Afelio de la Tierra (~4-5 de julio: máxima distancia y mínima velocidad orbital)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año en el norte)"
    ],
    "explanation": "El ciclo anual progresa desde el perihelio en enero pasando por equinoccios y solsticios hasta el afelio en julio y el cierre invernal."
  }
];
