// Autogenerated by GOALS Data Pipeline from 03_mars.md
import { Question } from '../../types';

export const test03_Mars: Question[] = [
  {
    "type": "choice",
    "question": "¿Por qué la superficie de Marte tiene su característico color rojizo?",
    "options": [
      "Por la abundancia de óxido de hierro (III) o hematita en su polvo superficial",
      "Por la combustión continua de gases volcánicos",
      "Por la radiación solar directa que quema las rocas",
      "Por la presencia de océanos de azufre líquido"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuál es el gas predominante en más del 95% de la atmósfera marciana?",
    "options": [
      "Dióxido de Carbono ($CO_2$)",
      "Oxígeno molecular ($O_2$)",
      "Nitrógeno ($N_2$)",
      "Helio ($He$)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si una astronauta tiene una masa de 60 kg en la Tierra, ¿cuál es su masa y peso aproximado en Marte (g = 3,72 m/s²)?",
    "options": [
      "Su masa sigue siendo 60 kg invariable y su peso es ~223 Newtons",
      "Su masa se reduce a 22 kg y su peso a 0 Newtons",
      "Su masa aumenta a 120 kg",
      "La masa y el peso son siempre cero en el espacio"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes relieves geológicos según su altitud o longitud de MENOR a MAYOR:",
    "items": [
      "Monte Everest en la Tierra (~8,8 km de altitud)",
      "Monte Olimpo en Marte (~21,9 km de altitud)",
      "Gran Cañón del Colorado en la Tierra (~446 km de longitud)",
      "Valles Marineris en Marte (~4.000 km de longitud)"
    ],
    "correctOrder": [
      "Monte Everest en la Tierra (~8,8 km de altitud)",
      "Monte Olimpo en Marte (~21,9 km de altitud)",
      "Gran Cañón del Colorado en la Tierra (~446 km de longitud)",
      "Valles Marineris en Marte (~4.000 km de longitud)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
