// Autogenerated by GOALS Data Pipeline from 11_la_red_cosmica_laniakea_y_el_gran_atractor.md
import { Question } from '../../types';

export const test11_La_red_cosmica_laniakea_y_el_gran_atractor: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué es el Supercúmulo Laniakea y qué tamaño aproximado tiene?",
    "options": [
      "Nuestro supercúmulo de galaxias de unos 520 millones de años luz que engloba más de 100.000 galaxias",
      "Una galaxia espiral cercana a la Vía Láctea",
      "Un agujero negro en el centro de la Vía Láctea",
      "Un planeta extrasolar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cómo se llama el centro de atracción gravitacional hacia el que se desplazan todas las galaxias de Laniakea a más de 600 km/s?",
    "options": [
      "El Gran Atractor",
      "El Horizonte de Sucesos",
      "El Punto Subsolar",
      "La Estrella Polar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes estructuras cósmicas desde la MÁS PEQUEÑA hasta la MÁS GRANDE:",
    "items": [
      "Grupo Local (10 millones al)",
      "Cúmulo de Virgo (54 millones al)",
      "Supercúmulo Laniakea (520 millones al)",
      "Universo Observable (93.000 millones al)"
    ],
    "correctOrder": [
      "Grupo Local (10 millones al)",
      "Cúmulo de Virgo (54 millones al)",
      "Supercúmulo Laniakea (520 millones al)",
      "Universo Observable (93.000 millones al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué se asemeja la distribución de la materia en el cosmos a escalas de cientos de millones de años luz?",
    "options": [
      "A una esponja de filamentos y telarañas que rodean inmensos vacíos cósmicos",
      "A esferas sólidas concéntricas perfectas",
      "A una línea recta uniforme sin variaciones",
      "A un disco plano bidimensional"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
