// Autogenerated by GOALS Data Pipeline from 07_la_nube_de_oort_y_la_sonda_interestelar_voyager_1.md
import { Question } from '../../types';

export const test07_La_nube_de_oort_y_la_sonda_interestelar_voyager_1: Question[] = [
  {
    "type": "choice",
    "question": "¿Cómo se llama la frontera magnética donde el viento solar choca contra el medio interestelar?",
    "options": [
      "Heliopausa",
      "Línea de Kármán",
      "Cinturón de Kuiper",
      "Horizonte de Sucesos"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Hasta qué distancia aproximada del Sol se extiende la Nube de Oort esférica?",
    "options": [
      "Hasta unas 100.000 UA (~1,5 años luz)",
      "Hasta 30 UA",
      "Hasta 400 kilómetros",
      "Hasta 100 millones de años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes regiones del Sistema Solar desde el Sol hacia el exterior:",
    "items": [
      "Cinturón de Asteroides (2,8 UA)",
      "Cinturón de Kuiper (30 - 55 UA)",
      "Heliopausa (~120 UA)",
      "Nube de Oort Exterior (100.000 UA)"
    ],
    "correctOrder": [
      "Cinturón de Asteroides (2,8 UA)",
      "Cinturón de Kuiper (30 - 55 UA)",
      "Heliopausa (~120 UA)",
      "Nube de Oort Exterior (100.000 UA)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué hito histórico alcanzará la sonda espacial Voyager 1 a finales de 2026?",
    "options": [
      "Situarse a 1 día-luz de distancia de la Tierra (la señal tardará 24 horas)",
      "Regresar a la Tierra tras completar su viaje",
      "Entrar en órbita alrededor de Alfa Centauri",
      "Aterrizar en la superficie de Plutón"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
