// Autogenerated by GOALS Data Pipeline from 01_earth.md
import { Question } from '../../types';

export const test01_Earth: Question[] = [
  {
    "type": "choice",
    "question": "¿Por qué los astronautas flotan dentro de la Estación Espacial Internacional (ISS) a 418 km de altitud?",
    "options": [
      "Porque la ISS y los astronautas están en caída libre continua alrededor de la Tierra a ~27.600 km/h",
      "Porque a 418 km de altura la gravedad de la Tierra desaparece por completo (g = 0)",
      "Porque unos propulsores magnéticos empujan a los astronautas hacia el techo",
      "Porque la falta de aire anula todas las fuerzas del universo"
    ],
    "answer": 0,
    "explanation": "A 418 km de altitud, la gravedad terrestre conserva casi el 90% de su fuerza. La ingravidez se produce porque la estación cae hacia la Tierra a la misma velocidad que la superficie se curva."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la composición química dominante de la atmósfera terrestre?",
    "options": [
      "78% Nitrógeno (N2) y 21% Oxígeno (O2)",
      "50% Oxígeno y 50% Dióxido de Carbono",
      "90% Hidrógeno y 10% Helio",
      "95% Dióxido de Carbono como en Marte"
    ],
    "answer": 0,
    "explanation": "La atmósfera terrestre es una mezcla única rica en nitrógeno molecular (78%) y oxígeno libre (21%), con un 1% de argón y gases traza."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra opera el Telescopio Espacial James Webb (JWST)?",
    "options": [
      "A 1,5 millones de kilómetros (en el punto de equilibrio gravitacional Lagrange L2)",
      "A 100 km sobre el nivel del mar en la Línea de Kármán",
      "En la superficie de la Luna a 384.400 km",
      "A 1 año luz de distancia en el espacio interestelar"
    ],
    "answer": 0,
    "explanation": "El JWST orbita el punto Lagrange L2 a 1,5 millones de kilómetros, donde las fuerzas gravitatorias del Sol y la Tierra se equilibran para mantenerlo sincronizado con nuestro planeta.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Por qué el telescopio Hubble obtiene imágenes mucho más nítidas que los telescopios terrestres?",
    "options": [
      "Porque a 535 km de altitud no sufre la turbulencia ni la absorción de luz de la atmósfera terrestre",
      "Porque utiliza lentes mágicas que no existen en la superficie",
      "Porque está 1.000 veces más cerca de las estrellas lejanas",
      "Porque en el espacio la luz viaja al doble de velocidad"
    ],
    "answer": 0,
    "explanation": "La turbulencia atmosférica hace que la luz titile y se distorsione. Al estar en el vacío orbital a 535 km, el Hubble capta frentes de onda de luz prístinos."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes altitudes desde la superficie terrestre hacia el espacio profundo:",
    "items": [
      "Línea de Kármán (100 km - Frontera oficial del espacio)",
      "Estación Espacial Internacional / ISS (418 km - Órbita baja)",
      "Telescopio Espacial Hubble (535 km - Órbita baja limpia)",
      "Satélite de Observación Landsat 9 (705 km - Órbita heliosíncrona)",
      "Telescopio Espacial James Webb (1.500.000 km - Punto Lagrange L2)"
    ],
    "correctOrder": [
      "Línea de Kármán (100 km - Frontera oficial del espacio)",
      "Estación Espacial Internacional / ISS (418 km - Órbita baja)",
      "Telescopio Espacial Hubble (535 km - Órbita baja limpia)",
      "Satélite de Observación Landsat 9 (705 km - Órbita heliosíncrona)",
      "Telescopio Espacial James Webb (1.500.000 km - Punto Lagrange L2)"
    ],
    "explanation": "La escala orbital humana progresa desde la atmósfera superior (100 km) y la órbita baja tripulada (ISS y Hubble) hasta satélites de recursos terrestres y observatorios en L2."
  }
];
