// Autogenerated by GOALS Data Pipeline from 10_el_grupo_local_de_galaxias_y_andromeda_m31.md
import { Question } from '../../types';

export const test10_El_grupo_local_de_galaxias_y_andromeda_m31: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuáles son las dos galaxias más grandes que dominan el Grupo Local?",
    "options": [
      "La Galaxia de Andrómeda (M31) y la Vía Láctea",
      "La Vía Láctea y la Galaxia del Triángulo",
      "Andrómeda y la Gran Nube de Magallanes",
      "Centaurus A y M87"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra se encuentra la Galaxia de Andrómeda (M31)?",
    "options": [
      "A unos 2,5 millones de años luz",
      "A 4,24 años luz",
      "A 100.000 años luz",
      "A 150 millones de kilómetros"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes galaxias de nuestro entorno desde la MÁS CERCANA a la Tierra hasta la MÁS LEJANA:",
    "items": [
      "Gran Nube de Magallanes (163.000 al)",
      "Galaxia de Andrómeda M31 (2,5 millones al)",
      "Galaxia del Triángulo M33 (2,7 millones al)",
      "Galaxia del Remolino M51 (23 millones al)"
    ],
    "correctOrder": [
      "Gran Nube de Magallanes (163.000 al)",
      "Galaxia de Andrómeda M31 (2,5 millones al)",
      "Galaxia del Triángulo M33 (2,7 millones al)",
      "Galaxia del Remolino M51 (23 millones al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué ocurrirá dentro de unos 4.500 millones de años entre la Vía Láctea y la Galaxia de Andrómeda?",
    "options": [
      "Colisionarán y se fusionarán formando una galaxia elíptica gigante (Milkomeda)",
      "Se alejarán para siempre debido a la energía oscura",
      "Andrómeda devorará a la Vía Láctea sin dejar rastro",
      "Explotarán destruyendo todas las estrellas"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
