// Autogenerated by GOALS Data Pipeline from 10_localgroup.md
import { Question } from '../../types';

export const test10_Localgroup: Question[] = [
  {
    "type": "choice",
    "question": "¿Por qué la Galaxia de Andrómeda se precipita hacia la Vía Láctea a 110 km/s a pesar de la expansión general del universo?",
    "options": [
      "Porque la atracción gravitatoria mutua y la masa de sus halos de materia oscura superan a la expansión cósmica a distancias locales cortas",
      "Porque la Tierra emite un campo magnético atractor",
      "Porque el agujero negro de Andrómeda succiona a toda la galaxia",
      "Porque el viento solar empuja a Andrómeda"
    ],
    "answer": 0,
    "explanation": "A escalas inferiores a ~10 millones de años luz, la gravedad local vence a la expansión de Hubble, provocando que los miembros del Grupo Local se atraigan mutuamente."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de nuestro Sistema Solar se encuentra la Galaxia de Andrómeda (M31)?",
    "options": [
      "A 2,537 millones de años luz (el objeto visible a simple vista más lejano)",
      "A 100.000 años luz",
      "A 8 minutos luz como el Sol",
      "A 100.000 millones de años luz"
    ],
    "answer": 0,
    "explanation": "Andrómeda se sitúa a unos 2,5 millones de años luz, por lo que la luz que vemos de ella partió cuando los primeros homínidos (Australopithecus) caminaban por la Tierra."
  },
  {
    "type": "choice",
    "question": "¿Chocarán físicamente las estrellas del Sol y de Andrómeda cuando ambas galaxias se fusionen en Milkomeda dentro de 4.500 millones de años?",
    "options": [
      "Prácticamente ninguna estrella chocará directamente, debido a las inmensas distancias de vacío que las separan",
      "Sí, todas las estrellas chocarán y explotarán como supernovas",
      "La Tierra se evaporará al instante en el primer segundo",
      "Ambas galaxias rebotarán como pelotas de goma"
    ],
    "answer": 0,
    "explanation": "Las galaxias son en su inmensa mayoría espacio vacío; las órbitas de las estrellas se reorganizarán gravitacionalmente pero las colisiones directas entre astros serán casi nulas.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Cuál es la galaxia satélite más cercana y prominente que orbita alrededor de la Vía Láctea?",
    "options": [
      "La Gran Nube de Magallanes (a unos 163.000 años luz)",
      "La Galaxia del Triángulo M33",
      "La Galaxia del Sombrero",
      "El cúmulo de Virgo"
    ],
    "answer": 0,
    "explanation": "La Gran Nube de Magallanes es una galaxia satélite enana que acompaña a la Vía Láctea a una distancia de tan solo 163.000 años luz."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes componentes del Grupo Local desde el más cercano a la Tierra hasta el borde exterior:",
    "items": [
      "Gran Nube de Magallanes (163.000 al - Satélite enana austral)",
      "Pequeña Nube de Magallanes (200.000 al)",
      "Galaxia de Andrómeda M31 (2,537 Millones al - Espiral gigante)",
      "Galaxia del Triángulo M33 (2,73 Millones al)",
      "Límite gravitacional exterior del Grupo Local (~10 Millones al)"
    ],
    "correctOrder": [
      "Gran Nube de Magallanes (163.000 al - Satélite enana austral)",
      "Pequeña Nube de Magallanes (200.000 al)",
      "Galaxia de Andrómeda M31 (2,537 Millones al - Espiral gigante)",
      "Galaxia del Triángulo M33 (2,73 Millones al)",
      "Límite gravitacional exterior del Grupo Local (~10 Millones al)"
    ],
    "explanation": "La escala del Grupo Local se extiende desde las galaxias satélites inmediatas hasta las grandes espirales de Andrómeda y Triángulo en su límite de 10 millones de años luz."
  }
];
