// Autogenerated by GOALS Data Pipeline from 12_universe.md
import { Question } from '../../types';

export const test12_Universe: Question[] = [
  {
    "type": "choice",
    "question": "Si el Universo tiene 13.800 millones de años, ¿por qué el diámetro del Universo Observable mide 93.000 millones de años luz?",
    "options": [
      "Porque el tejido del espacio-tiempo se ha expandido continuamente mientras los fotones de luz viajaban hacia nosotros",
      "Porque la luz se mueve al doble de velocidad en el espacio profundo",
      "Porque los espejos de los telescopios multiplican ópticamente las distancias",
      "Porque existen universos paralelos reflejados en el cielo"
    ],
    "answer": 0,
    "explanation": "El espacio no es estático; se ha expandido de forma acumulativa durante los 13.800 millones de años de viaje de la luz, situando a los emisores originales a una distancia comóvil actual de 46.500 millones de años luz de radio (93.000 millones de al de diámetro)."
  },
  {
    "type": "choice",
    "question": "¿Qué es el Fondo Cósmico de Microondas (CMB) en la astrofísica moderna?",
    "options": [
      "La radiación térmica fósil liberada 380.000 años tras el Big Bang cuando el plasma se enfrió a 3.000 K y el universo se volvió transparente",
      "El calor emitido por las chimeneas volcánicas de los exoplanetas",
      "La luz reflejada por los anillos de Saturno",
      "La red de señales de telecomunicaciones de la Tierra"
    ],
    "answer": 0,
    "explanation": "El CMB es el remanente térmico de la Recombinación, cuando los fotones se desacoplaron de la materia, viajando libremente por el cosmos hasta hoy.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué fracción aproximada del contenido de masa-energía del universo compone la materia ordinaria (átomos, estrellas y seres vivos)?",
    "options": [
      "Solo alrededor de un 4,9% (el 95,1% restante es Energía Oscura y Materia Oscura)",
      "El 100% de todo el cosmos",
      "El 50% exacto",
      "Menos del 0,00001%"
    ],
    "answer": 0,
    "explanation": "El modelo cosmológico estándar Lambda-CDM establece que la materia bariónica visible representa solo el 4,9% del pastel cósmico total."
  },
  {
    "type": "choice",
    "question": "¿Qué propiedad física describe a la Energía Oscura en el modelo cosmológico?",
    "options": [
      "Una energía intrínseca del vacío con presión negativa que impulsa la expansión acelerada del espacio",
      "Un tipo de gasolina espacial que arde en las estrellas",
      "Agujeros negros que absorben galaxias enteras",
      "La sombra que proyecta la Luna sobre la Tierra"
    ],
    "answer": 0,
    "explanation": "Descubierta en 1998 a través de supernovas tipo Ia, la energía oscura representa el 68,3% del universo y acelera la tasa de expansión cósmica."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente las grandes eras de la historia de nuestro Universo desde el origen:",
    "items": [
      "Big Bang e Inflación Cósmica Cuántica (t = 0 a 10^-32 segundos)",
      "Recombinación y emisión de la luz del Fondo Cósmico CMB (t = 380.000 años)",
      "Amanecer Cósmico y nacimiento de las primeras estrellas gigantes (t ~ 200 a 300 Millones de años)",
      "Formación del Sistema Solar y el planeta Tierra (t = 9.200 Millones de años tras el Big Bang)",
      "Era actual dominada por la expansión acelerada de la Energía Oscura (t = 13.800 Millones de años)"
    ],
    "correctOrder": [
      "Big Bang e Inflación Cósmica Cuántica (t = 0 a 10^-32 segundos)",
      "Recombinación y emisión de la luz del Fondo Cósmico CMB (t = 380.000 años)",
      "Amanecer Cósmico y nacimiento de las primeras estrellas gigantes (t ~ 200 a 300 Millones de años)",
      "Formación del Sistema Solar y el planeta Tierra (t = 9.200 Millones de años tras el Big Bang)",
      "Era actual dominada por la expansión acelerada de la Energía Oscura (t = 13.800 Millones de años)"
    ],
    "explanation": "La cosmología progresa ordenadamente desde la singularidad inicial y la sopa primordial hasta la formación de galaxias, el nacimiento del Sol y la era actual."
  }
];
