// Autogenerated by GOALS Data Pipeline from 11_laniakea.md
import { Question } from '../../types';

export const test11_Laniakea: Question[] = [
  {
    "type": "choice",
    "question": "¿Cómo definieron los astrofísicos la frontera exacta de nuestro supercúmulo Laniakea?",
    "options": [
      "Como una cuenca gravitacional delimitada por la línea donde las galaxias dejan de fluir hacia el Gran Atractor y caen hacia otro supercúmulo vecino",
      "Como un muro de estrellas gigantes visible en el telescopio",
      "Como la frontera donde la gravedad deja de existir en el universo",
      "Como la distancia máxima a la que puede viajar una sonda espacial"
    ],
    "answer": 0,
    "explanation": "Laniakea se define por la dinámica de velocidades peculiares: es el volumen del espacio donde todas las corrientes de galaxias convergen hacia el mismo centro de atracción."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad aproximada se desplaza la Vía Láctea a través del cosmos hacia el Gran Atractor?",
    "options": [
      "A más de 2,2 millones de km/h (unos ~627 km/s respecto a la radiación de fondo CMB)",
      "A 100 km/h como un automóvil",
      "A 300.000 km/s a la velocidad de la luz",
      "La Vía Láctea permanece completamente inmóvil en el espacio absoluto"
    ],
    "answer": 0,
    "explanation": "El análisis del dipolo de la radiación cósmica de fondo de microondas (CMB) demuestra que nuestro grupo galáctico viaja a ~627 km/s arrastrado por el Gran Atractor y Shapley."
  },
  {
    "type": "choice",
    "question": "¿Qué representan los gigantescos \"Vacíos Cósmicos\" (Cosmic Voids) en la telaraña del universo?",
    "options": [
      "Inmensos desiertos espaciales de hasta 150 millones de años luz de diámetro donde la densidad de galaxias y gas es prácticamente nula",
      "Agujeros negros que se han tragado a todas las estrellas",
      "Zonas donde las leyes de la física se apagan",
      "Nubes de gas inflamable"
    ],
    "answer": 0,
    "explanation": "Los vacíos cósmicos son regiones expansivas de muy baja densidad que empujan la materia hacia los filamentos y paredes de la red cósmica.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué significa el término \"Laniakea\" asignado por los astrónomos hawaianos en 2014?",
    "options": [
      "\"Cielos Inmensos\" o \"Horizonte Celestial Infinito\"",
      "\"Estrella Solitaria\"",
      "\"Remolino de Fuego\"",
      "\"Río Helado\""
    ],
    "answer": 0,
    "explanation": "En idioma hawaiano, *Lani* significa \"cielo\" y *Akea* significa \"inmenso\" o \"ilimitado\", en homenaje a los navegantes polinesios que guiaban sus canoas por las estrellas."
  },
  {
    "type": "order",
    "question": "Ordena la jerarquía de estructuras del cosmos de MENOR a MAYOR escala espacial:",
    "items": [
      "Sistema Solar (~60 UA - Nuestro vecindario planetario)",
      "La Vía Láctea (~100.000 años luz - Nuestra galaxia espiral)",
      "Grupo Local de Galaxias (~10 millones de años luz - Familia de 80 galaxias)",
      "Supercúmulo Laniakea (~520 millones de años luz - 100.000 galaxias)",
      "Universo Observable (~93.000 millones de años luz)"
    ],
    "correctOrder": [
      "Sistema Solar (~60 UA - Nuestro vecindario planetario)",
      "La Vía Láctea (~100.000 años luz - Nuestra galaxia espiral)",
      "Grupo Local de Galaxias (~10 millones de años luz - Familia de 80 galaxias)",
      "Supercúmulo Laniakea (~520 millones de años luz - 100.000 galaxias)",
      "Universo Observable (~93.000 millones de años luz)"
    ],
    "explanation": "La escalera cósmica se estructura jerárquicamente desde nuestro sistema planetario hasta el supercontinente Laniakea y el horizonte observable."
  }
];
