// Autogenerated by GOALS Data Pipeline from 09_milkyway.md
import { Question } from '../../types';

export const test09_Milkyway: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué hallazgo astrofísico demostró que la Vía Láctea está envuelta en un masivo halo de Materia Oscura?",
    "options": [
      "Que las estrellas del borde exterior de la galaxia giran a la misma velocidad (~220 km/s) que las interiores en vez de desacelerarse",
      "Que el centro de la galaxia carece por completo de gas",
      "Que las estrellas del núcleo galáctico son más frías que el Sol",
      "Que la Vía Láctea no tiene brazos espirales"
    ],
    "answer": 0,
    "explanation": "Según la gravedad newtoniana simple, las estrellas periféricas deberían girar mucho más lento; la curva de rotación plana descubierta por Vera Rubin demostró la existencia del halo invisible de materia oscura."
  },
  {
    "type": "choice",
    "question": "¿Cuánto tiempo tarda nuestro Sistema Solar en dar una vuelta completa alrededor del centro galáctico (Año Cósmico)?",
    "options": [
      "Aproximadamente 230 millones de años terrestres (viajando a ~828.000 km/h)",
      "365 días bisiestos",
      "10.000 años",
      "1 millón de años"
    ],
    "answer": 0,
    "explanation": "A una distancia de 26.000 años luz del núcleo galáctico, el Sol tarda unos 230 millones de años en completar una revolución orbital en la Vía Láctea."
  },
  {
    "type": "choice",
    "question": "¿Qué masa posee el agujero negro supermasivo Sagitario A* situado en el núcleo de nuestra galaxia?",
    "options": [
      "Aproximadamente 4,15 millones de masas solares ($M_\\odot$)",
      "La masa de un grano de polvo cósmico",
      "Exactamente la masa del planeta Tierra",
      "100 masas solares"
    ],
    "answer": 0,
    "explanation": "El seguimiento orbital de estrellas ultrarrápidas como S2 durante más de dos décadas (Premio Nobel de Física 2020) permitió determinar con precisión su masa de 4,15 millones de soles.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué son en realidad los brazos espirales de la Vía Láctea?",
    "options": [
      "Ondas de densidad de compresión donde el gas se condensa y nacen nuevas generaciones de estrellas",
      "Estructuras sólidas de roca que giran rígidamente",
      "Rayos láser emitidos por el agujero negro central",
      "Ríos de agua líquida flotando en el espacio"
    ],
    "answer": 0,
    "explanation": "Los brazos espirales son ondas de densidad a través de las cuales viajan las estrellas, funcionando como viveros donde el gas se comprime y forma cúmulos estelares."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes regiones anatómicas de la Vía Láctea desde el centro hacia los confines exteriores:",
    "items": [
      "Horizonte de Sucesos de Sagitario A* (Radio de Schwarzschild de ~12M km)",
      "Bulbo Galáctico central (Enjambre denso de estrellas viejas)",
      "Disco estelar y Brazo de Orión (Ubicación del Sistema Solar a 26.000 al)",
      "Disco gaseoso exterior (Límite óptico a 50.000 al del centro)",
      "Halo esférico de Materia Oscura y Cúmulos Globulares (Se extiende hasta 300.000 al)"
    ],
    "correctOrder": [
      "Horizonte de Sucesos de Sagitario A* (Radio de Schwarzschild de ~12M km)",
      "Bulbo Galáctico central (Enjambre denso de estrellas viejas)",
      "Disco estelar y Brazo de Orión (Ubicación del Sistema Solar a 26.000 al)",
      "Disco gaseoso exterior (Límite óptico a 50.000 al del centro)",
      "Halo esférico de Materia Oscura y Cúmulos Globulares (Se extiende hasta 300.000 al)"
    ],
    "explanation": "La estructura galáctica progresa desde la singularidad central y el bulbo pasando por el disco espiral hasta el inmenso halo de materia oscura exterior."
  }
];
