// Autogenerated by GOALS Data Pipeline from 12_el_universo_observable_el_cmb_y_los_origenes_cosmicos.md
import { Question } from '../../types';

export const test12_El_universo_observable_el_cmb_y_los_origenes_cosmicos: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué diámetro aproximado tiene la esfera del Universo Observable centrada en nosotros?",
    "options": [
      "93.000 millones de años luz",
      "13.800 millones de kilómetros",
      "100.000 años luz",
      "4,24 años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué porcentaje de todo el contenido del Universo corresponde a materia ordinaria (átomos, estrellas, planetas, personas)?",
    "options": [
      "Apenas un ~4,9% (el 95% restante es materia y energía oscura)",
      "El 50%",
      "El 85%",
      "El 100%"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los siguientes hitos de la historia cósmica desde el origen:",
    "items": [
      "Big Bang e Inflación Cósmica (t = 0)",
      "Emisión del Fondo Cósmico de Microondas (t = 380.000 años)",
      "Nacimiento de las Primeras Galaxias (t = 400 millones de años)",
      "Formación del Sistema Solar y la Tierra (t = 9.200 millones de años)"
    ],
    "correctOrder": [
      "Big Bang e Inflación Cósmica (t = 0)",
      "Emisión del Fondo Cósmico de Microondas (t = 380.000 años)",
      "Nacimiento de las Primeras Galaxias (t = 400 millones de años)",
      "Formación del Sistema Solar y la Tierra (t = 9.200 millones de años)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué es el Fondo Cósmico de Microondas (CMB)?",
    "options": [
      "El remanente térmico fósil emitido 380.000 años después del Big Bang enfriado a 2,725 K",
      "El sonido producido por la colisión de agujeros negros",
      "La luz reflejada por los asteroides del Sistema Solar",
      "El viento solar emitido por la corona solar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
