// Autogenerated by GOALS Data Pipeline from 02_eclipses.md
import { Question } from '../../types';

export const test02_Eclipses: Question[] = [
  {
    "type": "choice",
    "question": "¿Por qué no ocurre un eclipse total de Sol en cada fase de Luna Nueva?",
    "options": [
      "Porque la órbita de la Luna está inclinada 5,14° respecto a la eclíptica y su sombra suele pasar por encima o por debajo de la Tierra",
      "Porque la Luna solo proyecta sombra hacia el espacio una vez cada siglo",
      "Porque la atmósfera terrestre desvía la luz solar impidiendo la formación de sombras",
      "Porque el Sol se apaga durante la noche"
    ],
    "answer": 0,
    "explanation": "La inclinación de 5,14° de la órbita lunar hace que el Sol, la Luna y la Tierra solo se alineen en línea recta perfecta cuando la Luna cruza los puntos nodales."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la coincidencia geométrica que permite que la Luna tape al Sol de forma exacta?",
    "options": [
      "El Sol es 400 veces mayor en diámetro que la Luna pero está 400 veces más lejos, teniendo ambos ~0,5° de tamaño aparente",
      "La Luna y el Sol tienen exactamente el mismo tamaño físico en kilómetros",
      "La Tierra atrae a la Luna con el doble de fuerza gravitacional en verano",
      "La Luna se hincha al entrar en la sombra terrestre"
    ],
    "answer": 0,
    "explanation": "Ambos objetos subtienden un ángulo visual de aproximadamente medio grado (30 minutos de arco) en la bóveda celeste."
  },
  {
    "type": "choice",
    "question": "¿Qué fenómeno óptico ocurre en el borde lunar justo antes y después de la totalidad?",
    "options": [
      "Las Perlas de Baily y el Anillo de Diamantes, provocados por los rayos solares atravesando los valles y cráteres lunares",
      "La formación de un arcoíris lunar permanente",
      "La emisión de rayos gamma concentrados",
      "El cambio de color del mar de azul a verde"
    ],
    "answer": 0,
    "explanation": "El relieve escarpado de la Luna deja pasar los últimos rayos de luz a través de sus valles montañosos, creando destellos como perlas brillantes (Perlas de Baily).",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿En qué zona de la sombra lunar debe estar un observador para presenciar un eclipse solar 100% total?",
    "options": [
      "En el interior del cono de la Umbra",
      "En la Penumbra exterior",
      "En la estratosfera por encima de las nubes",
      "En el lado nocturno de la Tierra"
    ],
    "answer": 0,
    "explanation": "La Umbra es la región cónica donde la Luna cubre por completo el disco solar; en la Penumbra solo se ve un eclipse parcial."
  },
  {
    "type": "order",
    "question": "Ordena la secuencia cronológica de eventos durante un eclipse solar total:",
    "items": [
      "Primer Contacto C1 (La Luna comienza a morder el disco solar en fase parcial)",
      "Descenso de temperatura y cambio en la iluminación ambiental",
      "Perlas de Baily y destello del Anillo de Diamantes",
      "Segundo Contacto C2 y Totalidad (Aparición de la Corona Solar y estrellas)",
      "Cuarto Contacto C4 (La Luna abandona totalmente el disco del Sol)"
    ],
    "correctOrder": [
      "Primer Contacto C1 (La Luna comienza a morder el disco solar en fase parcial)",
      "Descenso de temperatura y cambio en la iluminación ambiental",
      "Perlas de Baily y destello del Anillo de Diamantes",
      "Segundo Contacto C2 y Totalidad (Aparición de la Corona Solar y estrellas)",
      "Cuarto Contacto C4 (La Luna abandona totalmente el disco del Sol)"
    ],
    "explanation": "El eclipse evoluciona desde el primer contacto visual hasta el clímax de la totalidad con la corona solar visible, finalizando en el cuarto contacto."
  }
];
