// Autogenerated by GOALS Data Pipeline from 01_la_tierra_su_atmosfera_y_satelites.md
import { Question } from '../../types';

export const test01_La_tierra_su_atmosfera_y_satelites: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuáles son los dos gases principales que componen más del 99% de la atmósfera terrestre?",
    "options": [
      "Nitrógeno (78%) y Oxígeno (21%)",
      "Dióxido de Carbono (80%) y Metano (19%)",
      "Hidrógeno (75%) y Helio (24%)",
      "Oxígeno (50%) y Vapor de Agua (50%)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad aproximada viaja la Estación Espacial Internacional (ISS) en órbita baja?",
    "options": [
      "~27.600 km/h (da una vuelta cada 92 minutos)",
      "~1.000 km/h (como un avión comercial)",
      "~100.000 km/h (velocidad de la luz)",
      "100 km/h (como un automóvil)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena estos artefactos y cuerpos desde el MÁS CERCANO a la Tierra hasta el MÁS LEJANO:",
    "items": [
      "Estación Espacial ISS (418 km)",
      "Telescopio Hubble (535 km)",
      "La Luna (384.400 km)",
      "Telescopio James Webb en L2 (1.500.000 km)"
    ],
    "correctOrder": [
      "Estación Espacial ISS (418 km)",
      "Telescopio Hubble (535 km)",
      "La Luna (384.400 km)",
      "Telescopio James Webb en L2 (1.500.000 km)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra opera el Telescopio James Webb en el Punto de Lagrange L2?",
    "options": [
      "1,5 millones de kilómetros",
      "400 kilómetros",
      "384.400 kilómetros",
      "150 millones de kilómetros"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
