// Autogenerated by GOALS Data Pipeline from 02_eclipses_y_el_gran_eclipse_solar_2026_en_espana.md
import { Question } from '../../types';

export const test02_Eclipses_y_el_gran_eclipse_solar_2026_en_espana: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué condición orbital indispensable debe cumplirse para que ocurra un eclipse solar?",
    "options": [
      "Luna Nueva situada en uno de los nodos orbitales",
      "Luna Llena situada en el punto más alejado de la Tierra",
      "Cualquier Luna Nueva sin importar la inclinación",
      "Alineación de la Tierra entre el Sol y la Luna"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuánto mide la inclinación de la órbita de la Luna respecto al plano orbital terrestre (eclíptica)?",
    "options": [
      "5,14 grados",
      "23,44 grados",
      "0 grados (son totalmente coplanares)",
      "90 grados"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los fenómenos visibles en un eclipse solar total:",
    "items": [
      "Fase Parcial (Penumbra)",
      "Perlas de Baily",
      "Anillo de Diamantes",
      "Totalidad (Corona Solar visible)"
    ],
    "correctOrder": [
      "Fase Parcial (Penumbra)",
      "Perlas de Baily",
      "Anillo de Diamantes",
      "Totalidad (Corona Solar visible)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuándo fue el último eclipse solar total que cruzó la España peninsular antes del 12 de agosto de 2026?",
    "options": [
      "30 de agosto de 1905 (hace más de 120 años)",
      "11 de julio de 1991",
      "20 de marzo de 2015",
      "Nunca antes en la historia"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
