// Autogenerated by GOALS Data Pipeline from 03_rotation.md
import { Question } from '../../types';

export const test03_Rotation: Question[] = [
  {
    "type": "choice",
    "question": "Si la Tierra realiza un giro de 360° en 23 horas y 56 minutos (día sidéreo), ¿por qué nuestro día cotidiano dura 24 horas?",
    "options": [
      "Porque al avanzar en su órbita alrededor del Sol debe rotar ~1° adicional (~4 minutos) para volver a encarar al Sol en el mediodía",
      "Porque la fricción del aire frena el planeta exactamente 4 minutos al día",
      "Porque los relojes atómicos internacionales se adelantan artificialmente",
      "Porque el eje de rotación de la Tierra se invierte cada noche"
    ],
    "answer": 0,
    "explanation": "El avance de la Tierra a lo largo de su órbita hace que la dirección hacia el Sol cambie en ~1° diario, requiriendo 4 minutos extra de giro para alinear de nuevo el mediodía solar."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad tangencial aproximada se mueve la superficie de la Tierra en la línea del ecuador?",
    "options": [
      "A unos 1.670 km/h (464 m/s)",
      "A 100 km/h como un coche en autopista",
      "A 300.000 km/s a la velocidad de la luz",
      "Está inmóvil sin rotación"
    ],
    "answer": 0,
    "explanation": "Dividiendo los 40.075 km de circunferencia ecuatorial entre las 24 horas del día se obtiene una velocidad superficial de aproximadamente 1.670 km/h."
  },
  {
    "type": "choice",
    "question": "¿Cuántos grados de longitud geográfica abarca cada uno de los 24 husos horarios del mundo?",
    "options": [
      "15° de longitud ($360^\\circ / 24\\text{ h}$)",
      "90° de longitud",
      "1° de longitud",
      "45° de longitud"
    ],
    "answer": 0,
    "explanation": "La esfera terrestre de 360° dividida equitativamente entre las 24 horas del día da como resultado exactamente 15° de longitud por cada franja horaria."
  },
  {
    "type": "choice",
    "question": "¿En qué sentido giran los huracanes en el Hemisferio Norte debido al Efecto Coriolis?",
    "options": [
      "En sentido antihorario (contrario a las agujas del reloj) por la desviación hacia la derecha",
      "En sentido horario (a favor de las agujas del reloj)",
      "En línea recta sin formar espirales",
      "De abajo hacia arriba verticalmente"
    ],
    "answer": 0,
    "explanation": "La rotación terrestre desvía el aire hacia la derecha en el Hemisferio Norte, haciendo que el flujo hacia el centro de bajas presiones adquiera giro antihorario.",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "order",
    "question": "Ordena la progresión de la iluminación durante la puesta de Sol hasta la noche cósmica:",
    "items": [
      "Puesta de Sol aparente (El disco solar cruza el horizonte geométrico a 0°)",
      "Crepúsculo Civil (El Sol se sitúa entre 0° y 6° bajo el horizonte)",
      "Crepúsculo Náutico (El Sol se sitúa entre 6° y 12° bajo el horizonte)",
      "Crepúsculo Astronómico (El Sol se sitúa entre 12° y 18° bajo el horizonte)",
      "Noche Cósmica Cerrada (El Sol desciende a más de 18° bajo el horizonte)"
    ],
    "correctOrder": [
      "Puesta de Sol aparente (El disco solar cruza el horizonte geométrico a 0°)",
      "Crepúsculo Civil (El Sol se sitúa entre 0° y 6° bajo el horizonte)",
      "Crepúsculo Náutico (El Sol se sitúa entre 6° y 12° bajo el horizonte)",
      "Crepúsculo Astronómico (El Sol se sitúa entre 12° y 18° bajo el horizonte)",
      "Noche Cósmica Cerrada (El Sol desciende a más de 18° bajo el horizonte)"
    ],
    "explanation": "El crepúsculo se divide astronómicamente según el ángulo del Sol bajo el horizonte, pasando por civil, náutico y astronómico antes de la oscuridad total."
  }
];
