// Autogenerated by GOALS Data Pipeline from 06_el_sistema_solar_los_8_planetas_y_asteroides.md
import { Question } from '../../types';

export const test06_El_sistema_solar_los_8_planetas_y_asteroides: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué porcentaje de toda la masa del Sistema Solar concentra el Sol en su interior?",
    "options": [
      "El 99,86%",
      "El 50%",
      "El 80%",
      "El 10%"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena los 8 planetas del Sistema Solar por su distancia creciente desde el Sol:",
    "items": [
      "Mercurio",
      "Venus",
      "Tierra",
      "Marte",
      "Júpiter",
      "Saturno",
      "Urano",
      "Neptuno"
    ],
    "correctOrder": [
      "Mercurio",
      "Venus",
      "Tierra",
      "Marte",
      "Júpiter",
      "Saturno",
      "Urano",
      "Neptuno"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Por qué Venus tiene una temperatura de 465 °C mayor que la de Mercurio?",
    "options": [
      "Por un desbocado efecto invernadero provocado por su densa atmósfera de CO₂",
      "Porque tiene erupciones volcánicas continuas que calientan la roca",
      "Porque está más cerca del Sol que Mercurio",
      "Porque no tiene noche"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Entre qué dos planetas se sitúa el Cinturón Principal de Asteroides?",
    "options": [
      "Entre Marte y Júpiter",
      "Entre la Tierra y Marte",
      "Entre Júpiter y Saturno",
      "Más allá de Neptuno"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
