// Autogenerated by GOALS Data Pipeline from 03_rotacion_terrestre_dia_noche_y_husos_horarios.md
import { Question } from '../../types';

export const test03_Rotacion_terrestre_dia_noche_y_husos_horarios: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuánto tiempo dura un Día Sidéreo (un giro exacto de 360° de la Tierra respecto a las estrellas)?",
    "options": [
      "23 horas, 56 minutos y 4 segundos",
      "24 horas exactas",
      "24 horas y 4 minutos",
      "365 días"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A cuántos grados de longitud terrestre equivale el salto de 1 hora en los husos horarios?",
    "options": [
      "15 grados (360° / 24h = 15°)",
      "10 grados",
      "30 grados",
      "24 grados"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las fases del crepúsculo desde el atardecer hasta la noche completa:",
    "items": [
      "Puesta de Sol (0°)",
      "Crepúsculo Civil (0° a -6°)",
      "Crepúsculo Náutico (-6° a -12°)",
      "Crepúsculo Astronómico (-12° a -18°)"
    ],
    "correctOrder": [
      "Puesta de Sol (0°)",
      "Crepúsculo Civil (0° a -6°)",
      "Crepúsculo Náutico (-6° a -12°)",
      "Crepúsculo Astronómico (-12° a -18°)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿En qué lugar de la Tierra la velocidad lineal debida a la rotación es máxima (~1.670 km/h)?",
    "options": [
      "En el Ecuador (latitud 0°)",
      "En el Polo Norte (latitud 90° N)",
      "En el Trópico de Cáncer",
      "En el Círculo Polar Ártico"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
