// Autogenerated by GOALS Data Pipeline from 09_la_via_lactea_y_el_agujero_negro_sagitario_a.md
import { Question } from '../../types';

export const test09_La_via_lactea_y_el_agujero_negro_sagitario_a: Question[] = [
  {
    "type": "choice",
    "question": "¿Qué tipo de galaxia es la Vía Láctea y cuánto mide su diámetro aproximado?",
    "options": [
      "Una galaxia espiral barrada de unos 100.000 años luz de diámetro",
      "Una galaxia elíptica gigante de 1.000 años luz",
      "Una galaxia irregular sin forma definida",
      "Una nebulosa de gas de 10 años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cómo se llama el objeto supermasivo situado en el centro geométrico de la Vía Láctea?",
    "options": [
      "Sagitario A* (un agujero negro supermasivo de 4,15 millones de masas solares)",
      "Betelgeuse",
      "La Nebulosa de Orión",
      "El Sol"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes estructuras desde la MÁS PEQUEÑA hasta la MÁS GRANDE:",
    "items": [
      "Sistema Solar (diámetro ~60 UA)",
      "Brazo de Orión (unos 10.000 al)",
      "Disco de la Vía Láctea (100.000 al)",
      "Halo Galáctico Exterior (300.000 al)"
    ],
    "correctOrder": [
      "Sistema Solar (diámetro ~60 UA)",
      "Brazo de Orión (unos 10.000 al)",
      "Disco de la Vía Láctea (100.000 al)",
      "Halo Galáctico Exterior (300.000 al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuánto tiempo tarda el Sol en completar una vuelta (un 'Año Galáctico') alrededor del centro de la Vía Láctea?",
    "options": [
      "Aproximadamente 230 millones de años",
      "365 días",
      "10.000 años",
      "13.800 millones de años"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
