// Autogenerated by GOALS Data Pipeline from 05_seasons.md
import { Question } from '../../types';

export const test05_Seasons: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuál es la causa física real y fundamental de que en verano haga más calor en el Hemisferio Norte?",
    "options": [
      "La inclinación de 23,44° del eje polar hace que los rayos solares incidan más perpendiculares (mayor W/m²) y los días sean más largos",
      "La Tierra se sitúa 50 millones de kilómetros más cerca del núcleo del Sol",
      "El Sol entra en fase de erupción periódica duplicando su combustible en junio",
      "La Luna bloquea las corrientes de viento frío procedentes del espacio"
    ],
    "answer": 0,
    "explanation": "La inclinación del eje de 23,44° hace que los rayos solares lleguen perpendiculares y concentrados sobre el hemisferio inclinado hacia el Sol, además de aumentar las horas de luz diurna."
  },
  {
    "type": "choice",
    "question": "Cuando en España y Europa es 21 de junio (Solsticio de Verano), ¿qué estación astronómica comienza en Chile y Australia?",
    "options": [
      "Comienza el Invierno austral",
      "Comienza el Verano austral",
      "Comienza la Primavera austral",
      "No tienen estaciones por estar en el sur"
    ],
    "answer": 0,
    "explanation": "Las estaciones son opuestas entre hemisferios porque cuando el Polo Norte apunta hacia el Sol, el Polo Sur apunta en dirección contraria."
  },
  {
    "type": "choice",
    "question": "¿Qué fenómeno astronómico ocurre simultáneamente en todo el planeta durante los equinoccios de marzo y septiembre?",
    "options": [
      "El día y la noche tienen exactamente la misma duración (12 horas de luz y 12 horas de oscuridad) en cualquier latitud",
      "Ocurre un eclipse total de Sol en todos los continentes",
      "La Tierra detiene su rotación durante 1 hora",
      "La temperatura es de 0°C en todo el planeta"
    ],
    "answer": 0,
    "explanation": "En los equinoccios el Sol incide perpendicularmente sobre la línea del ecuador, dividiendo el globo en dos mitades simétricamente iluminadas de 12 horas cada una.",
    "photo": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Por qué la presencia de la Luna es crucial para la estabilidad del clima terrestre a largo plazo?",
    "options": [
      "Porque su gravedad actúa como un ancla que estabiliza la inclinación axial de la Tierra cerca de los 23,44°, evitando oscilaciones caóticas",
      "Porque la Luna calienta los océanos durante la noche con su brillo",
      "Porque la Luna absorbe toda la radiación ultravioleta del Sol",
      "Porque la Luna frena los meteoritos que intentan cambiar el clima"
    ],
    "answer": 0,
    "explanation": "Sin una luna masiva que estabilice el eje de rotación, la oblicuidad de la Tierra oscilaría salvajemente entre 0° y 85° como le ocurre a Marte, provocando cataclismos climáticos."
  },
  {
    "type": "order",
    "question": "Ordena la secuencia cronológica de las 4 estaciones en el Hemisferio Norte empezando por el equinoccio vernal:",
    "items": [
      "Equinoccio de Primavera boreal (~20 de marzo: 12h de luz y 12h de noche)",
      "Solsticio de Verano boreal (~21 de junio: día más largo y máxima altura del Sol)",
      "Equinoccio de Otoño boreal (~22-23 de septiembre: transición equitativa)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año)"
    ],
    "correctOrder": [
      "Equinoccio de Primavera boreal (~20 de marzo: 12h de luz y 12h de noche)",
      "Solsticio de Verano boreal (~21 de junio: día más largo y máxima altura del Sol)",
      "Equinoccio de Otoño boreal (~22-23 de septiembre: transición equitativa)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año)"
    ],
    "explanation": "El ciclo astronómico anual de las estaciones progresa ordenadamente desde la primavera a través del verano y otoño hasta culminar en el invierno."
  }
];
