// Autogenerated by GOALS Data Pipeline from 04_traslacion_anual_kepleriana_y_afelio_perihelio.md
import { Question } from '../../types';

export const test04_Traslacion_anual_kepleriana_y_afelio_perihelio: Question[] = [
  {
    "type": "choice",
    "question": "¿A qué velocidad media viaja la Tierra en su órbita de traslación alrededor del Sol?",
    "options": [
      "~29,78 km/s (107.200 km/h)",
      "~1.670 km/h",
      "~300.000 km/s (velocidad de la luz)",
      "~7,66 km/s"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Según la 2ª Ley de Kepler, ¿en qué punto de su órbita la Tierra viaja a su máxima velocidad orbital (30,29 km/s)?",
    "options": [
      "En el Perihelio (en enero, más cerca del Sol)",
      "En el Afelio (en julio, más lejos del Sol)",
      "En los Equinoccios de primavera y otoño",
      "La velocidad orbital nunca cambia"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los 4 hitos anuales de la Tierra empezando en enero:",
    "items": [
      "Perihelio (~3 de enero)",
      "Equinoccio de Primavera (~20 de marzo)",
      "Afelio (~4 de julio)",
      "Solsticio de Invierno (~21 de diciembre)"
    ],
    "correctOrder": [
      "Perihelio (~3 de enero)",
      "Equinoccio de Primavera (~20 de marzo)",
      "Afelio (~4 de julio)",
      "Solsticio de Invierno (~21 de diciembre)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si un planeta se encontrara a 4 UA del Sol, según la 3ª Ley de Kepler (P² = a³ = 4³ = 64), ¿cuántos años tardaría en completar su órbita?",
    "options": [
      "8 años terrestres (raíz cuadrada de 64)",
      "4 años terrestres",
      "16 años terrestres",
      "64 años terrestres"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
