// Autogenerated by GOALS Data Pipeline from 06_solarsystem.md
import { Question } from '../../types';

export const test06_Solarsystem: Question[] = [
  {
    "type": "choice",
    "question": "¿Por qué Venus tiene la superficie más abrasadora de todo el Sistema Solar (~465 °C)?",
    "options": [
      "Por un desbocado efecto invernadero provocado por su densa atmósfera compuesta en un 96% por CO₂ a 92 atmósferas",
      "Porque está a solo 10.000 kilómetros del núcleo del Sol",
      "Porque el núcleo de Venus tiene reactores de fisión nuclear en la superficie",
      "Porque Venus nunca experimenta la noche"
    ],
    "answer": 0,
    "explanation": "La gruesa manta de dióxido de carbono y nubes de ácido sulfúrico de Venus atrapa la radiación infrarroja impidiendo que el calor escape, elevando la temperatura a 465 °C."
  },
  {
    "type": "choice",
    "question": "¿Qué porcentaje aproximado de toda la masa total del Sistema Solar está concentrado en el Sol?",
    "options": [
      "El 99,86% de la masa total",
      "El 50% de la masa total",
      "El 10% de la masa total",
      "Menos del 1%"
    ],
    "answer": 0,
    "explanation": "El Sol posee prácticamente toda la masa del sistema; los 8 planetas, asteroides y cometas juntos son apenas el 0,14% restante."
  },
  {
    "type": "choice",
    "question": "¿Cuál de los siguientes mundos tiene una densidad tan baja que flotaría en una gigantesca piscina de agua?",
    "options": [
      "Saturno (densidad media de ~0,69 g/cm³, inferior a la del agua líquida de 1,00 g/cm³)",
      "Júpiter",
      "La Tierra",
      "Mercurio"
    ],
    "answer": 0,
    "explanation": "Saturno está compuesto casi enteramente por hidrógeno y helio gaseoso expandido, teniendo una densidad menor que la del agua pura.",
    "photo": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Dónde concentran las agencias espaciales (misiones JUICE y Europa Clipper) la búsqueda de vida en 2026?",
    "options": [
      "En lunas con océanos subterráneos de agua líquida bajo el hielo como Europa y Encélado",
      "En la abrasadora superficie de Mercurio",
      "En el núcleo gaseoso de Júpiter",
      "En los anillos de polvo de Neptuno"
    ],
    "answer": 0,
    "explanation": "Lunas como Europa y Encélado poseen océanos líquidos calentados por fuerzas de marea gravitacionales, con chimeneas hidrotermales y minerales aptos para la vida."
  },
  {
    "type": "order",
    "question": "Ordena los 8 planetas del Sistema Solar por su distancia orbital al Sol (del más cercano al más lejano):",
    "items": [
      "Mercurio (0,39 UA)",
      "Venus (0,72 UA)",
      "Tierra (1,00 UA)",
      "Marte (1,52 UA)",
      "Júpiter (5,20 UA)",
      "Saturno (9,54 UA)",
      "Urano (19,19 UA)",
      "Neptuno (30,07 UA)"
    ],
    "correctOrder": [
      "Mercurio (0,39 UA)",
      "Venus (0,72 UA)",
      "Tierra (1,00 UA)",
      "Marte (1,52 UA)",
      "Júpiter (5,20 UA)",
      "Saturno (9,54 UA)",
      "Urano (19,19 UA)",
      "Neptuno (30,07 UA)"
    ],
    "explanation": "La progresión orbital comienza con los 4 rocosos interiores (Mercurio, Venus, Tierra, Marte) y continúa con los 4 gigantes exteriores (Júpiter, Saturno, Urano, Neptuno)."
  }
];
