// Autogenerated by GOALS Data Pipeline from 08_nearbystars.md
import { Question } from '../../types';

export const test08_Nearbystars: Question[] = [
  {
    "type": "choice",
    "question": "Si desde una colonia en el exoplaneta Próxima b (a 4,24 años luz) transmiten un mensaje de radio hacia la Tierra y se responde de inmediato, ¿cuánto tiempo total transcurre hasta que reciben la respuesta?",
    "options": [
      "8,48 años terrestres (4,24 años de ida + 4,24 años de viaje de vuelta a la velocidad de la luz c)",
      "4,24 años exactos",
      "11,2 días (el periodo de rotación orbital)",
      "La señal llega de forma instantánea mediante entrelazamiento"
    ],
    "answer": 0,
    "explanation": "Como las ondas de radio viajan a la velocidad de la luz ($c$), tardan 4,24 años en viajar de ida y otros 4,24 años en regresar a la Tierra, sumando un retardo total de 8,48 años."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la estrella individual físicamente más cercana a nuestro Sol en el espacio?",
    "options": [
      "Próxima Centauri (a 4,24 años luz, una enana roja del sistema Alfa Centauri)",
      "Sirio A (a 8,60 años luz)",
      "La Estrella Polar / Polaris (a más de 400 años luz)",
      "Betelgeuse (a 640 años luz)"
    ],
    "answer": 0,
    "explanation": "Aunque Alfa Centauri A y B son más brillantes, la pequeña enana roja Próxima Centauri se encuentra ligeramente más próxima a nosotros en su órbita alrededor de ellas."
  },
  {
    "type": "choice",
    "question": "¿Por qué el exoplaneta Próxima b despierta tanto interés en la astrobiología actual?",
    "options": [
      "Porque es un planeta rocoso de tamaño similar a la Tierra situado en la zona de habitabilidad de su estrella",
      "Porque tiene ciudades iluminadas visibles con telescopio",
      "Porque está compuesto enteramente por oro líquido",
      "Porque no tiene gravedad y se puede volar en su atmósfera"
    ],
    "answer": 0,
    "explanation": "Próxima b orbita a la distancia precisa de su estrella para que, con una atmósfera adecuada, el agua pueda existir en estado líquido en su corteza.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué es un Año Luz en la física astronómica?",
    "options": [
      "Una unidad de DISTANCIA que equivale al trayecto recorrido por la luz en el vacío durante un año (~9,46 billones de km)",
      "Una unidad de tiempo que dura 365 días bisiestos",
      "La cantidad de luz que emite el Sol durante el verano",
      "La velocidad a la que giran los agujeros negros"
    ],
    "answer": 0,
    "explanation": "El año luz mide distancia geométrica en el cosmos, calculada multiplicando la velocidad de la luz ($300.000\\text{ km/s}$) por los segundos que contiene un año."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes astros por su distancia real desde nuestro Sol (del más cercano al más lejano):",
    "items": [
      "Próxima Centauri (4,24 años luz - Enana roja vecina)",
      "Par estelar Alfa Centauri A y B (4,37 años luz)",
      "Estrella de Barnard (5,96 años luz)",
      "Luhman 16 (6,51 años luz - Sistema binario de enanas marrones)",
      "Sistema Sirio A y la enana blanca Sirio B (8,60 años luz)"
    ],
    "correctOrder": [
      "Próxima Centauri (4,24 años luz - Enana roja vecina)",
      "Par estelar Alfa Centauri A y B (4,37 años luz)",
      "Estrella de Barnard (5,96 años luz)",
      "Luhman 16 (6,51 años luz - Sistema binario de enanas marrones)",
      "Sistema Sirio A y la enana blanca Sirio B (8,60 años luz)"
    ],
    "explanation": "El vecindario estelar solar inmediato progresa desde el sistema triple Centauri hasta Barnard, Luhman y la brillante estrella Sirio."
  }
];
