// Autogenerated by GOALS Data Pipeline from 05_estaciones_del_ano_y_oblicuidad_axial_23_44.md
import { Question } from '../../types';

export const test05_Estaciones_del_ano_y_oblicuidad_axial_23_44: Question[] = [
  {
    "type": "choice",
    "question": "¿Cuál es la causa física fundamental de que existan las 4 estaciones del año en la Tierra?",
    "options": [
      "La inclinación fija de 23,44° del eje de rotación terrestre",
      "La variación de distancia al Sol entre Perihelio y Afelio",
      "Los cambios en la actividad magnética solar",
      "La rotación de la Luna alrededor de la Tierra"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Sobre qué paralelo geográfico caen perpendiculares (90°) los rayos del Sol durante el Solsticio de Junio?",
    "options": [
      "Trópico de Cáncer (23,44° Norte)",
      "Ecuador terrestre (0°)",
      "Trópico de Capricornio (23,44° Sur)",
      "Círculo Polar Ártico (66,5° Norte)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las estaciones del hemisferio norte empezando por el 21 de marzo:",
    "items": [
      "Primavera (Equinoccio de Marzo)",
      "Verano (Solsticio de Junio)",
      "Otoño (Equinoccio de Septiembre)",
      "Invierno (Solsticio de Diciembre)"
    ],
    "correctOrder": [
      "Primavera (Equinoccio de Marzo)",
      "Verano (Solsticio de Junio)",
      "Otoño (Equinoccio de Septiembre)",
      "Invierno (Solsticio de Diciembre)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si en Madrid (España) es el 21 de diciembre (Solsticio de Invierno), ¿qué estación comienza ese mismo día en Buenos Aires (Argentina)?",
    "options": [
      "Verano (Solsticio de Verano austral)",
      "Invierno austral",
      "Otoño austral",
      "Primavera austral"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
];
