// Autogenerated by GOALS Data Pipeline from 03_rotacion_terrestre_dia_noche_y_husos_horarios.md
import { Lesson } from '../../types';

export const lesson03_Rotacion_terrestre_dia_noche_y_husos_horarios: Lesson = {
  id: 3,
  title: "Rotación Terrestre, Día/Noche y Husos Horarios",
  tag: "Tema 3/12 • 24 Horas • 1.670 km/h",
  icon: "⏳",
  hero: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. El Giro Terrestre y la Velocidad Tangencial",
    "text": "La Tierra rota sobre su eje polar de oeste a este. Da un giro completo de 360° en 23h 56m 4s (Día Sidéreo), requiriendo 24h exactas para que el Sol vuelva al mismo meridiano (Día Solar Medio). En el ecuador, la superficie viaja a 1.670 km/h (464 m/s), disminuyendo con la latitud hasta cero en los polos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra de noche vista desde el espacio con las luces urbanas encendidas.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "2. El Terminador Solar y el Crepúsculo",
    "text": "El Terminador Solar es la línea divisoria móvil de 40.000 km que separa el hemisferio diurno del nocturno. La atmósfera terrestre dispersa la luz solar más allá del borde geométrico creando el crepúsculo (civil, náutico y astronómico), evitando una caída brusca en la oscuridad.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Línea del Terminador Solar dividiendo el día y la noche en la Tierra.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. Los 24 Husos Horarios y el Tiempo Universal (UTC)",
    "text": "La superficie terrestre está dividida en 24 husos horarios de 15° de longitud cada uno (360° / 24h = 15° por hora). El meridiano 0° en Greenwich marca la referencia mundial UTC, mientras que el meridiano 180° en el Pacífico fija la Línea Internacional de Cambio de Fecha.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Meridianos terrestres y cartografía satelital global.",
      "url": "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "4. El Punto Subsolar Cenital y Eratóstenes",
    "text": "El Punto Subsolar es la posición geográfica donde los rayos solares inciden perpendicularmente a 90° sobre el suelo al mediodía. A mayor distancia de este punto, los rayos caen más inclinados y proyectan sombras más largas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Radiación solar y sombras proyectadas en la superficie del planeta.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuánto tiempo dura un Día Sidéreo (un giro exacto de 360° de la Tierra respecto a las estrellas)?",
    "options": [
      "23 horas, 56 minutos y 4 segundos",
      "24 horas exactas",
      "24 horas y 4 minutos",
      "365 días"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A cuántos grados de longitud terrestre equivale el salto de 1 hora en los husos horarios?",
    "options": [
      "15 grados (360° / 24h = 15°)",
      "10 grados",
      "30 grados",
      "24 grados"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las fases del crepúsculo desde el atardecer hasta la noche completa:",
    "items": [
      "Puesta de Sol (0°)",
      "Crepúsculo Civil (0° a -6°)",
      "Crepúsculo Náutico (-6° a -12°)",
      "Crepúsculo Astronómico (-12° a -18°)"
    ],
    "correctOrder": [
      "Puesta de Sol (0°)",
      "Crepúsculo Civil (0° a -6°)",
      "Crepúsculo Náutico (-6° a -12°)",
      "Crepúsculo Astronómico (-12° a -18°)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿En qué lugar de la Tierra la velocidad lineal debida a la rotación es máxima (~1.670 km/h)?",
    "options": [
      "En el Ecuador (latitud 0°)",
      "En el Polo Norte (latitud 90° N)",
      "En el Trópico de Cáncer",
      "En el Círculo Polar Ártico"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
