// Autogenerated by GOALS Data Pipeline from 06_solarsystem.md
import { Lesson } from '../../types';

export const lesson06_Solarsystem: Lesson = {
  id: 6,
  title: "El Sistema Solar y los 8 Planetas",
  tag: "Tema 6 • 60 UA (9.000M km) • Teoría + Práctica 2026",
  icon: "🪐",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "☀️",
    "t": "[Teoría] El Dominio del Sol: 99,86% de la Masa Total",
    "text": "Nuestra estrella, el Sol, acapara el **99,86% de toda la materia del Sistema Solar**. En su interior cabrían 1,3 millones de planetas Tierra. Toda la corte de 8 planetas, más de 200 lunas, asteroides y cometas juntos representa apenas el **0,14%** restante. El Sistema Solar se divide nítidamente en dos reinos separados por el Cinturón de Asteroides: los 4 mundos rocosos interiores y los 4 mundos gigantes exteriores.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Los 8 planetas del Sistema Solar ordenados a escala de tamaño relativo",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Los 4 Planetas Rocosos Interiores",
    "text": "1. **Mercurio (0,39 UA)**: Un mundo metálico sin atmósfera con oscilaciones térmicas extremas de $+430\\text{ }^\\circ\\text{C}$ de día a $-180\\text{ }^\\circ\\text{C}$ de noche.\n2. **Venus (0,72 UA)**: El infierno del sistema solar ($465\\text{ }^\\circ\\text{C}$ de temperatura superficial constante) debido a un efecto invernadero desbocado provocado por un 96% de CO₂ y una presión de 92 atmósferas.\n3. **Tierra (1,00 UA)**: El único oasis con agua líquida superficial, placas tectónicas activas y biosfera.\n4. **Marte (1,52 UA)**: El planeta rojo desértico, hogar del volcán más alto del sistema solar (el Monte Olimpo, de 21,9 km de altitud).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Superficie y nubes sulfúricas de Venus captadas por radar orbital",
      "url": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] El Cinturón de Asteroides y la Línea de Nieve",
    "text": "Entre las órbitas de Marte ($1,5\\text{ UA}$) y Júpiter ($5,2\\text{ UA}$) se extiende el **Cinturón Principal de Asteroides**, compuesto por millones de fragmentos rocosos primigenios que nunca llegaron a fusionarse debido a las perturbaciones gravitatorias de Júpiter. Destacan el planeta enano esférico **Ceres** (940 km de diámetro) y los asteroides gigantes Vesta y Psyche. Aquí se ubica la \"Línea de Nieve\", más allá de la cual el agua y los gases se congelan en hielos sólidos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El planeta enano Ceres y sus misteriosos puntos brillantes de carbonato",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Los 4 Gigantes Exteriores: Gas, Hielo y Anillos",
    "text": "1. **Júpiter (5,2 UA)**: Gigante gaseoso de hidrógeno y helio con su Gran Mancha Roja (un anticiclón más grande que la Tierra activo desde hace más de 300 años).\n2. **Saturno (9,5 UA)**: Con sus majestuosos anillos de $280.000\\text{ km}$ de diámetro formados por partículas de hielo de agua con solo 10 a 100 metros de espesor.\n3. **Urano (19,2 UA)**: Gigante helado de metano que rueda de lado con una inclinación axial extrema de $97,8^\\circ$.\n4. **Neptuno (30,1 UA)**: El mundo más lejano, azotado por los vientos supersónicos más veloces del sistema solar a más de $2.100\\text{ km/h}$.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Detalle de Saturno y sus espectaculares anillos de hielo fotografiado por Cassini",
      "url": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] Océanos Ocultos y las Misiones JUICE y Europa Clipper",
    "text": "Las mayores esperanzas de hallar vida extraterrestre en nuestro vecindario no están en planetas secos, sino en las **lunas heladas con océanos subterráneos globales**:\n- **Europa (Júpiter)**: Esconde un océano con el doble de agua que todos los mares de la Tierra bajo una corteza de hielo.\n- **Encélado (Saturno)**: Expulsa géiseres de agua salada y moléculas orgánicas al espacio.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Géiseres de vapor y hielo brotando del polo sur de la luna Encélado",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Por qué Venus tiene la superficie más abrasadora de todo el Sistema Solar (~465 °C)?",
    "options": [
      "Por un desbocado efecto invernadero provocado por su densa atmósfera compuesta en un 96% por CO₂ a 92 atmósferas",
      "Porque está a solo 10.000 kilómetros del núcleo del Sol",
      "Porque el núcleo de Venus tiene reactores de fisión nuclear en la superficie",
      "Porque Venus nunca experimenta la noche"
    ],
    "answer": 0,
    "explanation": "La gruesa manta de dióxido de carbono y nubes de ácido sulfúrico de Venus atrapa la radiación infrarroja impidiendo que el calor escape, elevando la temperatura a 465 °C."
  },
  {
    "type": "choice",
    "question": "¿Qué porcentaje aproximado de toda la masa total del Sistema Solar está concentrado en el Sol?",
    "options": [
      "El 99,86% de la masa total",
      "El 50% de la masa total",
      "El 10% de la masa total",
      "Menos del 1%"
    ],
    "answer": 0,
    "explanation": "El Sol posee prácticamente toda la masa del sistema; los 8 planetas, asteroides y cometas juntos son apenas el 0,14% restante."
  },
  {
    "type": "choice",
    "question": "¿Cuál de los siguientes mundos tiene una densidad tan baja que flotaría en una gigantesca piscina de agua?",
    "options": [
      "Saturno (densidad media de ~0,69 g/cm³, inferior a la del agua líquida de 1,00 g/cm³)",
      "Júpiter",
      "La Tierra",
      "Mercurio"
    ],
    "answer": 0,
    "explanation": "Saturno está compuesto casi enteramente por hidrógeno y helio gaseoso expandido, teniendo una densidad menor que la del agua pura.",
    "photo": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Dónde concentran las agencias espaciales (misiones JUICE y Europa Clipper) la búsqueda de vida en 2026?",
    "options": [
      "En lunas con océanos subterráneos de agua líquida bajo el hielo como Europa y Encélado",
      "En la abrasadora superficie de Mercurio",
      "En el núcleo gaseoso de Júpiter",
      "En los anillos de polvo de Neptuno"
    ],
    "answer": 0,
    "explanation": "Lunas como Europa y Encélado poseen océanos líquidos calentados por fuerzas de marea gravitacionales, con chimeneas hidrotermales y minerales aptos para la vida."
  },
  {
    "type": "order",
    "question": "Ordena los 8 planetas del Sistema Solar por su distancia orbital al Sol (del más cercano al más lejano):",
    "items": [
      "Mercurio (0,39 UA)",
      "Venus (0,72 UA)",
      "Tierra (1,00 UA)",
      "Marte (1,52 UA)",
      "Júpiter (5,20 UA)",
      "Saturno (9,54 UA)",
      "Urano (19,19 UA)",
      "Neptuno (30,07 UA)"
    ],
    "correctOrder": [
      "Mercurio (0,39 UA)",
      "Venus (0,72 UA)",
      "Tierra (1,00 UA)",
      "Marte (1,52 UA)",
      "Júpiter (5,20 UA)",
      "Saturno (9,54 UA)",
      "Urano (19,19 UA)",
      "Neptuno (30,07 UA)"
    ],
    "explanation": "La progresión orbital comienza con los 4 rocosos interiores (Mercurio, Venus, Tierra, Marte) y continúa con los 4 gigantes exteriores (Júpiter, Saturno, Urano, Neptuno)."
  }
]
};
