// Autogenerated by GOALS Data Pipeline from 08_estrellas_vecinas_alfa_centauri_y_proxima_centauri.md
import { Lesson } from '../../types';

export const lesson08_Estrellas_vecinas_alfa_centauri_y_proxima_centauri: Lesson = {
  id: 8,
  title: "Estrellas Vecinas, Alfa Centauri y Próxima Centauri",
  tag: "Tema 8/12 • 4 - 11 Años Luz • Nuestro Vecindario",
  icon: "✨",
  hero: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. La Medida Cósmica: El Año Luz",
    "text": "En el espacio interestelar los kilómetros se quedan cortos. Usamos el Año Luz: la distancia que recorre la luz en el vacío en un año (9,46 billones de km o 63.241 UA). Mirar estrellas lejanas es mirar al pasado: su luz ha tardado años o siglos en llegar a nuestros ojos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Campo de miles de estrellas fotografiado en la constelación de Centauro.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. El Sistema Triple Alfa Centauri",
    "text": "A 4,37 años luz se halla nuestro sistema estelar vecino: Alfa Centauri A (estrella amarilla como el Sol), Alfa Centauri B (naranja) y Próxima Centauri, una enana roja a 4,24 años luz que ostenta el récord de ser la estrella individual más cercana al Sol.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El par estelar Alfa Centauri A y B capturado por el Telescopio Hubble.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. El Exoplaneta Habitable Próxima b",
    "text": "Orbitando a Próxima Centauri a 7,5 millones de km (0,05 UA) se encuentra Próxima b, un planeta rocoso con 1,17 masas terrestres en la zona habitable (donde el agua podría ser líquida). Su año dura solo 11,2 días terrestres.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Reconstrucción científica del exoplaneta rocoso Próxima b.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "4. Otras Estrellas Vecinas: Sirio y Barnard",
    "text": "En un radio de 11 años luz se hallan mundos fascinantes: la Estrella de Barnard (a 5,96 al), las enanas marrones de Luhman 16 (a 6,5 al) y Sirio (a 8,6 al), la estrella más brillante de nuestro cielo nocturno, acompañada de la enana blanca Sirio B.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Sirio A y su densa enana blanca compañera Sirio B fotografiada por el Hubble.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuál es la estrella individual más cercana a nuestro Sistema Solar?",
    "options": [
      "Próxima Centauri (a 4,24 años luz)",
      "Sirio (a 8,6 años luz)",
      "Betelgeuse (a 640 años luz)",
      "Estrella Polar (a 430 años luz)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué es exactamente un 'año luz'?",
    "options": [
      "La distancia que recorre la luz en el vacío en un año (~9,46 billones de km)",
      "El tiempo que tarda la Tierra en dar una vuelta completa al Sol",
      "La cantidad de luz que emite una estrella en 12 meses",
      "La distancia que hay entre el Sol y Plutón"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena estos sistemas estelares desde el MÁS CERCANO a la Tierra hasta el MÁS LEJANO:",
    "items": [
      "Próxima Centauri (4,24 al)",
      "Estrella de Barnard (5,96 al)",
      "Sirio (8,6 al)",
      "Épsilon Eridani (10,5 al)"
    ],
    "correctOrder": [
      "Próxima Centauri (4,24 al)",
      "Estrella de Barnard (5,96 al)",
      "Sirio (8,6 al)",
      "Épsilon Eridani (10,5 al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué característica especial tiene el exoplaneta Próxima b?",
    "options": [
      "Es un planeta rocoso situado en la zona habitable de Próxima Centauri",
      "Es un gigante de gas con anillos como Saturno",
      "Está cubierto enteramente por un océano de lava a 2.000 °C",
      "No gira alrededor de ninguna estrella"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
