// Autogenerated by GOALS Data Pipeline from 07_oort.md
import { Lesson } from '../../types';

export const lesson07_Oort: Lesson = {
  id: 7,
  title: "La Nube de Oort y la Sonda Voyager 1",
  tag: "Tema 7 • 100.000 UA (1,5 al) • Teoría + Práctica 2026",
  icon: "☄️",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "☀️",
    "t": "[Teoría] La Frontera Real del Sol: La Heliopausa y el Espacio Interestelar",
    "text": "La influencia magnética del Sol genera una burbuja protectora de plasma llamada **Heliosfera**. A unas **$120\\text{ UA}$ ($18.000\\text{ millones de km}$)**, el viento solar colisiona contra el gas y polvo frío de las estrellas vecinas en una frontera llamada **Heliopausa**. Al cruzarla, los instrumentos detectan un salto brusco en los rayos cósmicos galácticos: ¡hemos entrado oficialmente en el espacio interestelar!",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Representación artística de la nave Voyager 1 cruzando la heliopausa hacia el espacio interestelar",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Nube de Oort: El Inmenso Criadero de Cometas",
    "text": "Más allá de la heliopausa se extiende la **Nube de Oort**, una colosal cáscara esférica compuesta por billones de cometas de agua helada, metano y amoníaco. Esta estructura se extiende desde $2.000\\text{ UA}$ hasta **$100.000\\text{ UA}$ (casi 1,5 años luz)**, a medio camino de la estrella más cercana. Es el límite donde la gravedad del Sol es superada por la marea gravitacional de la Vía Láctea.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estructura esférica de la Nube de Oort envolviendo todo el Sistema Solar",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] El Disco de Oro: La Cápsula del Tiempo de la Humanidad",
    "text": "En el lateral de las naves Voyager 1 y Voyager 2 viaja un **Disco de Oro de 30 cm** de cobre bañado en oro, protegido por una cubierta de aluminio y una cápsula de uranio-238 para datar su antigüedad radiométrica. Contiene:\n- Saludos en 55 idiomas humanos y cantos de ballenas.\n- 115 fotografías analógicas de la vida, la anatomía y la Tierra.\n- 90 minutos de música (desde Bach y Mozart hasta Chuck Berry y gaitas tradicionales).\n- El mapa de púlsares con las coordenadas exactas de la Tierra en la galaxia.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El Disco de Oro de la Voyager con los diagramas explicativos grabados en su cubierta",
      "url": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] El Hito de 1 Día-Luz a 25.900 Millones de km",
    "text": "A finales de 2026, la sonda Voyager 1 se sitúa a **$25.900\\text{ millones de km}$ ($173\\text{ UA}$)** del Sol, alcanzando la marca histórica de **1 Día-Luz de distancia**. Una orden enviada por radio a la velocidad de la luz ($300.000\\text{ km/s}$) desde la Red del Espacio Profundo de Robledo de Chavela (Madrid) tarda 24 horas en llegar a la nave y 24 horas en devolver telemetría (¡48 horas de tiempo de ida y vuelta!).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Antenas gigantes de la Deep Space Network en Madrid comunicando con Voyager 1",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] Hacia las Estrellas: El Futuro de las Sondas Interestelares",
    "text": "La Voyager 1 viaja a **$17\\text{ km/s}$ ($61.200\\text{ km/h}$)**. Aunque cruzará la Nube de Oort durante los próximos 30.000 años, dentro de 40.000 años pasará a 1,6 años luz de la estrella enana roja **Gliese 445** en la constelación de Camelopardalis, vagando eternamente por el disco galáctico.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Concepto de microvela interestelar propulsada por láser óptico",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué hito de distancia histórica alcanza la sonda Voyager 1 hacia finales de 2026?",
    "options": [
      "Situarse a 1 Día-Luz de la Tierra (~25.900 millones de km), requiriendo 24 horas para que una señal de radio llegue a la nave",
      "Entrar en órbita alrededor de Próxima Centauri",
      "Aterrizar sobre el cometa Halley",
      "Regresar a la Tierra impulsada por gravedad"
    ],
    "answer": 0,
    "explanation": "A 1 Día-Luz de distancia, la radiación electromagnética (viajando a 300.000 km/s) tarda 24 horas completas en recorrer la distancia entre la Tierra y la nave."
  },
  {
    "type": "choice",
    "question": "¿Qué es la Nube de Oort según la astrofísica planetaria?",
    "options": [
      "Una gigantesca cáscara esférica de billones de cometas helados que envuelve al Sistema Solar hasta 100.000 UA",
      "Una nube de polvo que oscurece el disco solar en invierno",
      "Un anillo plano de asteroides metálicos entre Marte y Júpiter",
      "La atmósfera gaseosa del planeta Plutón"
    ],
    "answer": 0,
    "explanation": "Propuesta por el astrónomo Jan Oort, es una nube esférica que marca el límite gravitatorio del Sistema Solar y el reservorio de los cometas de largo período."
  },
  {
    "type": "choice",
    "question": "¿Qué mensaje transportan las sondas Voyager grabado en su emblemático Disco de Oro?",
    "options": [
      "Sonidos de la Tierra, música de diversas culturas, saludos en 55 idiomas, diagramas anatómicos y coordenadas estelares",
      "Un plano secreto de depósitos de combustible nuclear",
      "Una lista clasificada de astronautas militares",
      "Un disco duro digital con código binario ejecutable"
    ],
    "answer": 0,
    "explanation": "Diseñado por un comité presidido por Carl Sagan, el Disco de Oro es una cápsula cultural y biológica fonográfica diseñada para durar más de 1.000 millones de años.",
    "photo": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué frontera delimita el final de la Heliosfera solar y el inicio del espacio interestelar?",
    "options": [
      "La Heliopausa (a unas ~120 UA), donde el viento solar se frena contra el medio interestelar",
      "La órbita de la Luna a 384.400 km",
      "El Cinturón de Asteroides a 2,8 UA",
      "El centro de la Vía Láctea"
    ],
    "answer": 0,
    "explanation": "La Heliopausa es la frontera física donde la presión hacia afuera del viento solar se equilibra con la presión del gas interestelar galáctico."
  },
  {
    "type": "order",
    "question": "Ordena las regiones del Sistema Solar exterior desde el Sol hacia las estrellas vecinas:",
    "items": [
      "Cinturón de Kuiper (30 a 55 UA - Planetas enanos como Plutón)",
      "Choque de Terminación (~80 a 90 UA - Frenado del viento solar)",
      "Heliopausa (~120 UA - Frontera interestelar oficial)",
      "Nube de Oort interior (~2.000 a 20.000 UA)",
      "Límite exterior de la Nube de Oort (~100.000 UA - Frontera gravitatoria solar)"
    ],
    "correctOrder": [
      "Cinturón de Kuiper (30 a 55 UA - Planetas enanos como Plutón)",
      "Choque de Terminación (~80 a 90 UA - Frenado del viento solar)",
      "Heliopausa (~120 UA - Frontera interestelar oficial)",
      "Nube de Oort interior (~2.000 a 20.000 UA)",
      "Límite exterior de la Nube de Oort (~100.000 UA - Frontera gravitatoria solar)"
    ],
    "explanation": "La arquitectura externa progresa desde el cinturón transneptuniano hasta la heliopausa y la inmensa esfera de cometas de Oort."
  }
]
};
