// Autogenerated by GOALS Data Pipeline from 09_milkyway.md
import { Lesson } from '../../types';

export const lesson09_Milkyway: Lesson = {
  id: 9,
  title: "La Vía Láctea y Sagitario A*",
  tag: "Tema 9 • 100.000 Años Luz • Teoría + Práctica 2026",
  icon: "🌌",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "☀️",
    "t": "[Teoría] La Metrópolis Galáctica de 200.000 Millones de Soles",
    "text": "La Vía Láctea es una majestuosa **Galaxia Espiral Barrada (tipo SBbc)** con un diámetro de **$100.000\\text{ años luz}$** y un espesor medio de solo $1.000\\text{ al}$ en su disco estelar. Contiene entre 200.000 y 400.000 millones de estrellas. Nuestro Sistema Solar no está en el centro, sino en un apéndice tranquilo llamado el **Espolón de Orión**, a $26.000\\text{ años luz}$ del núcleo.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Panorámica de la estructura espiral de la Vía Láctea y la posición de nuestro Sol",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Materia Oscura: El Pegamento Invisible del Cosmos",
    "text": "Al medir la velocidad de rotación de las estrellas en los bordes de la galaxia (Curva de Rotación de Vera Rubin), los astrofísicos descubrieron una paradoja: las estrellas exteriores giran a la misma velocidad ($220\\text{ km/s}$) que las interiores, en lugar de frenarse. La única explicación física es que la Vía Láctea está inmersa en un colosal **Halo de Materia Oscura** que contiene el **85% de toda la masa gravitatoria** de la galaxia.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Curva de rotación galáctica y distribución de materia oscura",
      "url": "https://images-assets.nasa.gov/image/potw1343a/potw1343a~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Sagitario A*: El Monstruo Gravitacional del Núcleo",
    "text": "En el centro exacto de la galaxia reside **Sagitario A\\* ($Sgr\\text{ }A^*$)*, un **agujero negro supermasivo con una masa equivalente a 4,15 millones de soles** comprimida en una esfera menor que la órbita de Mercurio ($R_s \\approx 12\\text{ millones de km}$). Su gravedad extrema curva el tejido del espacio-tiempo, haciendo que estrellas como S2 giren a su alrededor al 3% de la velocidad de la luz.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Primera fotografía histórica del agujero negro supermasivo Sagitario A*",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Brazos Espirales y Maternidades Estelares",
    "text": "Los brazos de la galaxia (Perseo, Escudo-Centauro, Sagitario y Norma) no son estructuras rígidas, sino **ondas de densidad de compresión gravitacional**. Al chocar el gas interestelar contra estas ondas, se comprime y enciende el nacimiento de miles de nuevas estrellas en gigantescas nebulosas de emisión como la Nebulosa de Orión o los Pilares de la Creación.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Pilares de la Creación en la Nebulosa del Águila fotografiados por James Webb",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Práctica 2026] El Cartografiado de 2.000 Millones de Estrellas con Gaia",
    "text": "En 2026, el telescopio espacial **Gaia de la ESA** publica su catálogo astrométrico definitivo (Gaia DR4), midiendo las posiciones 3D, distancias por paralaje milimétrico y velocidades de más de 2.000 millones de estrellas, revelando las \"fósiles galácticos\" de antiguas galaxias enanas devoradas por la Vía Láctea en el pasado (como la fusión Gaia-Enceladus).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mapa de densidad estelar y polvo cósmico de la Vía Láctea captado por Gaia",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué hallazgo astrofísico demostró que la Vía Láctea está envuelta en un masivo halo de Materia Oscura?",
    "options": [
      "Que las estrellas del borde exterior de la galaxia giran a la misma velocidad (~220 km/s) que las interiores en vez de desacelerarse",
      "Que el centro de la galaxia carece por completo de gas",
      "Que las estrellas del núcleo galáctico son más frías que el Sol",
      "Que la Vía Láctea no tiene brazos espirales"
    ],
    "answer": 0,
    "explanation": "Según la gravedad newtoniana simple, las estrellas periféricas deberían girar mucho más lento; la curva de rotación plana descubierta por Vera Rubin demostró la existencia del halo invisible de materia oscura."
  },
  {
    "type": "choice",
    "question": "¿Cuánto tiempo tarda nuestro Sistema Solar en dar una vuelta completa alrededor del centro galáctico (Año Cósmico)?",
    "options": [
      "Aproximadamente 230 millones de años terrestres (viajando a ~828.000 km/h)",
      "365 días bisiestos",
      "10.000 años",
      "1 millón de años"
    ],
    "answer": 0,
    "explanation": "A una distancia de 26.000 años luz del núcleo galáctico, el Sol tarda unos 230 millones de años en completar una revolución orbital en la Vía Láctea."
  },
  {
    "type": "choice",
    "question": "¿Qué masa posee el agujero negro supermasivo Sagitario A* situado en el núcleo de nuestra galaxia?",
    "options": [
      "Aproximadamente 4,15 millones de masas solares ($M_\\odot$)",
      "La masa de un grano de polvo cósmico",
      "Exactamente la masa del planeta Tierra",
      "100 masas solares"
    ],
    "answer": 0,
    "explanation": "El seguimiento orbital de estrellas ultrarrápidas como S2 durante más de dos décadas (Premio Nobel de Física 2020) permitió determinar con precisión su masa de 4,15 millones de soles.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué son en realidad los brazos espirales de la Vía Láctea?",
    "options": [
      "Ondas de densidad de compresión donde el gas se condensa y nacen nuevas generaciones de estrellas",
      "Estructuras sólidas de roca que giran rígidamente",
      "Rayos láser emitidos por el agujero negro central",
      "Ríos de agua líquida flotando en el espacio"
    ],
    "answer": 0,
    "explanation": "Los brazos espirales son ondas de densidad a través de las cuales viajan las estrellas, funcionando como viveros donde el gas se comprime y forma cúmulos estelares."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes regiones anatómicas de la Vía Láctea desde el centro hacia los confines exteriores:",
    "items": [
      "Horizonte de Sucesos de Sagitario A* (Radio de Schwarzschild de ~12M km)",
      "Bulbo Galáctico central (Enjambre denso de estrellas viejas)",
      "Disco estelar y Brazo de Orión (Ubicación del Sistema Solar a 26.000 al)",
      "Disco gaseoso exterior (Límite óptico a 50.000 al del centro)",
      "Halo esférico de Materia Oscura y Cúmulos Globulares (Se extiende hasta 300.000 al)"
    ],
    "correctOrder": [
      "Horizonte de Sucesos de Sagitario A* (Radio de Schwarzschild de ~12M km)",
      "Bulbo Galáctico central (Enjambre denso de estrellas viejas)",
      "Disco estelar y Brazo de Orión (Ubicación del Sistema Solar a 26.000 al)",
      "Disco gaseoso exterior (Límite óptico a 50.000 al del centro)",
      "Halo esférico de Materia Oscura y Cúmulos Globulares (Se extiende hasta 300.000 al)"
    ],
    "explanation": "La estructura galáctica progresa desde la singularidad central y el bulbo pasando por el disco espiral hasta el inmenso halo de materia oscura exterior."
  }
]
};
