// Autogenerated by GOALS Data Pipeline from 10_localgroup.md
import { Lesson } from '../../types';

export const lesson10_Localgroup: Lesson = {
  id: 10,
  title: "El Grupo Local y Andrómeda (M31)",
  tag: "Tema 10 • 10 Millones al • Teoría + Práctica 2026",
  icon: "🌀",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Archipiélago Galáctico de 80 Islas Cósmicas",
    "text": "Nuestra galaxia no flota solitaria en el abismo, sino que forma parte del **Grupo Local de Galaxias**: una familia gravitatoria de más de **80 galaxias** que se extiende por un diámetro de **$10\\text{ millones de años luz}$**. Las dos gigantes dominantes son:\n1. **Galaxia de Andrómeda (M31)**: Monstruo espiral a $2,537\\text{ millones de años luz}$ con más de 1 billón ($10^{12}$) de estrellas.\n2. **La Vía Láctea**: Con unos 300.000 millones de estrellas y una masa gravitacional comparable gracias a su masivo halo de materia oscura.\n3. **Galaxia del Triángulo (M33)**: Tercera en tamaño, con 40.000 millones de soles.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mosaico ultra-detallado de la Galaxia de Andrómeda captado por el telescopio espacial Hubble",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🛰️",
    "t": "[Teoría] Galaxias Satélite: Las Nubes de Magallanes y Sagitario",
    "text": "Orbitando como escoltas alrededor de la Vía Láctea se encuentran decenas de galaxias enanas:\n- **Gran Nube de Magallanes (163.000 al)**: Galaxia irregular enana visible en el cielo del hemisferio sur, hogar de la colosal Maternidad Estelar de la Tarántula (30 Doradus).\n- **Pequeña Nube de Magallanes (200.000 al)**: Galaxia satélite vecina.\n- **Galaxia Enana Elíptica de Sagitario (70.000 al)**: Siendo desgarrada por las fuerzas de marea de la Vía Láctea.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Gran Nube de Magallanes y la brillante Nebulosa de la Tarántula",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Gran Fusión Galáctica: Milkomeda en 4.500 Millones de Años",
    "text": "A diferencia del universo distante donde el espacio se expande, la Vía Láctea y Andrómeda están unidas por una atracción gravitatoria tan feroz que viajan la una hacia la otra a **$110\\text{ km/s}$ ($400.000\\text{ km/h}$)**. En unos **4.500 millones de años**, colisionarán y se fusionarán en una colosal galaxia elíptica gigante bautizada como **Milkomeda (o Lactómeda)**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Simulación visual del cielo nocturno de la Tierra durante la colisión entre la Vía Láctea y Andrómeda",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Corrientes de Marea y Canibalismo Galáctico",
    "text": "Las galaxias crecen devorando a sus vecinas menores mediante **canibalismo galáctico**. Las colosales fuerzas de marea gravitacional estiran a las galaxias enanas en largos filamentos llamados **Corrientes Estelares** (como la corriente de Sagitario o la corriente de Magallanes), absorbiendo su gas y reabasteciendo el combustible para fabricar nuevas estrellas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Corrientes estelares de marea galáctica alrededor de galaxias espirales",
      "url": "https://images-assets.nasa.gov/image/potw1343a/potw1343a~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "[Práctica 2026] El Telescopio Espacial Euclid y la Materia Oscura",
    "text": "En 2026, el telescopio espacial **Euclid de la ESA** cartografía la distribución 3D de la materia oscura y las galaxias enanas del Grupo Local mediante el análisis de **Lentes Gravitacionales Débiles**, comprobando cómo los filamentos invisibles canalizan el movimiento de las galaxias hacia el centro de masa del grupo.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mapa de lentes gravitacionales y cúmulos galácticos captado por Euclid",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Por qué la Galaxia de Andrómeda se precipita hacia la Vía Láctea a 110 km/s a pesar de la expansión general del universo?",
    "options": [
      "Porque la atracción gravitatoria mutua y la masa de sus halos de materia oscura superan a la expansión cósmica a distancias locales cortas",
      "Porque la Tierra emite un campo magnético atractor",
      "Porque el agujero negro de Andrómeda succiona a toda la galaxia",
      "Porque el viento solar empuja a Andrómeda"
    ],
    "answer": 0,
    "explanation": "A escalas inferiores a ~10 millones de años luz, la gravedad local vence a la expansión de Hubble, provocando que los miembros del Grupo Local se atraigan mutuamente."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de nuestro Sistema Solar se encuentra la Galaxia de Andrómeda (M31)?",
    "options": [
      "A 2,537 millones de años luz (el objeto visible a simple vista más lejano)",
      "A 100.000 años luz",
      "A 8 minutos luz como el Sol",
      "A 100.000 millones de años luz"
    ],
    "answer": 0,
    "explanation": "Andrómeda se sitúa a unos 2,5 millones de años luz, por lo que la luz que vemos de ella partió cuando los primeros homínidos (Australopithecus) caminaban por la Tierra."
  },
  {
    "type": "choice",
    "question": "¿Chocarán físicamente las estrellas del Sol y de Andrómeda cuando ambas galaxias se fusionen en Milkomeda dentro de 4.500 millones de años?",
    "options": [
      "Prácticamente ninguna estrella chocará directamente, debido a las inmensas distancias de vacío que las separan",
      "Sí, todas las estrellas chocarán y explotarán como supernovas",
      "La Tierra se evaporará al instante en el primer segundo",
      "Ambas galaxias rebotarán como pelotas de goma"
    ],
    "answer": 0,
    "explanation": "Las galaxias son en su inmensa mayoría espacio vacío; las órbitas de las estrellas se reorganizarán gravitacionalmente pero las colisiones directas entre astros serán casi nulas.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Cuál es la galaxia satélite más cercana y prominente que orbita alrededor de la Vía Láctea?",
    "options": [
      "La Gran Nube de Magallanes (a unos 163.000 años luz)",
      "La Galaxia del Triángulo M33",
      "La Galaxia del Sombrero",
      "El cúmulo de Virgo"
    ],
    "answer": 0,
    "explanation": "La Gran Nube de Magallanes es una galaxia satélite enana que acompaña a la Vía Láctea a una distancia de tan solo 163.000 años luz."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes componentes del Grupo Local desde el más cercano a la Tierra hasta el borde exterior:",
    "items": [
      "Gran Nube de Magallanes (163.000 al - Satélite enana austral)",
      "Pequeña Nube de Magallanes (200.000 al)",
      "Galaxia de Andrómeda M31 (2,537 Millones al - Espiral gigante)",
      "Galaxia del Triángulo M33 (2,73 Millones al)",
      "Límite gravitacional exterior del Grupo Local (~10 Millones al)"
    ],
    "correctOrder": [
      "Gran Nube de Magallanes (163.000 al - Satélite enana austral)",
      "Pequeña Nube de Magallanes (200.000 al)",
      "Galaxia de Andrómeda M31 (2,537 Millones al - Espiral gigante)",
      "Galaxia del Triángulo M33 (2,73 Millones al)",
      "Límite gravitacional exterior del Grupo Local (~10 Millones al)"
    ],
    "explanation": "La escala del Grupo Local se extiende desde las galaxias satélites inmediatas hasta las grandes espirales de Andrómeda y Triángulo en su límite de 10 millones de años luz."
  }
]
};
