// Autogenerated by GOALS Data Pipeline from 05_seasons.md
import { Lesson } from '../../types';

export const lesson05_Seasons: Lesson = {
  id: 5,
  title: "Estaciones del Año y Oblicuidad Axial",
  tag: "Tema 5 • 23,44° de Inclinación • Teoría + Práctica 2026",
  icon: "☀️",
  hero: "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Eje Inclinado de 23,44°: La Causa Real del Clima",
    "text": "Las estaciones del año NO se deben a la distancia de la Tierra al Sol (de hecho, estamos más cerca del Sol en enero). La causa fundamental es que el eje polar de la Tierra mantiene una **inclinación constante de $23,44^\\circ$ respecto a la perpendicular de su órbita**. A medida que nos trasladamos alrededor del Sol, el Polo Norte apunta hacia el Sol durante medio año (primavera y verano boreal) y en dirección opuesta durante el otro medio año (otoño e invierno boreal).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Inclinación del eje de 23.44 grados y distribución de luz solar en los hemisferios",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] La Física del Haz de Linterna e Insolación ($W/m^2$)",
    "text": "¿Por qué hace calor en verano?\n1. **Ángulo de Incidencia**: Cuando el Sol está alto a mediodía, un haz de luz de $1.000\\text{ W}$ cae perpendicular concentrándose en $1\\text{ m}^2$ de suelo (calor intenso). En invierno, el Sol está bajo y ese mismo haz de $1.000\\text{ W}$ se estira oblicuo sobre $2\\text{ o }3\\text{ m}^2$, calentando con mucha menos intensidad.\n2. **Duración del Día**: En verano el Sol recorre un arco más largo en el cielo, brillando hasta 15 horas al día en España frente a solo 9 horas en invierno.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Distribución geométrica del flujo solar directo versus oblicuo",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] Solsticios, Equinoccios y Estaciones Invertidas",
    "text": "- **Solsticio de Junio (~20-21 de junio)**: El Sol incide cenital sobre el Trópico de Cáncer ($23,5^\\circ\\text{ N}$). Es el día más largo del año en el Hemisferio Norte (Verano) y el más corto en el Hemisferio Sur (Invierno).\n- **Equinoccios de Marzo (~20 marzo) y Septiembre (~22-23 sept)**: El Sol incide perpendicular sobre el Ecuador. El día y la noche duran exactamente 12 horas en todo el planeta.\n- **Solsticio de Diciembre (~21-22 de diciembre)**: El Sol incide cenital sobre el Trópico de Capricornio ($23,5^\\circ\\text{ S}$). Es verano en Australia y Argentina e invierno en Europa.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra en solsticio mostrando el casquete polar iluminado",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌑",
    "t": "[Teoría] La Luna como Estabilizador Climático",
    "text": "El tirón gravitatorio de nuestra Luna masiva ($M_{Luna} \\approx 1/81 M_{Tierra}$) actúa como un contrapeso giroscópico que mantiene la inclinación de la Tierra estable entre $22,1^\\circ$ y $24,5^\\circ$ a lo largo de ciclos de 41.000 años (Ciclos de Milankovitch). Sin la Luna, la Tierra se tambalearía caóticamente entre $0^\\circ$ y $85^\\circ$ como Marte, desatando glaciaciones salvajes y extinciones masivas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Luna y la Tierra fotografiados juntos en el espacio profundo",
      "url": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🛰️",
    "t": "[Práctica 2026] El Balance Radiativo Global con Satélites CERES",
    "text": "En 2026, los instrumentos **CERES (Clouds and the Earth's Radiant Energy System)** a bordo de los satélites Terra, Aqua y NOAA-20 miden continuamente los vatios por metro cuadrado ($W/m^2$) de energía solar reflejada y calor infrarrojo emitido al espacio, monitorizando el deshielo estacional y la respuesta climática global.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mapa de radiación neta e insolación de los polos captado por CERES",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuál es la causa física real y fundamental de que en verano haga más calor en el Hemisferio Norte?",
    "options": [
      "La inclinación de 23,44° del eje polar hace que los rayos solares incidan más perpendiculares (mayor W/m²) y los días sean más largos",
      "La Tierra se sitúa 50 millones de kilómetros más cerca del núcleo del Sol",
      "El Sol entra en fase de erupción periódica duplicando su combustible en junio",
      "La Luna bloquea las corrientes de viento frío procedentes del espacio"
    ],
    "answer": 0,
    "explanation": "La inclinación del eje de 23,44° hace que los rayos solares lleguen perpendiculares y concentrados sobre el hemisferio inclinado hacia el Sol, además de aumentar las horas de luz diurna."
  },
  {
    "type": "choice",
    "question": "Cuando en España y Europa es 21 de junio (Solsticio de Verano), ¿qué estación astronómica comienza en Chile y Australia?",
    "options": [
      "Comienza el Invierno austral",
      "Comienza el Verano austral",
      "Comienza la Primavera austral",
      "No tienen estaciones por estar en el sur"
    ],
    "answer": 0,
    "explanation": "Las estaciones son opuestas entre hemisferios porque cuando el Polo Norte apunta hacia el Sol, el Polo Sur apunta en dirección contraria."
  },
  {
    "type": "choice",
    "question": "¿Qué fenómeno astronómico ocurre simultáneamente en todo el planeta durante los equinoccios de marzo y septiembre?",
    "options": [
      "El día y la noche tienen exactamente la misma duración (12 horas de luz y 12 horas de oscuridad) en cualquier latitud",
      "Ocurre un eclipse total de Sol en todos los continentes",
      "La Tierra detiene su rotación durante 1 hora",
      "La temperatura es de 0°C en todo el planeta"
    ],
    "answer": 0,
    "explanation": "En los equinoccios el Sol incide perpendicularmente sobre la línea del ecuador, dividiendo el globo en dos mitades simétricamente iluminadas de 12 horas cada una.",
    "photo": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Por qué la presencia de la Luna es crucial para la estabilidad del clima terrestre a largo plazo?",
    "options": [
      "Porque su gravedad actúa como un ancla que estabiliza la inclinación axial de la Tierra cerca de los 23,44°, evitando oscilaciones caóticas",
      "Porque la Luna calienta los océanos durante la noche con su brillo",
      "Porque la Luna absorbe toda la radiación ultravioleta del Sol",
      "Porque la Luna frena los meteoritos que intentan cambiar el clima"
    ],
    "answer": 0,
    "explanation": "Sin una luna masiva que estabilice el eje de rotación, la oblicuidad de la Tierra oscilaría salvajemente entre 0° y 85° como le ocurre a Marte, provocando cataclismos climáticos."
  },
  {
    "type": "order",
    "question": "Ordena la secuencia cronológica de las 4 estaciones en el Hemisferio Norte empezando por el equinoccio vernal:",
    "items": [
      "Equinoccio de Primavera boreal (~20 de marzo: 12h de luz y 12h de noche)",
      "Solsticio de Verano boreal (~21 de junio: día más largo y máxima altura del Sol)",
      "Equinoccio de Otoño boreal (~22-23 de septiembre: transición equitativa)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año)"
    ],
    "correctOrder": [
      "Equinoccio de Primavera boreal (~20 de marzo: 12h de luz y 12h de noche)",
      "Solsticio de Verano boreal (~21 de junio: día más largo y máxima altura del Sol)",
      "Equinoccio de Otoño boreal (~22-23 de septiembre: transición equitativa)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año)"
    ],
    "explanation": "El ciclo astronómico anual de las estaciones progresa ordenadamente desde la primavera a través del verano y otoño hasta culminar en el invierno."
  }
]
};
