// Autogenerated by GOALS Data Pipeline from 04_traslacion_anual_kepleriana_y_afelio_perihelio.md
import { Lesson } from '../../types';

export const lesson04_Traslacion_anual_kepleriana_y_afelio_perihelio: Lesson = {
  id: 4,
  title: "Traslación Anual Kepleriana y Afelio/Perihelio",
  tag: "Tema 4/12 • 1 UA • 29,78 km/s",
  icon: "🛰️",
  hero: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. La Órbita Elíptica y la Primera Ley de Kepler",
    "text": "La Tierra describe una elipse alrededor del Sol con este situado en uno de sus focos (1ª Ley de Kepler). El semieje mayor mide 149.597.870 km (1 Unidad Astronómica o UA). La excentricidad es casi circular (e = 0,0167), pero produce cambios medibles de distancia a lo largo del año.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra en su viaje elíptico alrededor del Sol.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. Perihelio y Afelio: Distancias Extremas",
    "text": "En enero, la Tierra alcanza el Perihelio (su punto más cercano al Sol a 147 millones de km). En julio, alcanza el Afelio (su punto más lejano a 152 millones de km). Esto prueba que la distancia al Sol no causa las estaciones: ¡en enero es pleno invierno en Europa y Norteamérica!",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La fotosfera solar y emisión de radiación térmica.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. La Segunda Ley de Kepler y la Velocidad Orbital",
    "text": "La línea imaginaria Sol-Tierra barre áreas iguales en tiempos iguales (2ª Ley de Kepler). Por ello, la Tierra acelera cerca del Sol en el perihelio (30,29 km/s) y frena en el afelio (29,29 km/s), con una velocidad media de 29,78 km/s (107.200 km/h).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Vectores de velocidad y trayectoria orbital planetaria.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. La Tercera Ley de Kepler y la Armonía Planetaria",
    "text": "El cuadrado del periodo orbital (P²) es proporcional al cubo de la distancia media al Sol (a³): P²/a³ = constante. Para la Tierra (1 UA, 1 año) el valor es 1. Por ello los planetas exteriores tardan décadas o siglos en dar una vuelta completa.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Curvas de luz en tránsitos de sistemas planetarios.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿A qué velocidad media viaja la Tierra en su órbita de traslación alrededor del Sol?",
    "options": [
      "~29,78 km/s (107.200 km/h)",
      "~1.670 km/h",
      "~300.000 km/s (velocidad de la luz)",
      "~7,66 km/s"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Según la 2ª Ley de Kepler, ¿en qué punto de su órbita la Tierra viaja a su máxima velocidad orbital (30,29 km/s)?",
    "options": [
      "En el Perihelio (en enero, más cerca del Sol)",
      "En el Afelio (en julio, más lejos del Sol)",
      "En los Equinoccios de primavera y otoño",
      "La velocidad orbital nunca cambia"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los 4 hitos anuales de la Tierra empezando en enero:",
    "items": [
      "Perihelio (~3 de enero)",
      "Equinoccio de Primavera (~20 de marzo)",
      "Afelio (~4 de julio)",
      "Solsticio de Invierno (~21 de diciembre)"
    ],
    "correctOrder": [
      "Perihelio (~3 de enero)",
      "Equinoccio de Primavera (~20 de marzo)",
      "Afelio (~4 de julio)",
      "Solsticio de Invierno (~21 de diciembre)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si un planeta se encontrara a 4 UA del Sol, según la 3ª Ley de Kepler (P² = a³ = 4³ = 64), ¿cuántos años tardaría en completar su órbita?",
    "options": [
      "8 años terrestres (raíz cuadrada de 64)",
      "4 años terrestres",
      "16 años terrestres",
      "64 años terrestres"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
