// Autogenerated by GOALS Data Pipeline from 11_laniakea.md
import { Lesson } from '../../types';

export const lesson11_Laniakea: Lesson = {
  id: 11,
  title: "La Red Cósmica Laniakea y el Gran Atractor",
  tag: "Tema 11 • 520 Millones al • Teoría + Práctica 2026",
  icon: "🕸️",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] La Telaraña Cósmica: Nodos, Filamentos y Grandes Vacíos",
    "text": "A gran escala, el universo no es un cúmulo caótico de estrellas, sino una **Red Cósmica** que se asemeja a una telaraña neuronal tridimensional:\n- **Filamentos**: Ríos luminosos de materia oscura y gas donde viajan millones de galaxias.\n- **Nodos (Supercúmulos)**: Intersecciones masivas donde convergen miles de cúmulos de galaxias.\n- **Vacíos Cósmicos (Voids)**: Inmensos desiertos espaciales de hasta $150\\text{ millones de años luz}$ de diámetro (como el Vacío de Boötes) donde la densidad de materia es casi nula.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estructura filamentaria de la telaraña cósmica y supercúmulos de galaxias",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Nuestro Continente Galáctico: Laniakea",
    "text": "En 2014, el equipo del astrofísico R. Brent Tully (Universidad de Hawái) definió la frontera de nuestro hogar cósmico: el **Supercúmulo Laniakea** (\"Cielos Inmensos\" en lengua hawaiana). Mide **$520\\text{ millones de años luz}$ de extensión**, engloba una masa de $10^{17}\\text{ masas solares}$ (100.000 veces la Vía Láctea) y alberga más de **100.000 galaxias mayores** organizadas en 4 subcúmulos: Virgo, Hydra, Centaurus y Pavo-Indus.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Líneas de corriente de velocidad de las galaxias convergiendo en Laniakea",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] El Gran Atractor y el Dipolo Repulsor",
    "text": "En el corazón gravitatorio de Laniakea reside una anomalía de masa descomunal conocida como el **Gran Atractor**, situado a $220\\text{ millones de años luz}$ en dirección a la constelación de Norma (detrás de la \"Zona de Evitación\" del polvo de nuestra propia galaxia). La Vía Láctea y todo el Grupo Local viajan a **$2,2\\text{ millones de km/h}$ ($627\\text{ km/s}$)** atraídos por el Gran Atractor y simultáneamente \"empujados\" por el vacío del **Dipolo Repulsor**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Esquema de vectores de flujo hacia el Gran Atractor y el Cúmulo de Shapley",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Más Allá de Laniakea: El Supercúmulo de Shapley",
    "text": "Laniakea no es el final de la jerarquía. Hacia adelante se encuentra el gigantesco **Supercúmulo de Shapley**, una concentración de más de 8.000 galaxias que ejerce una atracción gravitatoria aún mayor a $650\\text{ millones de años luz}$. La energía oscura y la expansión acelerada del universo determinarán si Laniakea llegará a fusionarse con Shapley o si la expansión del espacio terminará por separarlos para siempre.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Cúmulos de galaxias masivos del supercúmulo de Shapley",
      "url": "https://images-assets.nasa.gov/image/potw1343a/potw1343a~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "[Práctica 2026] El Telescopio Espacial Euclid y la Energía Oscura",
    "text": "En 2026, el telescopio espacial **Euclid de la ESA** analiza el corrimiento al rojo espectroscópico de más de 1.500 millones de galaxias hasta una distancia de 10.000 millones de años luz. Su objetivo es medir con precisión sub-porcentual la **Ecuación de Estado de la Energía Oscura ($w$)** y cartografiar en 3D el crecimiento de la red de filamentos cósmicos a lo largo del tiempo.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Campo profundo ultra-nítido con miles de galaxias distantes captado por Euclid",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cómo definieron los astrofísicos la frontera exacta de nuestro supercúmulo Laniakea?",
    "options": [
      "Como una cuenca gravitacional delimitada por la línea donde las galaxias dejan de fluir hacia el Gran Atractor y caen hacia otro supercúmulo vecino",
      "Como un muro de estrellas gigantes visible en el telescopio",
      "Como la frontera donde la gravedad deja de existir en el universo",
      "Como la distancia máxima a la que puede viajar una sonda espacial"
    ],
    "answer": 0,
    "explanation": "Laniakea se define por la dinámica de velocidades peculiares: es el volumen del espacio donde todas las corrientes de galaxias convergen hacia el mismo centro de atracción."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad aproximada se desplaza la Vía Láctea a través del cosmos hacia el Gran Atractor?",
    "options": [
      "A más de 2,2 millones de km/h (unos ~627 km/s respecto a la radiación de fondo CMB)",
      "A 100 km/h como un automóvil",
      "A 300.000 km/s a la velocidad de la luz",
      "La Vía Láctea permanece completamente inmóvil en el espacio absoluto"
    ],
    "answer": 0,
    "explanation": "El análisis del dipolo de la radiación cósmica de fondo de microondas (CMB) demuestra que nuestro grupo galáctico viaja a ~627 km/s arrastrado por el Gran Atractor y Shapley."
  },
  {
    "type": "choice",
    "question": "¿Qué representan los gigantescos \"Vacíos Cósmicos\" (Cosmic Voids) en la telaraña del universo?",
    "options": [
      "Inmensos desiertos espaciales de hasta 150 millones de años luz de diámetro donde la densidad de galaxias y gas es prácticamente nula",
      "Agujeros negros que se han tragado a todas las estrellas",
      "Zonas donde las leyes de la física se apagan",
      "Nubes de gas inflamable"
    ],
    "answer": 0,
    "explanation": "Los vacíos cósmicos son regiones expansivas de muy baja densidad que empujan la materia hacia los filamentos y paredes de la red cósmica.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué significa el término \"Laniakea\" asignado por los astrónomos hawaianos en 2014?",
    "options": [
      "\"Cielos Inmensos\" o \"Horizonte Celestial Infinito\"",
      "\"Estrella Solitaria\"",
      "\"Remolino de Fuego\"",
      "\"Río Helado\""
    ],
    "answer": 0,
    "explanation": "En idioma hawaiano, *Lani* significa \"cielo\" y *Akea* significa \"inmenso\" o \"ilimitado\", en homenaje a los navegantes polinesios que guiaban sus canoas por las estrellas."
  },
  {
    "type": "order",
    "question": "Ordena la jerarquía de estructuras del cosmos de MENOR a MAYOR escala espacial:",
    "items": [
      "Sistema Solar (~60 UA - Nuestro vecindario planetario)",
      "La Vía Láctea (~100.000 años luz - Nuestra galaxia espiral)",
      "Grupo Local de Galaxias (~10 millones de años luz - Familia de 80 galaxias)",
      "Supercúmulo Laniakea (~520 millones de años luz - 100.000 galaxias)",
      "Universo Observable (~93.000 millones de años luz)"
    ],
    "correctOrder": [
      "Sistema Solar (~60 UA - Nuestro vecindario planetario)",
      "La Vía Láctea (~100.000 años luz - Nuestra galaxia espiral)",
      "Grupo Local de Galaxias (~10 millones de años luz - Familia de 80 galaxias)",
      "Supercúmulo Laniakea (~520 millones de años luz - 100.000 galaxias)",
      "Universo Observable (~93.000 millones de años luz)"
    ],
    "explanation": "La escalera cósmica se estructura jerárquicamente desde nuestro sistema planetario hasta el supercontinente Laniakea y el horizonte observable."
  }
]
};
