// Autogenerated by GOALS Data Pipeline from 01_earth.md
import { Lesson } from '../../types';

export const lesson01_Earth: Lesson = {
  id: 1,
  title: "La Tierra, su Atmósfera y los Satélites",
  tag: "Tema 1 • 100 km a 1.5M km • Teoría + Práctica 2026",
  icon: "🌍",
  hero: "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
  steps: [
  {
    "icon": "🌍",
    "t": "[Teoría] La Piel Protectora de la Tierra y la Línea de Kármán",
    "text": "Nuestro planeta está envuelto por una tenue capa gaseosa de apenas 100 km de altitud efectiva (Línea de Kármán). Si la Tierra fuera una manzana escolar, toda la atmósfera donde respiramos y vuelan los aviones sería más delgada que la piel de la fruta. Esta capa (78% Nitrógeno, 21% Oxígeno) nos resguarda del vacío, absorbe los rayos ultravioleta dañinos y desintegra millones de meteoroides cada día antes de que toquen el suelo.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La tenue atmósfera terrestre vista como un halo azul desde la ISS",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🛰️",
    "t": "[Teoría] La ISS y la Caída Libre a 27.600 km/h",
    "text": "A 418 km de altitud orbita la Estación Espacial Internacional (ISS). A esa altura la gravedad de la Tierra sigue siendo del **90% ($g \\approx 8,7\\text{ m/s}^2$)**. Los astronautas flotan no por falta de gravedad, sino porque están en **caída libre continua** a $27.600\\text{ km/h}$: la estación cae constantemente hacia la Tierra al mismo ritmo exacto en que la curvatura del planeta se aleja bajo ella.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estación Espacial Internacional en órbita con sus paneles solares dorados",
      "url": "https://images-assets.nasa.gov/image/PIA00118/PIA00118~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Centinelas del Clima: Landsat 9 y la Órbita Polar",
    "text": "A 705 km de altitud, satélites como Landsat 9 recorren una órbita polar heliosíncrona cruzando los polos mientras la Tierra gira debajo. Sus sensores multiespectrales (OLI-2 y TIRS-2) miden en infrarrojo la salud de los bosques, el nivel de los glaciares y el agua en los campos de cultivo del mundo entero.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Imagen multiespectral de deltas y glaciares captada por Landsat 9",
      "url": "https://images-assets.nasa.gov/image/GSFC_20211105_Landsat9_FirstImages/GSFC_20211105_Landsat9_FirstImages~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "[Teoría] El Telescopio Hubble: Mirar sin la Turbulencia del Aire",
    "text": "A 535 km de altura orbita el Telescopio Espacial Hubble. Mirar el espacio desde el suelo es como leer un libro desde el fondo de una piscina; al situarse por encima del 99% de la atmósfera, el Hubble obtiene imágenes ultra-nítidas en luz visible y ultravioleta sin turbulencia atmosférica.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Telescopio Espacial Hubble capturado durante una misión de mantenimiento",
      "url": "https://images-assets.nasa.gov/image/potw1343a/potw1343a~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "[Práctica 2026] James Webb en Lagrange L2: El Ojo a 1,5 Millones de km",
    "text": "Para observar la débil radiación infrarroja de las primeras estrellas y galaxias nacidas tras el Big Bang, el Telescopio Espacial James Webb (JWST) no orbita la Tierra, sino que se sitúa a 1,5 millones de kilómetros en el punto de equilibrio gravitatorio Lagrange L2, protegido por un parasol de 5 capas que lo mantiene a $-233\\text{ }^\\circ\\text{C}$.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Telescopio Espacial James Webb desplegado en el punto de Lagrange L2",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Por qué los astronautas flotan dentro de la Estación Espacial Internacional (ISS) a 418 km de altitud?",
    "options": [
      "Porque la ISS y los astronautas están en caída libre continua alrededor de la Tierra a ~27.600 km/h",
      "Porque a 418 km de altura la gravedad de la Tierra desaparece por completo (g = 0)",
      "Porque unos propulsores magnéticos empujan a los astronautas hacia el techo",
      "Porque la falta de aire anula todas las fuerzas del universo"
    ],
    "answer": 0,
    "explanation": "A 418 km de altitud, la gravedad terrestre conserva casi el 90% de su fuerza. La ingravidez se produce porque la estación cae hacia la Tierra a la misma velocidad que la superficie se curva."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la composición química dominante de la atmósfera terrestre?",
    "options": [
      "78% Nitrógeno (N2) y 21% Oxígeno (O2)",
      "50% Oxígeno y 50% Dióxido de Carbono",
      "90% Hidrógeno y 10% Helio",
      "95% Dióxido de Carbono como en Marte"
    ],
    "answer": 0,
    "explanation": "La atmósfera terrestre es una mezcla única rica en nitrógeno molecular (78%) y oxígeno libre (21%), con un 1% de argón y gases traza."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra opera el Telescopio Espacial James Webb (JWST)?",
    "options": [
      "A 1,5 millones de kilómetros (en el punto de equilibrio gravitacional Lagrange L2)",
      "A 100 km sobre el nivel del mar en la Línea de Kármán",
      "En la superficie de la Luna a 384.400 km",
      "A 1 año luz de distancia en el espacio interestelar"
    ],
    "answer": 0,
    "explanation": "El JWST orbita el punto Lagrange L2 a 1,5 millones de kilómetros, donde las fuerzas gravitatorias del Sol y la Tierra se equilibran para mantenerlo sincronizado con nuestro planeta.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Por qué el telescopio Hubble obtiene imágenes mucho más nítidas que los telescopios terrestres?",
    "options": [
      "Porque a 535 km de altitud no sufre la turbulencia ni la absorción de luz de la atmósfera terrestre",
      "Porque utiliza lentes mágicas que no existen en la superficie",
      "Porque está 1.000 veces más cerca de las estrellas lejanas",
      "Porque en el espacio la luz viaja al doble de velocidad"
    ],
    "answer": 0,
    "explanation": "La turbulencia atmosférica hace que la luz titile y se distorsione. Al estar en el vacío orbital a 535 km, el Hubble capta frentes de onda de luz prístinos."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes altitudes desde la superficie terrestre hacia el espacio profundo:",
    "items": [
      "Línea de Kármán (100 km - Frontera oficial del espacio)",
      "Estación Espacial Internacional / ISS (418 km - Órbita baja)",
      "Telescopio Espacial Hubble (535 km - Órbita baja limpia)",
      "Satélite de Observación Landsat 9 (705 km - Órbita heliosíncrona)",
      "Telescopio Espacial James Webb (1.500.000 km - Punto Lagrange L2)"
    ],
    "correctOrder": [
      "Línea de Kármán (100 km - Frontera oficial del espacio)",
      "Estación Espacial Internacional / ISS (418 km - Órbita baja)",
      "Telescopio Espacial Hubble (535 km - Órbita baja limpia)",
      "Satélite de Observación Landsat 9 (705 km - Órbita heliosíncrona)",
      "Telescopio Espacial James Webb (1.500.000 km - Punto Lagrange L2)"
    ],
    "explanation": "La escala orbital humana progresa desde la atmósfera superior (100 km) y la órbita baja tripulada (ISS y Hubble) hasta satélites de recursos terrestres y observatorios en L2."
  }
]
};
