// Autogenerated by GOALS Data Pipeline from 08_nearbystars.md
import { Lesson } from '../../types';

export const lesson08_Nearbystars: Lesson = {
  id: 8,
  title: "Estrellas Vecinas y Alfa Centauri",
  tag: "Tema 8 • 4,2 a 11 Años Luz • Teoría + Práctica 2026",
  icon: "✨",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Año Luz y la Máquina del Tiempo Cósmica",
    "text": "En el espacio interestelar las distancias en kilómetros se vuelven astronómicamente inmanejables. Se utiliza el **Año Luz (al)**: la distancia que recorre un fotón de luz en el vacío durante un año terrestre a $300.000\\text{ km/s}$:\n$$1\\text{ Año Luz} = 299.792\\text{ km/s} \\times 31.557.600\\text{ s} \\approx 9,46\\text{ billones de km} = 63.241\\text{ UA}$$\nMirar el cielo nocturno es mirar directamente hacia el pasado: la luz de la estrella más cercana, **Próxima Centauri (a 4,24 al)**, salió de allí hace 4 años y 3 meses para llegar hoy a tus retinas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El sistema estelar triple Alfa Centauri captado en el cielo austral",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] El Sistema Triple de Alfa Centauri",
    "text": "A solo 4,37 años luz se encuentra el sistema de **Alfa Centauri**, compuesto por tres soles ligados gravitacionalmente:\n1. **Alfa Centauri A (Rigil Kentaurus)**: Enana amarilla de tipo espectral G2V, un 10% más masiva y brillante que nuestro Sol.\n2. **Alfa Centauri B (Toliman)**: Enana naranja de tipo K1V, un 10% más pequeña que el Sol. Giran entre sí cada 80 años.\n3. **Próxima Centauri**: Pequeña enana roja de tipo M5.5V que orbita a la pareja principal a gran distancia (a 4,24 al del Sol).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Diagrama orbital del sistema triple de Alfa Centauri y Próxima",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] El Exoplaneta Rocoso Próxima b",
    "text": "En 2016, el telescopio VLT de Chile descubrió **Próxima b**, un exoplaneta terrestre con una masa mínima de $1,17\\text{ masas terrestres}$ que orbita a solo 7,5 millones de kilómetros de Próxima Centauri en su **Zona de Habitabilidad**, donde la temperatura permitiría la existencia de agua líquida en su superficie.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Recreación artística de la superficie rocosa del exoplaneta Próxima b",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] El Vecindario Solar en 10 Años Luz",
    "text": "En un radio de 10 años luz alrededor del Sol se encuentran mundos estelares fascinantes:\n- **Estrella de Barnard (5,96 al)**: Enana roja con la mayor velocidad propia del cielo nocturno.\n- **Luhman 16 (6,51 al)**: Pareja binaria de enanas marrones (estrellas fallidas que no lograron encender la fusión de hidrógeno).\n- **Sirio A y B (8,60 al)**: La estrella más brillante del firmamento nocturno, acompañada de una enana blanca del tamaño de la Tierra pero con la masa del Sol.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Sirio A y su diminuta enana blanca Sirio B fotografiada por el Hubble",
      "url": "https://images-assets.nasa.gov/image/potw1343a/potw1343a~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] Veleros Interestelares y Nanocámaras",
    "text": "En 2026, la iniciativa **Breakthrough Starshot** prueba en laboratorio microchips de 1 gramo dotados de cámaras, procesadores y fuentes de energía nuclear beta-voltaica acoplados a velas reflectoras de grafeno de 4 metros. Impulsados por un arreglo láser de $100\\text{ GW}$ desde la Tierra, alcanzarán el **20% de la velocidad de la luz ($60.000\\text{ km/s}$)**, llegando a Próxima Centauri en poco más de 20 años de travesía.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Concepto de nanocápsula interestelar con vela fotónica láser",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "Si desde una colonia en el exoplaneta Próxima b (a 4,24 años luz) transmiten un mensaje de radio hacia la Tierra y se responde de inmediato, ¿cuánto tiempo total transcurre hasta que reciben la respuesta?",
    "options": [
      "8,48 años terrestres (4,24 años de ida + 4,24 años de viaje de vuelta a la velocidad de la luz c)",
      "4,24 años exactos",
      "11,2 días (el periodo de rotación orbital)",
      "La señal llega de forma instantánea mediante entrelazamiento"
    ],
    "answer": 0,
    "explanation": "Como las ondas de radio viajan a la velocidad de la luz ($c$), tardan 4,24 años en viajar de ida y otros 4,24 años en regresar a la Tierra, sumando un retardo total de 8,48 años."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la estrella individual físicamente más cercana a nuestro Sol en el espacio?",
    "options": [
      "Próxima Centauri (a 4,24 años luz, una enana roja del sistema Alfa Centauri)",
      "Sirio A (a 8,60 años luz)",
      "La Estrella Polar / Polaris (a más de 400 años luz)",
      "Betelgeuse (a 640 años luz)"
    ],
    "answer": 0,
    "explanation": "Aunque Alfa Centauri A y B son más brillantes, la pequeña enana roja Próxima Centauri se encuentra ligeramente más próxima a nosotros en su órbita alrededor de ellas."
  },
  {
    "type": "choice",
    "question": "¿Por qué el exoplaneta Próxima b despierta tanto interés en la astrobiología actual?",
    "options": [
      "Porque es un planeta rocoso de tamaño similar a la Tierra situado en la zona de habitabilidad de su estrella",
      "Porque tiene ciudades iluminadas visibles con telescopio",
      "Porque está compuesto enteramente por oro líquido",
      "Porque no tiene gravedad y se puede volar en su atmósfera"
    ],
    "answer": 0,
    "explanation": "Próxima b orbita a la distancia precisa de su estrella para que, con una atmósfera adecuada, el agua pueda existir en estado líquido en su corteza.",
    "photo": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué es un Año Luz en la física astronómica?",
    "options": [
      "Una unidad de DISTANCIA que equivale al trayecto recorrido por la luz en el vacío durante un año (~9,46 billones de km)",
      "Una unidad de tiempo que dura 365 días bisiestos",
      "La cantidad de luz que emite el Sol durante el verano",
      "La velocidad a la que giran los agujeros negros"
    ],
    "answer": 0,
    "explanation": "El año luz mide distancia geométrica en el cosmos, calculada multiplicando la velocidad de la luz ($300.000\\text{ km/s}$) por los segundos que contiene un año."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes astros por su distancia real desde nuestro Sol (del más cercano al más lejano):",
    "items": [
      "Próxima Centauri (4,24 años luz - Enana roja vecina)",
      "Par estelar Alfa Centauri A y B (4,37 años luz)",
      "Estrella de Barnard (5,96 años luz)",
      "Luhman 16 (6,51 años luz - Sistema binario de enanas marrones)",
      "Sistema Sirio A y la enana blanca Sirio B (8,60 años luz)"
    ],
    "correctOrder": [
      "Próxima Centauri (4,24 años luz - Enana roja vecina)",
      "Par estelar Alfa Centauri A y B (4,37 años luz)",
      "Estrella de Barnard (5,96 años luz)",
      "Luhman 16 (6,51 años luz - Sistema binario de enanas marrones)",
      "Sistema Sirio A y la enana blanca Sirio B (8,60 años luz)"
    ],
    "explanation": "El vecindario estelar solar inmediato progresa desde el sistema triple Centauri hasta Barnard, Luhman y la brillante estrella Sirio."
  }
]
};
