// Autogenerated by GOALS Data Pipeline from 05_estaciones_del_ano_y_oblicuidad_axial_23_44.md
import { Lesson } from '../../types';

export const lesson05_Estaciones_del_ano_y_oblicuidad_axial_23_44: Lesson = {
  id: 5,
  title: "Estaciones del Año y Oblicuidad Axial (23.44°)",
  tag: "Tema 5/12 • 23,44° Oblicuidad • Insolación W/m²",
  icon: "☀️",
  hero: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. La Oblicuidad Axial Inercial de 23,44°",
    "text": "El eje de rotación de la Tierra está inclinado 23,44° respecto a la perpendicular de su órbita. Esta inclinación se mantiene fija en el espacio apuntando hacia Polaris. A medida que la Tierra se traslada, los hemisferios Norte y Sur reciben luz solar directa en periodos alternos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra en el espacio con su inclinación axial de 23,44°.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "2. Solsticios y Equinoccios",
    "text": "En el Solsticio de Junio (21 junio), los rayos solares caen perpendiculares sobre el Trópico de Cáncer (23,5° N), dando el día más largo en el norte. En el Solsticio de Diciembre (21 diciembre), caen en Capricornio (23,5° S). En los Equinoccios (marzo y septiembre), el Sol está en el cenit ecuatorial y el día dura 12h exactas en todo el planeta.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mosaico estacional de la vegetación terrestre desde el espacio.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "3. Flujo de Energía e Insolación Solar (W/m²)",
    "text": "La constante solar en lo alto de la atmósfera es de 1.361 W/m². La energía que calienta el suelo sigue la ley del coseno de Lambert: rayos perpendiculares a 90° concentran calor en un área pequeña; rayos oblicuos a 30° reparten la misma energía en el doble de superficie, calentando mucho menos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Radiación térmica solar y balance energético terrestre.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. Simetría Inversa entre Hemisferios",
    "text": "Los hemisferios Norte y Sur experimentan estaciones invertidas. Cuando en Europa es el solsticio de verano con 15 horas de sol, en Argentina, Chile y Australia es el solsticio de invierno con 15 horas de noche. En el ecuador, día y noche duran 12 horas invariables todo el año.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Vista del hemisferio sur y la Antártida tomada por la sonda Galileo.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuál es la causa física fundamental de que existan las 4 estaciones del año en la Tierra?",
    "options": [
      "La inclinación fija de 23,44° del eje de rotación terrestre",
      "La variación de distancia al Sol entre Perihelio y Afelio",
      "Los cambios en la actividad magnética solar",
      "La rotación de la Luna alrededor de la Tierra"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Sobre qué paralelo geográfico caen perpendiculares (90°) los rayos del Sol durante el Solsticio de Junio?",
    "options": [
      "Trópico de Cáncer (23,44° Norte)",
      "Ecuador terrestre (0°)",
      "Trópico de Capricornio (23,44° Sur)",
      "Círculo Polar Ártico (66,5° Norte)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las estaciones del hemisferio norte empezando por el 21 de marzo:",
    "items": [
      "Primavera (Equinoccio de Marzo)",
      "Verano (Solsticio de Junio)",
      "Otoño (Equinoccio de Septiembre)",
      "Invierno (Solsticio de Diciembre)"
    ],
    "correctOrder": [
      "Primavera (Equinoccio de Marzo)",
      "Verano (Solsticio de Junio)",
      "Otoño (Equinoccio de Septiembre)",
      "Invierno (Solsticio de Diciembre)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si en Madrid (España) es el 21 de diciembre (Solsticio de Invierno), ¿qué estación comienza ese mismo día en Buenos Aires (Argentina)?",
    "options": [
      "Verano (Solsticio de Verano austral)",
      "Invierno austral",
      "Otoño austral",
      "Primavera austral"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
