// Autogenerated by GOALS Data Pipeline from 03_mars.md
import { Lesson } from '../../types';

export const lesson03_Mars: Lesson = {
  id: 3,
  title: "Marte y la Exploración Planetaria",
  tag: "Tema 3 • 227.9M km • Teoría + Práctica 2026",
  icon: "🔴",
  hero: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Desierto Rojo, la Hematita y la Gravedad",
    "text": "Marte es el cuarto planeta del Sistema Solar. Aunque desde la Tierra lo vemos como un punto rojizo brillante, su tonalidad procede de una fina capa de **óxido de hierro (III)** o hematita mineral que cubre su regolito basáltico. Su gravedad superficial es de **$3,72\\text{ m/s}^2$** (aproximadamente el 38% de la gravedad terrestre), permitiendo que un objeto pese menos de la mitad que en nuestro planeta.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Superficie global de Marte con casquetes polares",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Atmósfera de $CO_2$ y Relieve Titánico",
    "text": "La presión en la superficie marciana es de solo **6,1 milibares** (menos del 1% de la presión de la Tierra al nivel del mar), compuesta en un **95,3% por Dióxido de Carbono ($CO_2$)**. Su relieve alberga el **Monte Olimpo** ($21,9\\text{ km}$ de altura, el volcán en escudo más alto del Sistema Solar) y el cañón tectónico **Valles Marineris** ($4.000\\text{ km}$ de longitud y hasta $7\\text{ km}$ de profundidad).",
    "wow": "",
    "scene": "space_default"
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] Noticias Reales y Muestras de Roca de Perseverance",
    "text": "En 2026, la exploración marciana vive un momento histórico: el rover **Perseverance** de la NASA ha finalizado la recolección y sellado de 24 tubos de núcleos de roca en el delta fluvial fósil del cráter Jezero. La misión conjunta **Mars Sample Return (NASA / ESA)** prepara la arquitectura para traer por primera vez estas muestras a laboratorios terrestres.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Rocas sedimentarias del delta fluvial captadas por el rover Perseverance en el cráter Jezero",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Por qué la superficie de Marte tiene su característico color rojizo?",
    "options": [
      "Por la abundancia de óxido de hierro (III) o hematita en su polvo superficial",
      "Por la combustión continua de gases volcánicos",
      "Por la radiación solar directa que quema las rocas",
      "Por la presencia de océanos de azufre líquido"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuál es el gas predominante en más del 95% de la atmósfera marciana?",
    "options": [
      "Dióxido de Carbono ($CO_2$)",
      "Oxígeno molecular ($O_2$)",
      "Nitrógeno ($N_2$)",
      "Helio ($He$)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "Si una astronauta tiene una masa de 60 kg en la Tierra, ¿cuál es su masa y peso aproximado en Marte (g = 3,72 m/s²)?",
    "options": [
      "Su masa sigue siendo 60 kg invariable y su peso es ~223 Newtons",
      "Su masa se reduce a 22 kg y su peso a 0 Newtons",
      "Su masa aumenta a 120 kg",
      "La masa y el peso son siempre cero en el espacio"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena los siguientes relieves geológicos según su altitud o longitud de MENOR a MAYOR:",
    "items": [
      "Monte Everest en la Tierra (~8,8 km de altitud)",
      "Monte Olimpo en Marte (~21,9 km de altitud)",
      "Gran Cañón del Colorado en la Tierra (~446 km de longitud)",
      "Valles Marineris en Marte (~4.000 km de longitud)"
    ],
    "correctOrder": [
      "Monte Everest en la Tierra (~8,8 km de altitud)",
      "Monte Olimpo en Marte (~21,9 km de altitud)",
      "Gran Cañón del Colorado en la Tierra (~446 km de longitud)",
      "Valles Marineris en Marte (~4.000 km de longitud)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
