// Autogenerated by GOALS Data Pipeline from 06_el_sistema_solar_los_8_planetas_y_asteroides.md
import { Lesson } from '../../types';

export const lesson06_El_sistema_solar_los_8_planetas_y_asteroides: Lesson = {
  id: 6,
  title: "El Sistema Solar, los 8 Planetas y Asteroides",
  tag: "Tema 6/12 • 60 UA • De Mercurio a Neptuno",
  icon: "🪐",
  hero: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "☀️",
    "t": "1. El Sol Soberano y la Masa del Sistema",
    "text": "El Sol concentra el 99,86% de toda la masa del Sistema Solar. En su núcleo a 15 millones de °C, fusiona 600 millones de toneladas de hidrógeno en helio cada segundo. Su diámetro de 1.392.700 km equivale a 109 Tierras alineadas, dominando gravitatoriamente todos los planetas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Erupción de llamaradas y plasma en la corona solar capturada por el SDO.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. Los 4 Planetas Rocosos Interiores",
    "text": "Cerca del Sol orbitan los planetas telúricos de roca y metales: Mercurio (cráteres y temperaturas de -180 °C a 430 °C), Venus (atmósfera de CO₂ a 465 °C y 92 atm), la Tierra (agua y vida) y Marte (desiertos de óxido de hierro y el volcán Monte Olimpo de 21 km).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El planeta rojo Marte fotografiado por el Telescopio Espacial Hubble.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. El Cinturón Principal de Asteroides",
    "text": "Entre 2,2 y 3,2 UA (entre Marte y Júpiter), el Cinturón Principal alberga millones de rocas y metales sobrantes de la formación planetaria. Destacan el planeta enano Ceres (940 km de diámetro) y los asteroides gigantes Vesta, Pallas e Higía.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El asteroide gigante Vesta fotografiado por la nave Dawn.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. Los 4 Gigantes Exteriores: Gas y Hielo",
    "text": "Más allá de la línea de congelación reinan los gigantes: Júpiter (318 masas terrestres y lunas como Europa y Ganímedes), Saturno (anillos de hielo de 280.000 km), Urano (gigante helado con un eje inclinado 98° que rueda sobre su órbita) y Neptuno (vientos de 2.100 km/h).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Saturno y sus anillos fotografiados a contraluz por la nave Cassini.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué porcentaje de toda la masa del Sistema Solar concentra el Sol en su interior?",
    "options": [
      "El 99,86%",
      "El 50%",
      "El 80%",
      "El 10%"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena los 8 planetas del Sistema Solar por su distancia creciente desde el Sol:",
    "items": [
      "Mercurio",
      "Venus",
      "Tierra",
      "Marte",
      "Júpiter",
      "Saturno",
      "Urano",
      "Neptuno"
    ],
    "correctOrder": [
      "Mercurio",
      "Venus",
      "Tierra",
      "Marte",
      "Júpiter",
      "Saturno",
      "Urano",
      "Neptuno"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Por qué Venus tiene una temperatura de 465 °C mayor que la de Mercurio?",
    "options": [
      "Por un desbocado efecto invernadero provocado por su densa atmósfera de CO₂",
      "Porque tiene erupciones volcánicas continuas que calientan la roca",
      "Porque está más cerca del Sol que Mercurio",
      "Porque no tiene noche"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Entre qué dos planetas se sitúa el Cinturón Principal de Asteroides?",
    "options": [
      "Entre Marte y Júpiter",
      "Entre la Tierra y Marte",
      "Entre Júpiter y Saturno",
      "Más allá de Neptuno"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
