// Autogenerated by GOALS Data Pipeline from 10_el_grupo_local_de_galaxias_y_andromeda_m31.md
import { Lesson } from '../../types';

export const lesson10_El_grupo_local_de_galaxias_y_andromeda_m31: Lesson = {
  id: 10,
  title: "El Grupo Local de Galaxias y Andrómeda (M31)",
  tag: "Tema 10/12 • 10 Millones al • Nuestro Cúmulo",
  icon: "🌌",
  hero: "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "🌌",
    "t": "1. El Grupo Local: Un Archipiélago de 80 Galaxias",
    "text": "Nuestra galaxia no está aislada: forma parte del Grupo Local, un cúmulo de 10 millones de años luz de diámetro ligado por gravedad. Contiene más de 80 galaxias, dominado por dos gigantes espirales (Andrómeda y la Vía Láctea), una espiral mediana (Triángulo M33) y decenas de galaxias enanas satélites.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La majestuosa Galaxia de Andrómeda (M31) con sus brazos espirales de polvo.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌌",
    "t": "2. La Galaxia de Andrómeda (M31)",
    "text": "Situada a 2,5 millones de años luz, Andrómeda (M31) es el objeto visible a simple vista más lejano en el cielo nocturno. Posee un diámetro de 220.000 años luz y contiene un billón (10¹²) de estrellas, con un agujero negro central supermasivo de 100 millones de masas solares.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Detalle de estrellas y cúmulos en el disco de Andrómeda por el Hubble.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌌",
    "t": "3. La Galaxia del Triángulo (M33) y las Nubes de Magallanes",
    "text": "A 2,7 millones de años luz brilla la Galaxia del Triángulo (M33), la tercera mayor del grupo con 40.000 millones de estrellas. Orbitando a la Vía Láctea se hallan la Gran y Pequeña Nube de Magallanes, dos galaxias enanas irregulares visibles desde el hemisferio sur.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Galaxia del Triángulo (M33) mostrando sus cúmulos azules de estrellas jóvenes.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. La Gran Colisión Cósmica: Milkomeda",
    "text": "Andrómeda y la Vía Láctea se aproximan a 110 km/s (400.000 km/h). En unos 4.500 millones de años colisionarán frontalmente, fusionándose en una galaxia elíptica gigante bautizada como 'Lactómeda' o 'Milkomeda'. El Sistema Solar sobrevivirá pero será lanzado a una nueva órbita exterior.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Simulación de la colisión y fusión de dos galaxias espirales gigantes.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuáles son las dos galaxias más grandes que dominan el Grupo Local?",
    "options": [
      "La Galaxia de Andrómeda (M31) y la Vía Láctea",
      "La Vía Láctea y la Galaxia del Triángulo",
      "Andrómeda y la Gran Nube de Magallanes",
      "Centaurus A y M87"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra se encuentra la Galaxia de Andrómeda (M31)?",
    "options": [
      "A unos 2,5 millones de años luz",
      "A 4,24 años luz",
      "A 100.000 años luz",
      "A 150 millones de kilómetros"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes galaxias de nuestro entorno desde la MÁS CERCANA a la Tierra hasta la MÁS LEJANA:",
    "items": [
      "Gran Nube de Magallanes (163.000 al)",
      "Galaxia de Andrómeda M31 (2,5 millones al)",
      "Galaxia del Triángulo M33 (2,7 millones al)",
      "Galaxia del Remolino M51 (23 millones al)"
    ],
    "correctOrder": [
      "Gran Nube de Magallanes (163.000 al)",
      "Galaxia de Andrómeda M31 (2,5 millones al)",
      "Galaxia del Triángulo M33 (2,7 millones al)",
      "Galaxia del Remolino M51 (23 millones al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué ocurrirá dentro de unos 4.500 millones de años entre la Vía Láctea y la Galaxia de Andrómeda?",
    "options": [
      "Colisionarán y se fusionarán formando una galaxia elíptica gigante (Milkomeda)",
      "Se alejarán para siempre debido a la energía oscura",
      "Andrómeda devorará a la Vía Láctea sin dejar rastro",
      "Explotarán destruyendo todas las estrellas"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
