// Autogenerated by GOALS Data Pipeline from 03_daynight.md
import { Lesson } from '../../types';

export const lesson03_Daynight: Lesson = {
  id: 3,
  title: "Rotación Terrestre y Husos Horarios",
  tag: "Tema 3 • 12.742 km • Teoría + Práctica 2026",
  icon: "⏳",
  hero: "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Gran Tiovivo Planetario a 1.670 km/h en el Ecuador",
    "text": "La Tierra gira de Oeste a Este alrededor de su eje polar imaginario. En la línea del ecuador nos desplazamos a **1.670 km/h (464 m/s)** sin sentirlo, porque la atmósfera, los océanos y todo lo que nos rodea viaja solidariamente a la misma velocidad inercial constante. A medida que nos acercamos a los polos, la velocidad lineal disminuye hasta ser de $0\\text{ km/h}$ en el propio polo geográfico.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Luces nocturnas de las ciudades terrestres y el terminador solar captados por satélite",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] Día Sidéreo (23h 56m 4s) vs Día Solar (24h)",
    "text": "Un giro exacto de $360^\\circ$ de la Tierra respecto a las estrellas lejanas tarda **23 horas, 56 minutos y 4 segundos** (Día Sidéreo). Sin embargo, como la Tierra avanza simultáneamente en su órbita alrededor del Sol, nuestro planeta debe rotar aproximadamente **$0,986^\\circ$ extra (unos 4 minutos adicionales)** cada jornada para volver a encarar al Sol en el cenit del mediodía, completando las 24 horas del Día Solar.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Diagrama explicativo del ángulo adicional entre el día sidéreo y el día solar",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] El Terminador Solar y las Fases de Crepúsculo",
    "text": "La línea que separa el hemisferio iluminado por el Sol del hemisferio nocturno se llama **Terminador Solar**. Debido a que la atmósfera terrestre dispersa la luz solar como un prisma (dispersión Rayleigh), la transición a la noche no es instantánea, sino que atraviesa tres fases crepusculares:\n1. **Crepúsculo Civil**: Sol entre 0° y 6° bajo el horizonte; hay luz suficiente para actividades sin farolas.\n2. **Crepúsculo Náutico**: Sol entre 6° y 12° bajo el horizonte; se distinguen las estrellas guía en el mar.\n3. **Crepúsculo Astronómico**: Sol entre 12° y 18° bajo el horizonte; finaliza la penumbra y comienza la noche cósmica pura.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El terminador solar cruzando el océano Atlántico visto desde la cúpula de la ISS",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Husos Horarios, Longitud y la Red UTC",
    "text": "Como la Tierra tiene $360^\\circ$ de circunferencia y tarda 24 horas en dar una vuelta completa, cada hora de tiempo solar corresponde exactamente a:\n$$\\frac{360^\\circ}{24\\text{ horas}} = 15^\\circ\\text{ de longitud}$$\nEl planeta está dividido en 24 husos horarios referenciados al meridiano cero de Greenwich (UTC). Al viajar hacia el Este sumamos horas, y al viajar hacia el Oeste restamos horas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Red mundial de husos horarios y ciudades iluminadas",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] El Efecto Coriolis y los Huracanes",
    "text": "Al girar la Tierra bajo la atmósfera, cualquier fluido en movimiento libre (como vientos o corrientes oceánicas) sufre una desviación aparente conocida como **Efecto Coriolis**:\n- En el **Hemisferio Norte**, los vientos se desvían hacia la **derecha** (los huracanes giran en sentido antihorario).\n- En el **Hemisferio Sur**, los vientos se desvían hacia la **izquierda** (los ciclones giran en sentido horario).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estructura espiral de un gran ciclón fotografiado desde la órbita",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "Si la Tierra realiza un giro de 360° en 23 horas y 56 minutos (día sidéreo), ¿por qué nuestro día cotidiano dura 24 horas?",
    "options": [
      "Porque al avanzar en su órbita alrededor del Sol debe rotar ~1° adicional (~4 minutos) para volver a encarar al Sol en el mediodía",
      "Porque la fricción del aire frena el planeta exactamente 4 minutos al día",
      "Porque los relojes atómicos internacionales se adelantan artificialmente",
      "Porque el eje de rotación de la Tierra se invierte cada noche"
    ],
    "answer": 0,
    "explanation": "El avance de la Tierra a lo largo de su órbita hace que la dirección hacia el Sol cambie en ~1° diario, requiriendo 4 minutos extra de giro para alinear de nuevo el mediodía solar."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad tangencial aproximada se mueve la superficie de la Tierra en la línea del ecuador?",
    "options": [
      "A unos 1.670 km/h (464 m/s)",
      "A 100 km/h como un coche en autopista",
      "A 300.000 km/s a la velocidad de la luz",
      "Está inmóvil sin rotación"
    ],
    "answer": 0,
    "explanation": "Dividiendo los 40.075 km de circunferencia ecuatorial entre las 24 horas del día se obtiene una velocidad superficial de aproximadamente 1.670 km/h."
  },
  {
    "type": "choice",
    "question": "¿Cuántos grados de longitud geográfica abarca cada uno de los 24 husos horarios del mundo?",
    "options": [
      "15° de longitud ($360^\\circ / 24\\text{ h}$)",
      "90° de longitud",
      "1° de longitud",
      "45° de longitud"
    ],
    "answer": 0,
    "explanation": "La esfera terrestre de 360° dividida equitativamente entre las 24 horas del día da como resultado exactamente 15° de longitud por cada franja horaria."
  },
  {
    "type": "choice",
    "question": "¿En qué sentido giran los huracanes en el Hemisferio Norte debido al Efecto Coriolis?",
    "options": [
      "En sentido antihorario (contrario a las agujas del reloj) por la desviación hacia la derecha",
      "En sentido horario (a favor de las agujas del reloj)",
      "En línea recta sin formar espirales",
      "De abajo hacia arriba verticalmente"
    ],
    "answer": 0,
    "explanation": "La rotación terrestre desvía el aire hacia la derecha en el Hemisferio Norte, haciendo que el flujo hacia el centro de bajas presiones adquiera giro antihorario.",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "order",
    "question": "Ordena la progresión de la iluminación durante la puesta de Sol hasta la noche cósmica:",
    "items": [
      "Puesta de Sol aparente (El disco solar cruza el horizonte geométrico a 0°)",
      "Crepúsculo Civil (El Sol se sitúa entre 0° y 6° bajo el horizonte)",
      "Crepúsculo Náutico (El Sol se sitúa entre 6° y 12° bajo el horizonte)",
      "Crepúsculo Astronómico (El Sol se sitúa entre 12° y 18° bajo el horizonte)",
      "Noche Cósmica Cerrada (El Sol desciende a más de 18° bajo el horizonte)"
    ],
    "correctOrder": [
      "Puesta de Sol aparente (El disco solar cruza el horizonte geométrico a 0°)",
      "Crepúsculo Civil (El Sol se sitúa entre 0° y 6° bajo el horizonte)",
      "Crepúsculo Náutico (El Sol se sitúa entre 6° y 12° bajo el horizonte)",
      "Crepúsculo Astronómico (El Sol se sitúa entre 12° y 18° bajo el horizonte)",
      "Noche Cósmica Cerrada (El Sol desciende a más de 18° bajo el horizonte)"
    ],
    "explanation": "El crepúsculo se divide astronómicamente según el ángulo del Sol bajo el horizonte, pasando por civil, náutico y astronómico antes de la oscuridad total."
  }
]
};
