// Autogenerated by GOALS Data Pipeline from 12_el_universo_observable_el_cmb_y_los_origenes_cosmicos.md
import { Lesson } from '../../types';

export const lesson12_El_universo_observable_el_cmb_y_los_origenes_cosmicos: Lesson = {
  id: 12,
  title: "El Universo Observable, el CMB y los Orígenes Cósmicos",
  tag: "Tema 12/12 • 93.000 Millones al • El Horizonte Cósmico",
  icon: "🌐",
  hero: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "🌌",
    "t": "1. El Horizonte del Universo Observable",
    "text": "Solo podemos ver la porción del cosmos cuya luz ha tenido tiempo de alcanzarnos desde el Big Bang: una esfera centrada en nosotros de 93.000 millones de años luz de diámetro (46.500 millones de al de radio comóvil), con un estimado de 2 billones (2×10¹²) de galaxias.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Campo ultra-profundo con miles de galaxias primitivas.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. El Fondo Cósmico de Microondas (CMB)",
    "text": "Emitido 380.000 años después del Big Bang, el Fondo Cósmico de Microondas (CMB) es el 'eco' fósil del nacimiento del universo. La radiación primigenia se ha enfriado por la expansión del espacio hasta los 2,725 Kelvin (-270,42 °C), mostrando ínfimas fluctuaciones térmicas (1 parte en 100.000).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mapa térmico de anisotropías del Fondo Cósmico de Microondas (CMB).",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌌",
    "t": "3. El Universo Oscuro: 95% de Enigma",
    "text": "La materia ordinaria (estrellas, planetas, gas y tú) constituye apenas el 4,9% del cosmos. El 26,8% es Materia Oscura (que genera gravedad pero no emite luz) y el 68,3% es Energía Oscura, una fuerza repulsiva inherente al vacío que acelera la expansión del universo.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Lente gravitacional generada por materia oscura invisible.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. El Big Bang y el Destino Cósmico",
    "text": "Hace 13.800 millones de años, todo el espacio, tiempo y energía emergieron de una singularidad extremadamente caliente y densa. Si la energía oscura sigue acelerando la expansión, el cosmos se dirige hacia la 'Muerte Térmica' o 'Big Freeze', donde todas las estrellas se extinguirán en billones de años.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Cronología de la expansión del Universo desde la era inflacionaria hasta el presente.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué diámetro aproximado tiene la esfera del Universo Observable centrada en nosotros?",
    "options": [
      "93.000 millones de años luz",
      "13.800 millones de kilómetros",
      "100.000 años luz",
      "4,24 años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué porcentaje de todo el contenido del Universo corresponde a materia ordinaria (átomos, estrellas, planetas, personas)?",
    "options": [
      "Apenas un ~4,9% (el 95% restante es materia y energía oscura)",
      "El 50%",
      "El 85%",
      "El 100%"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los siguientes hitos de la historia cósmica desde el origen:",
    "items": [
      "Big Bang e Inflación Cósmica (t = 0)",
      "Emisión del Fondo Cósmico de Microondas (t = 380.000 años)",
      "Nacimiento de las Primeras Galaxias (t = 400 millones de años)",
      "Formación del Sistema Solar y la Tierra (t = 9.200 millones de años)"
    ],
    "correctOrder": [
      "Big Bang e Inflación Cósmica (t = 0)",
      "Emisión del Fondo Cósmico de Microondas (t = 380.000 años)",
      "Nacimiento de las Primeras Galaxias (t = 400 millones de años)",
      "Formación del Sistema Solar y la Tierra (t = 9.200 millones de años)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué es el Fondo Cósmico de Microondas (CMB)?",
    "options": [
      "El remanente térmico fósil emitido 380.000 años después del Big Bang enfriado a 2,725 K",
      "El sonido producido por la colisión de agujeros negros",
      "La luz reflejada por los asteroides del Sistema Solar",
      "El viento solar emitido por la corona solar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
