// Autogenerated by GOALS Data Pipeline from 07_la_nube_de_oort_y_la_sonda_interestelar_voyager_1.md
import { Lesson } from '../../types';

export const lesson07_La_nube_de_oort_y_la_sonda_interestelar_voyager_1: Lesson = {
  id: 7,
  title: "La Nube de Oort y la Sonda Interestelar Voyager 1",
  tag: "Tema 7/12 • 100.000 UA • Frontera Interestelar",
  icon: "☄️",
  hero: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. El Cinturón de Kuiper y los Mundos Helados",
    "text": "De 30 a 55 UA se extiende el Cinturón de Kuiper, un anillo de objetos helados de metano y agua. Alberga planetas enanos como Plutón (y su luna Caronte), Eris, Haumea y Makemake, junto a millones de cometas de periodo corto que tardan menos de 200 años en orbitar al Sol.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Plutón y su glaciar de nitrógeno Tombaugh Regio fotografiado por New Horizons.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. La Heliósfera y la Heliopausa",
    "text": "El viento solar a 400 km/s infla una burbuja protectora llamada Heliósfera. A unas 120 UA del Sol, este viento choca contra la presión del medio interestelar en una frontera llamada Heliopausa. Al cruzarla, termina el dominio solar y comienza el espacio interestelar.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estructura de la Heliósfera y el choque con el medio interestelar.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. La Gigantesca Nube de Oort Esférica",
    "text": "Envolviendo al Sistema Solar como un cascarón esférico colosal, de 2.000 a 100.000 UA (1,5 años luz), se extiende la Nube de Oort con billones de cometas helados. Perturbaciones gravitatorias de estrellas vecinas desvían estos cometas hacia el Sol con órbitas de miles de años.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Cometa interestelar y su cola de polvo atravesando el espacio.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌍",
    "t": "4. Voyager 1: A 1 Día-Luz de la Tierra",
    "text": "Lanzada en 1977, la sonda Voyager 1 es el artefacto humano más lejano, navegando a más de 24.500 millones de km (>163 UA) a 61.000 km/h. En su chasis lleva el Disco de Oro (Golden Record) con saludos en 55 idiomas, música de la Tierra y mapas de púlsares.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El Disco de Oro 'Golden Record' instalado en la sonda Voyager 1.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cómo se llama la frontera magnética donde el viento solar choca contra el medio interestelar?",
    "options": [
      "Heliopausa",
      "Línea de Kármán",
      "Cinturón de Kuiper",
      "Horizonte de Sucesos"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Hasta qué distancia aproximada del Sol se extiende la Nube de Oort esférica?",
    "options": [
      "Hasta unas 100.000 UA (~1,5 años luz)",
      "Hasta 30 UA",
      "Hasta 400 kilómetros",
      "Hasta 100 millones de años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes regiones del Sistema Solar desde el Sol hacia el exterior:",
    "items": [
      "Cinturón de Asteroides (2,8 UA)",
      "Cinturón de Kuiper (30 - 55 UA)",
      "Heliopausa (~120 UA)",
      "Nube de Oort Exterior (100.000 UA)"
    ],
    "correctOrder": [
      "Cinturón de Asteroides (2,8 UA)",
      "Cinturón de Kuiper (30 - 55 UA)",
      "Heliopausa (~120 UA)",
      "Nube de Oort Exterior (100.000 UA)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Qué hito histórico alcanzará la sonda espacial Voyager 1 a finales de 2026?",
    "options": [
      "Situarse a 1 día-luz de distancia de la Tierra (la señal tardará 24 horas)",
      "Regresar a la Tierra tras completar su viaje",
      "Entrar en órbita alrededor de Alfa Centauri",
      "Aterrizar en la superficie de Plutón"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
