// Autogenerated by GOALS Data Pipeline from 09_la_via_lactea_y_el_agujero_negro_sagitario_a.md
import { Lesson } from '../../types';

export const lesson09_La_via_lactea_y_el_agujero_negro_sagitario_a: Lesson = {
  id: 9,
  title: "La Vía Láctea y el Agujero Negro Sagitario A*",
  tag: "Tema 9/12 • 100.000 Años Luz • Espiral Galáctica",
  icon: "🌌",
  hero: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "☀️",
    "t": "1. La Ciudad Cósmica: 200.000 Millones de Soles",
    "text": "La Vía Láctea es una galaxia espiral barrada con un diámetro de 100.000 años luz y un espesor de 1.000 años luz. Alberga entre 200.000 y 400.000 millones de estrellas y al menos 100.000 millones de planetas, girando como un remolino gravitatorio monumental.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La banda de la Vía Láctea resplandeciendo sobre el cielo nocturno.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. Nuestra Dirección: El Brazo de Orión",
    "text": "El Sol está situado a 26.000 años luz del centro galáctico, en el espolón o Brazo de Orión, entre los brazos mayores de Perseo y Sagitario. Nuestro Sistema Solar orbita el centro de la galaxia a 220 km/s (800.000 km/h), completando un 'Año Galáctico' cada 230 millones de años.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Nebulosas de gas y formación de estrellas en los brazos espirales.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. Sagitario A*: El Monstruo del Centro Galáctico",
    "text": "En el corazón exacto de la galaxia acecha Sagitario A* (Sgr A*), un agujero negro supermasivo con una masa de 4,15 millones de soles concentrada en un radio menor que la distancia de Mercurio al Sol. En 2022, el Telescopio del Horizonte de Sucesos (EHT) tomó su primera fotografía histórica.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Primera imagen real del agujero negro supermasivo Sagitario A* en el centro de nuestra galaxia.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. El Halo Galáctico y la Materia Oscura",
    "text": "Envolviendo el disco espiral se extiende el Halo Galáctico con más de 150 cúmulos globulares de estrellas ancianas. Las estrellas de los bordes giran tan rápido que la galaxia se desintegraría si no estuviera inmersa en un inmenso halo esférico invisible de Materia Oscura.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Cúmulo globular estelar en el halo exterior de la galaxia.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué tipo de galaxia es la Vía Láctea y cuánto mide su diámetro aproximado?",
    "options": [
      "Una galaxia espiral barrada de unos 100.000 años luz de diámetro",
      "Una galaxia elíptica gigante de 1.000 años luz",
      "Una galaxia irregular sin forma definida",
      "Una nebulosa de gas de 10 años luz"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cómo se llama el objeto supermasivo situado en el centro geométrico de la Vía Láctea?",
    "options": [
      "Sagitario A* (un agujero negro supermasivo de 4,15 millones de masas solares)",
      "Betelgeuse",
      "La Nebulosa de Orión",
      "El Sol"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes estructuras desde la MÁS PEQUEÑA hasta la MÁS GRANDE:",
    "items": [
      "Sistema Solar (diámetro ~60 UA)",
      "Brazo de Orión (unos 10.000 al)",
      "Disco de la Vía Láctea (100.000 al)",
      "Halo Galáctico Exterior (300.000 al)"
    ],
    "correctOrder": [
      "Sistema Solar (diámetro ~60 UA)",
      "Brazo de Orión (unos 10.000 al)",
      "Disco de la Vía Láctea (100.000 al)",
      "Halo Galáctico Exterior (300.000 al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuánto tiempo tarda el Sol en completar una vuelta (un 'Año Galáctico') alrededor del centro de la Vía Láctea?",
    "options": [
      "Aproximadamente 230 millones de años",
      "365 días",
      "10.000 años",
      "13.800 millones de años"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
