// Autogenerated by GOALS Data Pipeline from 01_la_tierra_su_atmosfera_y_satelites.md
import { Lesson } from '../../types';

export const lesson01_La_tierra_su_atmosfera_y_satelites: Lesson = {
  id: 1,
  title: "La Tierra, su Atmósfera y Satélites",
  tag: "Tema 1/12 • 12.742 km • Nuestro Oasis Cósmico",
  icon: "🌍",
  hero: "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. La Canica Azul y su Escudo Protector",
    "text": "A 150 millones de kilómetros del Sol, la Tierra es el único planeta conocido con biosfera activa. Su atmósfera posee un grosor de apenas 100 km (Línea de Kármán) y está compuesta por 78% de Nitrógeno y 21% de Oxígeno, frenando meteoritos y reteniendo agua líquida y océanos.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Fotografía original \"Earthrise\" (Salida de la Tierra) tomada desde órbita lunar.",
      "url": "https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🛰️",
    "t": "2. La Estación Espacial Internacional (ISS)",
    "text": "A 418 km sobre nuestras cabezas vuela la ISS, un laboratorio de 450 toneladas que navega a 27.600 km/h (7,66 km/s). Da una vuelta completa a la Tierra cada 92 minutos: los astronautas presencian 16 amaneceres y 16 atardeceres cada día en caída libre perpetua.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra y su atmósfera azul vista desde la Estación Espacial Internacional.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "3. Centinelas Orbitales: Hubble y Landsat 9",
    "text": "Por encima de la atmósfera turbulenta operan telescopios y satélites científicos. El Telescopio Hubble (a 535 km) fotografía el universo profundo con nitidez óptica impecable, mientras Landsat 9 (a 705 km) escanea la vegetación y recursos hídricos del planeta.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Campo profundo del universo fotografiado por el Telescopio Espacial Hubble.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. El Ojo Infrarrojo: JWST en Lagrange L2",
    "text": "A 1,5 millones de km de la Tierra, en el punto gravitacional Sol-Tierra L2, opera el Telescopio Espacial James Webb. Su parasol de 5 capas mantiene sus espejos de berilio y oro a -233 °C para detectar la luz infrarroja de las primeras estrellas.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Primer campo profundo del James Webb con lentes gravitacionales.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Cuáles son los dos gases principales que componen más del 99% de la atmósfera terrestre?",
    "options": [
      "Nitrógeno (78%) y Oxígeno (21%)",
      "Dióxido de Carbono (80%) y Metano (19%)",
      "Hidrógeno (75%) y Helio (24%)",
      "Oxígeno (50%) y Vapor de Agua (50%)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué velocidad aproximada viaja la Estación Espacial Internacional (ISS) en órbita baja?",
    "options": [
      "~27.600 km/h (da una vuelta cada 92 minutos)",
      "~1.000 km/h (como un avión comercial)",
      "~100.000 km/h (velocidad de la luz)",
      "100 km/h (como un automóvil)"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena estos artefactos y cuerpos desde el MÁS CERCANO a la Tierra hasta el MÁS LEJANO:",
    "items": [
      "Estación Espacial ISS (418 km)",
      "Telescopio Hubble (535 km)",
      "La Luna (384.400 km)",
      "Telescopio James Webb en L2 (1.500.000 km)"
    ],
    "correctOrder": [
      "Estación Espacial ISS (418 km)",
      "Telescopio Hubble (535 km)",
      "La Luna (384.400 km)",
      "Telescopio James Webb en L2 (1.500.000 km)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué distancia aproximada de la Tierra opera el Telescopio James Webb en el Punto de Lagrange L2?",
    "options": [
      "1,5 millones de kilómetros",
      "400 kilómetros",
      "384.400 kilómetros",
      "150 millones de kilómetros"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
