// Autogenerated by GOALS Data Pipeline from 12_universe.md
import { Lesson } from '../../types';

export const lesson12_Universe: Lesson = {
  id: 12,
  title: "El Universo Observable, el Fondo Cósmico y el Big Bang",
  tag: "Tema 12 • 93.000 Millones al • Teoría + Práctica 2026",
  icon: "🔥",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] El Gran Despertar y los 93.000 Millones de Años Luz",
    "text": "El espacio, el tiempo y toda la energía emergieron hace **13.787 millones de años** en el **Big Bang**. Debido a que el propio tejido del espacio-tiempo se ha estado estirando y expandiendo aceleradamente mientras los fotones viajaban hacia nosotros, el diámetro actual de nuestra esfera de visión —el **Universo Observable**— no mide 13.800 millones de años luz, sino **$93.000\\text{ millones de años luz}$ (28,5 Gigaparsecs)**, conteniendo más de **2 billones de galaxias**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Mapa de fluctuaciones de temperatura del Fondo Cósmico de Microondas captado por Planck",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Foto de Bebé del Cosmos: El CMB ($2,725\\text{ K}$)",
    "text": "Durante los primeros 380.000 años, el cosmos era una niebla de plasma opaco de protones y electrones tan densa que la luz no podía viajar. Cuando la temperatura bajó a $3.000\\text{ Kelvin}$, los electrones se unieron a los protones (Recombinación) y el universo se volvió transparente de golpe. Hoy, esa primera luz fósil se ha enfriado por la expansión del espacio hasta los **$2,725\\text{ Kelvin}$ ($-270,42\\text{ }^\\circ\\text{C}$)** y baña todo el cielo nocturno en forma de microondas: el **Fondo Cósmico de Microondas (CMB)**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Espectro de cuerpo negro casi perfecto del fondo cósmico medido por COBE y Planck",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌌",
    "t": "[Teoría] El Pastel Cósmico: El 95% Invisible del Universo",
    "text": "El censo definitivo de masa y energía del cosmos (misión Planck) revela una lección de humildad para la humanidad:\n- **68,3% Energía Oscura ($\\Lambda$)**: Una presión intrínseca del vacío que hace que el universo se expanda cada vez más rápido.\n- **26,8% Materia Oscura Fría (CDM)**: Partículas no detectadas que actúan como el andamio gravitatorio de las galaxias.\n- **4,9% Materia Bariónica Normal**: Todos los átomos de la tabla periódica, todas las estrellas, planetas, nubes de gas y seres vivos de todas las galaxias.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Composición del universo según el modelo estándar cosmológico Lambda-CDM",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🔭",
    "t": "[Teoría] El Amanecer Cósmico con el Telescopio James Webb",
    "text": "El Telescopio Espacial James Webb (JWST) actúa como una máquina del tiempo infrarroja capaz de observar el **Amanecer Cósmico** (la era de Reionización). Ha fotografiado galaxias como **JADES-GS-z14-0**, que brillaban cuando el universo tenía solo **290 millones de años** (apenas el 2% de su edad actual), desafiando las teorías clásicas al revelar que las primeras estrellas se formaron mucho antes y eran más masivas de lo previsto.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Campo ultra-profundo con las galaxias más tempranas del universo captadas por James Webb",
      "url": "https://images-assets.nasa.gov/image/PIA25325/PIA25325~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Práctica 2026] La Caza de Ondas Gravitacionales del Big Bang",
    "text": "En 2026, el **Simons Observatory** y el telescopio **BICEP Array** en el desierto de Atacama y el Polo Sur miden la **Polarización de Modo B** en los fotones del CMB para detectar el eco de las **Ondas Gravitacionales Primordiales** generadas durante la fracción de segundo de la Inflación Cósmica ($10^{-35}\\text{ segundos}$ tras el Big Bang).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Telescopios del Simons Observatory en el altiplano de Atacama observando el CMB",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "Si el Universo tiene 13.800 millones de años, ¿por qué el diámetro del Universo Observable mide 93.000 millones de años luz?",
    "options": [
      "Porque el tejido del espacio-tiempo se ha expandido continuamente mientras los fotones de luz viajaban hacia nosotros",
      "Porque la luz se mueve al doble de velocidad en el espacio profundo",
      "Porque los espejos de los telescopios multiplican ópticamente las distancias",
      "Porque existen universos paralelos reflejados en el cielo"
    ],
    "answer": 0,
    "explanation": "El espacio no es estático; se ha expandido de forma acumulativa durante los 13.800 millones de años de viaje de la luz, situando a los emisores originales a una distancia comóvil actual de 46.500 millones de años luz de radio (93.000 millones de al de diámetro)."
  },
  {
    "type": "choice",
    "question": "¿Qué es el Fondo Cósmico de Microondas (CMB) en la astrofísica moderna?",
    "options": [
      "La radiación térmica fósil liberada 380.000 años tras el Big Bang cuando el plasma se enfrió a 3.000 K y el universo se volvió transparente",
      "El calor emitido por las chimeneas volcánicas de los exoplanetas",
      "La luz reflejada por los anillos de Saturno",
      "La red de señales de telecomunicaciones de la Tierra"
    ],
    "answer": 0,
    "explanation": "El CMB es el remanente térmico de la Recombinación, cuando los fotones se desacoplaron de la materia, viajando libremente por el cosmos hasta hoy.",
    "photo": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿Qué fracción aproximada del contenido de masa-energía del universo compone la materia ordinaria (átomos, estrellas y seres vivos)?",
    "options": [
      "Solo alrededor de un 4,9% (el 95,1% restante es Energía Oscura y Materia Oscura)",
      "El 100% de todo el cosmos",
      "El 50% exacto",
      "Menos del 0,00001%"
    ],
    "answer": 0,
    "explanation": "El modelo cosmológico estándar Lambda-CDM establece que la materia bariónica visible representa solo el 4,9% del pastel cósmico total."
  },
  {
    "type": "choice",
    "question": "¿Qué propiedad física describe a la Energía Oscura en el modelo cosmológico?",
    "options": [
      "Una energía intrínseca del vacío con presión negativa que impulsa la expansión acelerada del espacio",
      "Un tipo de gasolina espacial que arde en las estrellas",
      "Agujeros negros que absorben galaxias enteras",
      "La sombra que proyecta la Luna sobre la Tierra"
    ],
    "answer": 0,
    "explanation": "Descubierta en 1998 a través de supernovas tipo Ia, la energía oscura representa el 68,3% del universo y acelera la tasa de expansión cósmica."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente las grandes eras de la historia de nuestro Universo desde el origen:",
    "items": [
      "Big Bang e Inflación Cósmica Cuántica (t = 0 a 10^-32 segundos)",
      "Recombinación y emisión de la luz del Fondo Cósmico CMB (t = 380.000 años)",
      "Amanecer Cósmico y nacimiento de las primeras estrellas gigantes (t ~ 200 a 300 Millones de años)",
      "Formación del Sistema Solar y el planeta Tierra (t = 9.200 Millones de años tras el Big Bang)",
      "Era actual dominada por la expansión acelerada de la Energía Oscura (t = 13.800 Millones de años)"
    ],
    "correctOrder": [
      "Big Bang e Inflación Cósmica Cuántica (t = 0 a 10^-32 segundos)",
      "Recombinación y emisión de la luz del Fondo Cósmico CMB (t = 380.000 años)",
      "Amanecer Cósmico y nacimiento de las primeras estrellas gigantes (t ~ 200 a 300 Millones de años)",
      "Formación del Sistema Solar y el planeta Tierra (t = 9.200 Millones de años tras el Big Bang)",
      "Era actual dominada por la expansión acelerada de la Energía Oscura (t = 13.800 Millones de años)"
    ],
    "explanation": "La cosmología progresa ordenadamente desde la singularidad inicial y la sopa primordial hasta la formación de galaxias, el nacimiento del Sol y la era actual."
  }
]
};
