// Autogenerated by GOALS Data Pipeline from 02_eclipses_y_el_gran_eclipse_solar_2026_en_espana.md
import { Lesson } from '../../types';

export const lesson02_Eclipses_y_el_gran_eclipse_solar_2026_en_espana: Lesson = {
  id: 2,
  title: "Eclipses y el Gran Eclipse Solar 2026 en España",
  tag: "Tema 2/12 • 384.400 km • Geometría Celestial",
  icon: "🌑",
  hero: "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. Geometría de la Ocultación: Umbra y Penumbra",
    "text": "Un eclipse solar ocurre cuando la Luna se interpone exactamente entre el Sol y la Tierra durante la fase de Luna Nueva. El cono de sombra proyectado consta de la Umbra (bloqueo solar total al 100%) y la Penumbra (bloqueo parcial). En la umbra, el día se transforma en noche y la temperatura cae varios grados.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Corona solar y llamaradas en la fase de totalidad de un eclipse total de Sol.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌑",
    "t": "2. La Inclinación Orbital Lunar de 5.14° y los Nodos",
    "text": "La órbita de la Luna alrededor de la Tierra está inclinada 5,14° respecto al plano de la órbita terrestre (eclíptica). Por eso no hay eclipses en cada Luna Nueva: solo se producen cuando la Luna cruza los 'Nodos', los dos puntos de intersección entre ambos planos orbitales.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Alineación de la Eclíptica y fases lunares en el espacio.",
      "url": "https://images.unsplash.com/photo-1522030299830-16b8d3d049fe?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌑",
    "t": "3. El Gran Eclipse Total del 12 de Agosto de 2026",
    "text": "El 12 de agosto de 2026, la franja de totalidad de 290 km de ancho barrerá el norte y este de España al atardecer (19:30 - 20:30 CEST). Ciudades como A Coruña, Oviedo, Santander, León, Burgos, Valladolid, Zaragoza, Castellón, Valencia y Palma presenciarán hasta 1m 48s de oscuridad total.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La sombra de la Luna proyectada sobre la superficie terrestre.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. Perlas de Baily, Anillo de Diamantes y Corona",
    "text": "Segundos antes de la totalidad, los últimos rayos solares atraviesan los valles del relieve lunar formando las Perlas de Baily. Cuando queda un único haz, destella el Anillo de Diamantes. Al taparse la fotosfera, se hace visible la Corona Solar: la atmósfera exterior del Sol a más de 1.000.000 °C.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Efecto del Anillo de Diamantes y la corona solar en el momento cumbre.",
      "url": "https://images.unsplash.com/photo-1532693322450-2cb5c511067d?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué condición orbital indispensable debe cumplirse para que ocurra un eclipse solar?",
    "options": [
      "Luna Nueva situada en uno de los nodos orbitales",
      "Luna Llena situada en el punto más alejado de la Tierra",
      "Cualquier Luna Nueva sin importar la inclinación",
      "Alineación de la Tierra entre el Sol y la Luna"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuánto mide la inclinación de la órbita de la Luna respecto al plano orbital terrestre (eclíptica)?",
    "options": [
      "5,14 grados",
      "23,44 grados",
      "0 grados (son totalmente coplanares)",
      "90 grados"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los fenómenos visibles en un eclipse solar total:",
    "items": [
      "Fase Parcial (Penumbra)",
      "Perlas de Baily",
      "Anillo de Diamantes",
      "Totalidad (Corona Solar visible)"
    ],
    "correctOrder": [
      "Fase Parcial (Penumbra)",
      "Perlas de Baily",
      "Anillo de Diamantes",
      "Totalidad (Corona Solar visible)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cuándo fue el último eclipse solar total que cruzó la España peninsular antes del 12 de agosto de 2026?",
    "options": [
      "30 de agosto de 1905 (hace más de 120 años)",
      "11 de julio de 1991",
      "20 de marzo de 2015",
      "Nunca antes en la historia"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
