// Autogenerated by GOALS Data Pipeline from 04_orbit.md
import { Lesson } from '../../types';

export const lesson04_Orbit: Lesson = {
  id: 4,
  title: "Traslación Anual y Afelio/Perihelio",
  tag: "Tema 4 • 1 UA (149.6M km) • Teoría + Práctica 2026",
  icon: "🛰️",
  hero: "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] La Gran Pista Elíptica y la Primera Ley de Kepler",
    "text": "La Tierra no describe un círculo perfecto alrededor del Sol, sino una **órbita elíptica** de excentricidad baja ($e = 0,0167$) a lo largo de un circuito de **940 millones de kilómetros**. Según la **Primera Ley de Kepler**, el Sol no se encuentra en el centro de la elipse, sino en uno de sus focos geométricos. Nuestro planeta viaja por el vacío a una velocidad media prodigiosa de **$107.200\\text{ km/h}$ ($29,78\\text{ km/s}$)**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La Tierra en su órbita elíptica alrededor del Sol",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Ley de las Áreas: Perihelio vs Afelio",
    "text": "La **Segunda Ley de Kepler** establece que el vector que une el Sol y la Tierra barre áreas iguales en tiempos iguales. Por ello, la Tierra no viaja siempre a la misma velocidad:\n- **Perihelio (3-4 de enero)**: Estamos en el punto más cercano al Sol a **147,1 millones de km**, viajando a su velocidad máxima de **$30,29\\text{ km/s}$ ($109.000\\text{ km/h}$)**.\n- **Afelio (3-5 de julio)**: Estamos en el punto más lejano a **152,1 millones de km**, desacelerando a su velocidad mínima de **$29,29\\text{ km/s}$ ($105.400\\text{ km/h}$)**.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Comparativa orbital de distancias entre afelio y perihelio",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Unidad Astronómica (1 UA) y la Velocidad de la Luz",
    "text": "La distancia media de la Tierra al Sol define la unidad métrica fundamental del Sistema Solar: la **Unidad Astronómica ($1\\text{ UA} \\approx 149.597.870\\text{ km}$)**. Como la velocidad de la luz en el vacío es de $299.792\\text{ km/s}$, la luz solar que ilumina nuestro rostro en la playa tardó:\n$$t = \\frac{149.600.000\\text{ km}}{300.000\\text{ km/s}} \\approx 499\\text{ segundos} = 8\\text{ minutos y } 19\\text{ segundos}$$\nSiempre vemos el Sol tal como era hace más de 8 minutos en el pasado.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Emisión solar en luz visible y rayos ultravioleta captada por SDO",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] La Tercera Ley de Kepler y la Balanza Cósmica",
    "text": "La **Tercera Ley de Kepler ($P^2 = a^3$)** relaciona el tiempo que tarda un planeta en dar una vuelta completa ($P$ en años) con su distancia media al Sol ($a$ en UA):\n- **Mercurio** (0,39 UA): Tarda solo 88 días a $47,4\\text{ km/s}$.\n- **Tierra** (1,00 UA): Tarda 365,25 días a $29,8\\text{ km/s}$.\n- **Neptuno** (30,07 UA): Tarda 164,8 años a solo $5,4\\text{ km/s}$.\nCuanto más lejos está un mundo, más débil es la gravedad solar y más lento debe moverse para no caer hacia el Sol.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Comparativa de órbitas keplerianas de los planetas del sistema solar",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Práctica 2026] La Sonda Parker Solar Probe a 692.000 km/h",
    "text": "Aprovechando la Segunda Ley de Kepler y la asistencia gravitatoria de Venus, la sonda **Parker Solar Probe de la NASA** alcanza en sus perihelios velocidades récord de **$692.000\\text{ km/h}$ ($192\\text{ km/s}$)** pasando a solo 6,1 millones de kilómetros de la superficie solar, rozando la corona solar mientras su escudo de carbono soporta $1.400\\text{ }^\\circ\\text{C}$.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Sonda Parker Solar Probe aproximándose a la corona solar",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿En qué momento del año la Tierra se desplaza a su máxima velocidad orbital (~30,3 km/s)?",
    "options": [
      "En el Perihelio (principios de enero), cuando está en el punto más próximo al Sol (147,1 millones de km)",
      "En el Afelio (principios de julio), cuando está en el punto más alejado del Sol",
      "En los equinoccios de primavera y otoño",
      "La velocidad orbital de la Tierra es matemáticamente constante todos los días"
    ],
    "answer": 0,
    "explanation": "Por la Segunda Ley de Kepler, los planetas aumentan su velocidad cuanto más cerca están del foco gravitacional para barrer áreas iguales en tiempos iguales."
  },
  {
    "type": "choice",
    "question": "¿Qué forma geométrica tiene la órbita de la Tierra alrededor del Sol según la Primera Ley de Kepler?",
    "options": [
      "Una elipse de baja excentricidad con el Sol situado en uno de los dos focos",
      "Un círculo perfecto con el Sol en el centro geométrico absoluto",
      "Una espiral cónica que se acerca progresivamente al Sol",
      "Una trayectoria parabólica abierta"
    ],
    "answer": 0,
    "explanation": "Kepler demostró que las órbitas planetarias son elipses y que el Sol no ocupa el centro, sino uno de los focos orbitales."
  },
  {
    "type": "choice",
    "question": "Si la distancia media Tierra-Sol es 1 UA (~149,6 millones de km), ¿cuánto tarda un rayo de luz solar en llegar a la Tierra?",
    "options": [
      "8 minutos y 19 segundos (aproximadamente 499 segundos a 300.000 km/s)",
      "Ocurre de forma instantánea en 0 segundos",
      "24 horas exactas coincidiendo con el día solar",
      "365 días completos"
    ],
    "answer": 0,
    "explanation": "Dividiendo 149.600.000 km entre los 299.792 km/s de la velocidad de la luz se obtienen 499 segundos (~8 min 19 s).",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "choice",
    "question": "Según la Tercera Ley de Kepler ($P^2 = a^3$), ¿qué planeta del Sistema Solar se mueve a MENOR velocidad orbital?",
    "options": [
      "Neptuno (orbita a solo ~5,4 km/s por estar a 30 UA del Sol)",
      "Mercurio (el más veloz a ~47,4 km/s)",
      "La Tierra (a ~29,8 km/s)",
      "Marte (a ~24,1 km/s)"
    ],
    "answer": 0,
    "explanation": "A mayor distancia orbital ($a$), menor es la atracción gravitacional del Sol y menor es la velocidad orbital ($v$) requerida para mantenerse en equilibrio."
  },
  {
    "type": "order",
    "question": "Ordena cronológicamente los hitos del viaje orbital de la Tierra empezando a principios de año:",
    "items": [
      "Perihelio de la Tierra (~3-4 de enero: mínima distancia y máxima velocidad orbital)",
      "Equinoccio de Primavera boreal (~20 de marzo: duración idéntica de día y noche)",
      "Solsticio de Verano boreal (~21 de junio: máxima altura del Sol en el cielo)",
      "Afelio de la Tierra (~4-5 de julio: máxima distancia y mínima velocidad orbital)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año en el norte)"
    ],
    "correctOrder": [
      "Perihelio de la Tierra (~3-4 de enero: mínima distancia y máxima velocidad orbital)",
      "Equinoccio de Primavera boreal (~20 de marzo: duración idéntica de día y noche)",
      "Solsticio de Verano boreal (~21 de junio: máxima altura del Sol en el cielo)",
      "Afelio de la Tierra (~4-5 de julio: máxima distancia y mínima velocidad orbital)",
      "Solsticio de Invierno boreal (~21 de diciembre: día más corto del año en el norte)"
    ],
    "explanation": "El ciclo anual progresa desde el perihelio en enero pasando por equinoccios y solsticios hasta el afelio en julio y el cierre invernal."
  }
]
};
