// Autogenerated by GOALS Data Pipeline from 11_la_red_cosmica_laniakea_y_el_gran_atractor.md
import { Lesson } from '../../types';

export const lesson11_La_red_cosmica_laniakea_y_el_gran_atractor: Lesson = {
  id: 11,
  title: "La Red Cósmica Laniakea y el Gran Atractor",
  tag: "Tema 11/12 • 520 Millones al • El Gran Atractor",
  icon: "🕸️",
  hero: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
  steps: [
  {
    "icon": "✨",
    "t": "1. Laniakea: 'Cielo Inmenso Inconmensurable'",
    "text": "Nuestra galaxia y el Grupo Local pertenecen a Laniakea ('Cielo Inmenso' en hawaiano), un supercúmulo de 520 millones de años luz de diámetro que engloba más de 100.000 galaxias y 10¹⁷ masas solares, unidas por ríos y filamentos gravitatorios.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Reconstrucción tridimensional de los filamentos y corrientes de galaxias en Laniakea.",
      "url": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "2. El Misterioso Gran Atractor",
    "text": "Todas las 100.000 galaxias de Laniakea fluyen hacia un punto focal gravitatorio central llamado el Gran Atractor, ubicado en la 'Zona de Evitación' (oculta tras el gas y polvo del plano de la Vía Láctea), hacia el que nos desplazamos a más de 600 km/s (2,2 millones de km/h).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Cúmulo de galaxias masivo distorsionando el espacio con lentes gravitacionales.",
      "url": "https://images.unsplash.com/photo-1541185933-ef5d8ed016c2?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "3. El Cúmulo de Virgo y los Vecinos de Laniakea",
    "text": "El corazón de nuestro sector es el Cúmulo de Virgo (a 54 millones de al), dominado por la galaxia elíptica M87 cuyo agujero negro supermasivo fue fotografiado en 2019. Laniakea limita con otros supercúmulos como Perseo-Piscis y Coma.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "El chorro de plasma relativista emanando del núcleo de la galaxia M87.",
      "url": "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "4. El Repulsor Dipolo y los Grandes Vacíos",
    "text": "Entre los filamentos de galaxias se extienden los 'Grandes Vacíos Cósmicos', regiones de cientos de millones de años luz casi desprovistas de materia. Frente al Gran Atractor se halla el Repulsor Dipolo, un inmenso vacío que empuja gravitatoriamente a nuestra galaxia.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Estructura esponjosa de la telaraña cósmica y grandes vacíos.",
      "url": "https://images.unsplash.com/photo-1538370965046-79c0d6907d47?auto=format&fit=crop&w=1200&q=80",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Qué es el Supercúmulo Laniakea y qué tamaño aproximado tiene?",
    "options": [
      "Nuestro supercúmulo de galaxias de unos 520 millones de años luz que engloba más de 100.000 galaxias",
      "Una galaxia espiral cercana a la Vía Láctea",
      "Un agujero negro en el centro de la Vía Láctea",
      "Un planeta extrasolar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿Cómo se llama el centro de atracción gravitacional hacia el que se desplazan todas las galaxias de Laniakea a más de 600 km/s?",
    "options": [
      "El Gran Atractor",
      "El Horizonte de Sucesos",
      "El Punto Subsolar",
      "La Estrella Polar"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "order",
    "question": "Ordena las siguientes estructuras cósmicas desde la MÁS PEQUEÑA hasta la MÁS GRANDE:",
    "items": [
      "Grupo Local (10 millones al)",
      "Cúmulo de Virgo (54 millones al)",
      "Supercúmulo Laniakea (520 millones al)",
      "Universo Observable (93.000 millones al)"
    ],
    "correctOrder": [
      "Grupo Local (10 millones al)",
      "Cúmulo de Virgo (54 millones al)",
      "Supercúmulo Laniakea (520 millones al)",
      "Universo Observable (93.000 millones al)"
    ],
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  },
  {
    "type": "choice",
    "question": "¿A qué se asemeja la distribución de la materia en el cosmos a escalas de cientos de millones de años luz?",
    "options": [
      "A una esponja de filamentos y telarañas que rodean inmensos vacíos cósmicos",
      "A esferas sólidas concéntricas perfectas",
      "A una línea recta uniforme sin variaciones",
      "A un disco plano bidimensional"
    ],
    "answer": 0,
    "explanation": "Revisa el material de la lección para reforzar este concepto."
  }
]
};
