// Autogenerated by GOALS Data Pipeline from 02_eclipses.md
import { Lesson } from '../../types';

export const lesson02_Eclipses: Lesson = {
  id: 2,
  title: "Eclipses y el Gran Eclipse 2026 en España",
  tag: "Tema 2 • 384.400 km • Teoría + Práctica 2026",
  icon: "🌑",
  hero: "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
  steps: [
  {
    "icon": "✨",
    "t": "[Teoría] La Asombrosa Coincidencia del Tamaño Angular de 0,5°",
    "text": "El Sol es unas 400 veces más grande en diámetro que la Luna ($1.392.700\\text{ km}$ frente a $3.474\\text{ km}$), pero se encuentra unas 400 veces más lejos de la Tierra ($149,6\\text{ millones de km}$ frente a $384.400\\text{ km}$). Debido a esta coincidencia geométrica, ambos cuerpos celestes tienen exactamente el **mismo tamaño aparente en nuestro cielo: un diámetro angular de $0,5^\\circ$**. Cuando la Luna pasa exactamente entre el Sol y la Tierra, es capaz de ocultar milimétricamente el disco solar.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Alineación del eclipse solar total con la corona resplandeciente",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌑",
    "t": "[Teoría] La Cuesta de 5,14° y los Nodos Lunares",
    "text": "Si el plano de la órbita de la Luna fuera idéntico al de la Tierra alrededor del Sol, tendríamos un eclipse solar en cada Luna Nueva y un eclipse lunar en cada Luna Llena. Sin embargo, la órbita lunar está **inclinada $5,14^\\circ$ respecto a la eclíptica**. La mayoría de las veces, la sombra de la Luna pasa por encima del Polo Norte o por debajo del Polo Sur terrestre. Un eclipse solo ocurre cuando la Luna Nueva coincide con la **Línea de Nodos** (los dos puntos de intersección orbital).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Esquema orbital de la inclinación lunar de 5.14 grados y los nodos",
      "url": "https://images-assets.nasa.gov/image/PIA22353/PIA22353~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "✨",
    "t": "[Teoría] Anatomía de la Sombra: Umbra, Penumbra y Antumbra",
    "text": "La Luna proyecta en el espacio dos conos de sombra concéntricos:\n1. **La Umbra**: La zona interior y más oscura, donde el Sol queda bloqueado al 100%. Quien esté dentro de la umbra ve un **Eclipse Total** y se hace de noche en pleno día.\n2. **La Penumbra**: La zona exterior y más ancha, donde el Sol solo se cubre parcialmente (Eclipse Parcial).\n3. **La Antumbra**: Si la Luna está en el apogeo (más lejos), la umbra no llega a tocar la Tierra y se produce un **Eclipse Anular** (\"anillo de fuego\").",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "La sombra de la Luna proyectada sobre la superficie de la Tierra vista desde el espacio",
      "url": "https://images-assets.nasa.gov/image/iss064e007861/iss064e007861~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "🌑",
    "t": "[Práctica 2026] El Gran Eclipse Total del 12 de Agosto de 2026 en España",
    "text": "El **12 de agosto de 2026**, España vivirá su primer eclipse solar total visible desde la península en 121 años. Al atardecer (entre las 19:30 y las 20:30 CEST), la franja de totalidad de más de 250 km de ancho barrerá Galicia, Asturias, Cantabria, País Vasco, Castilla y León, La Rioja, Navarra, Aragón, Cataluña, Comunidad Valenciana y Baleares. Durante casi 2 minutos la temperatura caerá entre 3°C y 6°C, se levantará una brisa de eclipse y aparecerán planetas y estrellas en el cielo crepuscular.",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Destello de las Perlas de Baily y anillo de diamantes antes de la totalidad",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  },
  {
    "icon": "☀️",
    "t": "[Teoría] La Corona Solar y la Misión ESA PROBA-3",
    "text": "Durante los minutos de totalidad, la Luna tapa el deslumbrante disco solar permitiendo ver a simple vista la **Corona Solar**: una atmósfera de plasma magnetizado que se extiende millones de kilómetros en el espacio a temperaturas desconcertantes de más de **$1.000.000\\text{ }^\\circ\\text{C}$** (mucho más caliente que la superficie del Sol, que está a $5.500\\text{ }^\\circ\\text{C}$).",
    "wow": "",
    "scene": "space_default",
    "photo": {
      "caption": "Corona solar de plasma captada durante la fase de totalidad",
      "url": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg",
      "credit": "NASA / ESA"
    }
  }
],
  test: [
  {
    "type": "choice",
    "question": "¿Por qué no ocurre un eclipse total de Sol en cada fase de Luna Nueva?",
    "options": [
      "Porque la órbita de la Luna está inclinada 5,14° respecto a la eclíptica y su sombra suele pasar por encima o por debajo de la Tierra",
      "Porque la Luna solo proyecta sombra hacia el espacio una vez cada siglo",
      "Porque la atmósfera terrestre desvía la luz solar impidiendo la formación de sombras",
      "Porque el Sol se apaga durante la noche"
    ],
    "answer": 0,
    "explanation": "La inclinación de 5,14° de la órbita lunar hace que el Sol, la Luna y la Tierra solo se alineen en línea recta perfecta cuando la Luna cruza los puntos nodales."
  },
  {
    "type": "choice",
    "question": "¿Cuál es la coincidencia geométrica que permite que la Luna tape al Sol de forma exacta?",
    "options": [
      "El Sol es 400 veces mayor en diámetro que la Luna pero está 400 veces más lejos, teniendo ambos ~0,5° de tamaño aparente",
      "La Luna y el Sol tienen exactamente el mismo tamaño físico en kilómetros",
      "La Tierra atrae a la Luna con el doble de fuerza gravitacional en verano",
      "La Luna se hincha al entrar en la sombra terrestre"
    ],
    "answer": 0,
    "explanation": "Ambos objetos subtienden un ángulo visual de aproximadamente medio grado (30 minutos de arco) en la bóveda celeste."
  },
  {
    "type": "choice",
    "question": "¿Qué fenómeno óptico ocurre en el borde lunar justo antes y después de la totalidad?",
    "options": [
      "Las Perlas de Baily y el Anillo de Diamantes, provocados por los rayos solares atravesando los valles y cráteres lunares",
      "La formación de un arcoíris lunar permanente",
      "La emisión de rayos gamma concentrados",
      "El cambio de color del mar de azul a verde"
    ],
    "answer": 0,
    "explanation": "El relieve escarpado de la Luna deja pasar los últimos rayos de luz a través de sus valles montañosos, creando destellos como perlas brillantes (Perlas de Baily).",
    "photo": "https://images-assets.nasa.gov/image/GSFC_20171208_Archive_e001435/GSFC_20171208_Archive_e001435~orig.jpg"
  },
  {
    "type": "choice",
    "question": "¿En qué zona de la sombra lunar debe estar un observador para presenciar un eclipse solar 100% total?",
    "options": [
      "En el interior del cono de la Umbra",
      "En la Penumbra exterior",
      "En la estratosfera por encima de las nubes",
      "En el lado nocturno de la Tierra"
    ],
    "answer": 0,
    "explanation": "La Umbra es la región cónica donde la Luna cubre por completo el disco solar; en la Penumbra solo se ve un eclipse parcial."
  },
  {
    "type": "order",
    "question": "Ordena la secuencia cronológica de eventos durante un eclipse solar total:",
    "items": [
      "Primer Contacto C1 (La Luna comienza a morder el disco solar en fase parcial)",
      "Descenso de temperatura y cambio en la iluminación ambiental",
      "Perlas de Baily y destello del Anillo de Diamantes",
      "Segundo Contacto C2 y Totalidad (Aparición de la Corona Solar y estrellas)",
      "Cuarto Contacto C4 (La Luna abandona totalmente el disco del Sol)"
    ],
    "correctOrder": [
      "Primer Contacto C1 (La Luna comienza a morder el disco solar en fase parcial)",
      "Descenso de temperatura y cambio en la iluminación ambiental",
      "Perlas de Baily y destello del Anillo de Diamantes",
      "Segundo Contacto C2 y Totalidad (Aparición de la Corona Solar y estrellas)",
      "Cuarto Contacto C4 (La Luna abandona totalmente el disco del Sol)"
    ],
    "explanation": "El eclipse evoluciona desde el primer contacto visual hasta el clímax de la totalidad con la corona solar visible, finalizando en el cuarto contacto."
  }
]
};
