/**
 * scripts/compileCurriculum.ts
 * Script CLI de Compilación, Validación y Sincronización Automática con Firestore
 * 
 * Uso:
 *   npx tsx scripts/compileCurriculum.ts [--sync-firebase] [--discipline=astro] [--dry-run]
 */

import * as fs from 'fs';
import * as path from 'path';
import { MarkdownCurriculumParser } from '../src/core/pipeline/MarkdownCurriculumParser';
import { CurriculumValidator } from '../src/core/pipeline/CurriculumValidator';

const args = process.argv.slice(2);
const shouldSyncFirebase = args.includes('--sync-firebase');
const isDryRun = args.includes('--dry-run');
const disciplineFilter = args.find(a => a.startsWith('--discipline='))?.split('=')[1] || 'all';

const ROOT_DIR = process.cwd();
const CONTENT_DIR = path.join(ROOT_DIR, 'content', 'curriculum');
const EXPERIENCES_BASE = path.join(ROOT_DIR, 'src', 'experiences');

async function compileAll() {
  console.log('🚀 [GOALS Curriculum Pipeline] Iniciando compilación de lecciones...');

  if (!fs.existsSync(CONTENT_DIR)) {
    console.error(`❌ Directorio de contenido no encontrado: ${CONTENT_DIR}`);
    process.exit(1);
  }

  // Buscar recursivamente todas las carpetas con archivos .md
  function getMarkdownFiles(dir: string): string[] {
    let results: string[] = [];
    const list = fs.readdirSync(dir);
    list.forEach(file => {
      const fullPath = path.join(dir, file);
      const stat = fs.statSync(fullPath);
      if (stat && stat.isDirectory()) {
        results = results.concat(getMarkdownFiles(fullPath));
      } else if (file.endsWith('.md')) {
        results.push(fullPath);
      }
    });
    return results;
  }

  const allMdFiles = getMarkdownFiles(CONTENT_DIR);
  console.log(`📄 Encontrados ${allMdFiles.length} archivos Markdown en ${CONTENT_DIR}`);

  let totalCompiled = 0;
  let totalErrors = 0;
  const compiledByDiscipline: Record<string, any[]> = {};

  for (const filePath of allMdFiles) {
    const relativePath = path.relative(CONTENT_DIR, filePath);
    const parts = relativePath.split(path.sep);
    const discipline = parts[0];

    if (disciplineFilter !== 'all' && discipline !== disciplineFilter) {
      continue;
    }

    const content = fs.readFileSync(filePath, 'utf-8');
    const parsed = MarkdownCurriculumParser.parse(content, discipline);
    const validation = CurriculumValidator.validate(parsed);

    if (!validation.isValid) {
      console.error(`\n❌ Error de validación en: ${relativePath}`);
      validation.criticalErrors.forEach(e => console.error(`   - [${e.code}] ${e.message}`));
      totalErrors++;
      continue;
    }

    if (validation.warnings.length > 0) {
      console.warn(`⚠️  Advertencia en ${relativePath} (Calidad: ${validation.score}/100)`);
    }

    if (!compiledByDiscipline[discipline]) {
      compiledByDiscipline[discipline] = [];
    }
    compiledByDiscipline[discipline].push(parsed);
    totalCompiled++;

    // Generar módulos atómicos de TypeScript para Astronomía (L3 fallback)
    if (!isDryRun && discipline === 'astro') {
      const destLessonsDir = path.join(EXPERIENCES_BASE, 'astro', 'data', 'lessons');
      const destTestsDir = path.join(EXPERIENCES_BASE, 'astro', 'data', 'tests');

      fs.mkdirSync(destLessonsDir, { recursive: true });
      fs.mkdirSync(destTestsDir, { recursive: true });

      const pad = String(parsed.lesson.order).padStart(2, '0');
      const baseName = path.parse(filePath).name.replace(/^\d+_?/, '');
      const capitalized = baseName.charAt(0).toUpperCase() + baseName.slice(1);

      const lessonFileName = `lesson${pad}_${capitalized}.ts`;
      const testFileName = `test${pad}_${capitalized}.ts`;

      const stepsData = parsed.lesson.steps.map(s => ({
        icon: s.icon,
        t: s.title,
        text: s.content,
        wow: s.wowFact || '',
        now: s.nowFact,
        scene: s.model3d?.sceneId || (s as any).scene || 'space_default',
        photo: s.photo
      }));

      const testData = parsed.test.questions.map(q => {
        if (q.type === 'order') {
          return {
            type: 'order',
            question: q.prompt,
            items: q.orderItems ? q.orderItems.map(i => i.label) : [],
            correctOrder: q.orderItems ? q.orderItems.map(i => i.label) : [],
            explanation: q.explanation || 'Excelente ordenamiento secuencial basado en las escalas físicas del universo.',
            photo: q.media?.url
          };
        }
        return {
          type: 'choice',
          question: q.prompt,
          options: q.options || [],
          answer: q.correctAnswer !== undefined ? q.correctAnswer : 0,
          explanation: q.explanation || 'Excelente deducción científica fundamentada en los principios de la lección.',
          photo: q.media?.url
        };
      });

      const lessonCode = `// Autogenerated by GOALS Data Pipeline from ${path.basename(filePath)}\n` +
        `import { Lesson } from '../../types';\n\n` +
        `export const lesson${pad}_${capitalized}: Lesson = {\n` +
        `  id: ${parsed.lesson.order},\n` +
        `  title: ${JSON.stringify(parsed.lesson.title)},\n` +
        `  tag: ${JSON.stringify(parsed.lesson.tag)},\n` +
        `  icon: ${JSON.stringify(parsed.lesson.icon)},\n` +
        `  hero: ${JSON.stringify(parsed.lesson.heroImage)},\n` +
        `  steps: ${JSON.stringify(stepsData, null, 2)},\n` +
        `  test: ${JSON.stringify(testData, null, 2)}\n` +
        `};\n`;

      fs.writeFileSync(path.join(destLessonsDir, lessonFileName), lessonCode, 'utf-8');

      const testCode = `// Autogenerated by GOALS Data Pipeline from ${path.basename(filePath)}\n` +
        `import { Question } from '../../types';\n\n` +
        `export const test${pad}_${capitalized}: Question[] = ${JSON.stringify(testData, null, 2)};\n`;

      fs.writeFileSync(path.join(destTestsDir, testFileName), testCode, 'utf-8');
    }
  }

  console.log(`\n======================================================`);
  console.log(`🎉 Pipeline Finalizado: ${totalCompiled} lecciones compiladas con éxito. (${totalErrors} errores).`);
  console.log(`======================================================\n`);
}

compileAll().catch(console.error);
